package com.tour.dao.impl;

import com.tour.dao.ifc.SmAuthoDAO;
import com.tour.model.SmAutho;
import com.tour.model.SmAuthoExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class SmAuthoDAOImpl extends SqlMapClientDaoSupport implements SmAuthoDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table sm_autho
     *
     * @ibatorgenerated Wed May 13 15:02:13 CST 2015
     */
    public SmAuthoDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table sm_autho
     *
     * @ibatorgenerated Wed May 13 15:02:13 CST 2015
     */
    public int countByExample(SmAuthoExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("sm_autho.ibatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table sm_autho
     *
     * @ibatorgenerated Wed May 13 15:02:13 CST 2015
     */
    public int deleteByExample(SmAuthoExample example) {
        int rows = getSqlMapClientTemplate().delete("sm_autho.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table sm_autho
     *
     * @ibatorgenerated Wed May 13 15:02:13 CST 2015
     */
    public int deleteByPrimaryKey(Integer id) {
        SmAutho key = new SmAutho();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("sm_autho.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table sm_autho
     *
     * @ibatorgenerated Wed May 13 15:02:13 CST 2015
     */
    public void insert(SmAutho record) {
        getSqlMapClientTemplate().insert("sm_autho.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table sm_autho
     *
     * @ibatorgenerated Wed May 13 15:02:13 CST 2015
     */
    public void insertSelective(SmAutho record) {
        getSqlMapClientTemplate().insert("sm_autho.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table sm_autho
     *
     * @ibatorgenerated Wed May 13 15:02:13 CST 2015
     */
    public List selectByExample(SmAuthoExample example) {
        List list = getSqlMapClientTemplate().queryForList("sm_autho.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table sm_autho
     *
     * @ibatorgenerated Wed May 13 15:02:13 CST 2015
     */
    public SmAutho selectByPrimaryKey(Integer id) {
        SmAutho key = new SmAutho();
        key.setId(id);
        SmAutho record = (SmAutho) getSqlMapClientTemplate().queryForObject("sm_autho.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table sm_autho
     *
     * @ibatorgenerated Wed May 13 15:02:13 CST 2015
     */
    public int updateByExampleSelective(SmAutho record, SmAuthoExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("sm_autho.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table sm_autho
     *
     * @ibatorgenerated Wed May 13 15:02:13 CST 2015
     */
    public int updateByExample(SmAutho record, SmAuthoExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("sm_autho.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table sm_autho
     *
     * @ibatorgenerated Wed May 13 15:02:13 CST 2015
     */
    public int updateByPrimaryKeySelective(SmAutho record) {
        int rows = getSqlMapClientTemplate().update("sm_autho.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table sm_autho
     *
     * @ibatorgenerated Wed May 13 15:02:13 CST 2015
     */
    public int updateByPrimaryKey(SmAutho record) {
        int rows = getSqlMapClientTemplate().update("sm_autho.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table sm_autho
     *
     * @ibatorgenerated Wed May 13 15:02:13 CST 2015
     */
    private static class UpdateByExampleParms extends SmAuthoExample {
        private Object record;

        public UpdateByExampleParms(Object record, SmAuthoExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}