package com.tour.dao.impl;

import com.tour.dao.ifc.SmRoleAuthoDAO;
import com.tour.model.SmRoleAutho;
import com.tour.model.SmRoleAuthoExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class SmRoleAuthoDAOImpl extends SqlMapClientDaoSupport implements SmRoleAuthoDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table sm_role_autho
     *
     * @ibatorgenerated Wed May 13 14:51:35 CST 2015
     */
    public SmRoleAuthoDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table sm_role_autho
     *
     * @ibatorgenerated Wed May 13 14:51:35 CST 2015
     */
    public int countByExample(SmRoleAuthoExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("sm_role_autho.ibatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table sm_role_autho
     *
     * @ibatorgenerated Wed May 13 14:51:35 CST 2015
     */
    public int deleteByExample(SmRoleAuthoExample example) {
        int rows = getSqlMapClientTemplate().delete("sm_role_autho.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table sm_role_autho
     *
     * @ibatorgenerated Wed May 13 14:51:35 CST 2015
     */
    public int deleteByPrimaryKey(Integer id) {
        SmRoleAutho key = new SmRoleAutho();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("sm_role_autho.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table sm_role_autho
     *
     * @ibatorgenerated Wed May 13 14:51:35 CST 2015
     */
    public void insert(SmRoleAutho record) {
        getSqlMapClientTemplate().insert("sm_role_autho.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table sm_role_autho
     *
     * @ibatorgenerated Wed May 13 14:51:35 CST 2015
     */
    public void insertSelective(SmRoleAutho record) {
        getSqlMapClientTemplate().insert("sm_role_autho.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table sm_role_autho
     *
     * @ibatorgenerated Wed May 13 14:51:35 CST 2015
     */
    public List selectByExample(SmRoleAuthoExample example) {
        List list = getSqlMapClientTemplate().queryForList("sm_role_autho.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table sm_role_autho
     *
     * @ibatorgenerated Wed May 13 14:51:35 CST 2015
     */
    public SmRoleAutho selectByPrimaryKey(Integer id) {
        SmRoleAutho key = new SmRoleAutho();
        key.setId(id);
        SmRoleAutho record = (SmRoleAutho) getSqlMapClientTemplate().queryForObject("sm_role_autho.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table sm_role_autho
     *
     * @ibatorgenerated Wed May 13 14:51:35 CST 2015
     */
    public int updateByExampleSelective(SmRoleAutho record, SmRoleAuthoExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("sm_role_autho.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table sm_role_autho
     *
     * @ibatorgenerated Wed May 13 14:51:35 CST 2015
     */
    public int updateByExample(SmRoleAutho record, SmRoleAuthoExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("sm_role_autho.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table sm_role_autho
     *
     * @ibatorgenerated Wed May 13 14:51:35 CST 2015
     */
    public int updateByPrimaryKeySelective(SmRoleAutho record) {
        int rows = getSqlMapClientTemplate().update("sm_role_autho.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table sm_role_autho
     *
     * @ibatorgenerated Wed May 13 14:51:35 CST 2015
     */
    public int updateByPrimaryKey(SmRoleAutho record) {
        int rows = getSqlMapClientTemplate().update("sm_role_autho.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table sm_role_autho
     *
     * @ibatorgenerated Wed May 13 14:51:35 CST 2015
     */
    private static class UpdateByExampleParms extends SmRoleAuthoExample {
        private Object record;

        public UpdateByExampleParms(Object record, SmRoleAuthoExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}