package com.tour.dao.impl;

import com.tour.dao.ifc.SmRoleDAO;
import com.tour.model.SmRole;
import com.tour.model.SmRoleExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class SmRoleDAOImpl extends 
SqlMapClientDaoSupport implements SmRoleDAO {

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table sm_role
     * @ibatorgenerated  Wed May 13 14:51:35 CST 2015
     */
    public SmRoleDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table sm_role
     * @ibatorgenerated  Wed May 13 14:51:35 CST 2015
     */
    public int countByExample( SmRoleExample example ) {
        Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
                "sm_role.ibatorgenerated_countByExample", example );
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table sm_role
     * @ibatorgenerated  Wed May 13 14:51:35 CST 2015
     */
    public int deleteByExample( SmRoleExample example ) {
        int rows = getSqlMapClientTemplate().delete( "sm_role.ibatorgenerated_deleteByExample",
                example );
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table sm_role
     * @ibatorgenerated  Wed May 13 14:51:35 CST 2015
     */
    public int deleteByPrimaryKey( Integer id ) {
        SmRole key = new SmRole();
        key.setId( id );
        int rows = getSqlMapClientTemplate().delete( "sm_role.ibatorgenerated_deleteByPrimaryKey",
                key );
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table sm_role
     * @ibatorgenerated  Wed May 13 14:51:35 CST 2015
     */
    public void insert( SmRole record ) {
        getSqlMapClientTemplate().insert( "sm_role.ibatorgenerated_insert", record );
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table sm_role
     * @ibatorgenerated  Wed May 13 14:51:35 CST 2015
     */
    public void insertSelective( SmRole record ) {
        getSqlMapClientTemplate().insert( "sm_role.ibatorgenerated_insertSelective", record );
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table sm_role
     * @ibatorgenerated  Wed May 13 14:51:35 CST 2015
     */
    public List selectByExample( SmRoleExample example ) {
        List list = getSqlMapClientTemplate().queryForList(
                "sm_role.ibatorgenerated_selectByExample", example );
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table sm_role
     * @ibatorgenerated  Wed May 13 14:51:35 CST 2015
     */
    public SmRole selectByPrimaryKey( Integer id ) {
        SmRole key = new SmRole();
        key.setId( id );
        SmRole record = (SmRole) getSqlMapClientTemplate().queryForObject(
                "sm_role.ibatorgenerated_selectByPrimaryKey", key );
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table sm_role
     * @ibatorgenerated  Wed May 13 14:51:35 CST 2015
     */
    public int updateByExampleSelective( SmRole record, SmRoleExample example ) {
        UpdateByExampleParms parms = new UpdateByExampleParms( record, example );
        int rows = getSqlMapClientTemplate().update(
                "sm_role.ibatorgenerated_updateByExampleSelective", parms );
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table sm_role
     * @ibatorgenerated  Wed May 13 14:51:35 CST 2015
     */
    public int updateByExample( SmRole record, SmRoleExample example ) {
        UpdateByExampleParms parms = new UpdateByExampleParms( record, example );
        int rows = getSqlMapClientTemplate().update( "sm_role.ibatorgenerated_updateByExample",
                parms );
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table sm_role
     * @ibatorgenerated  Wed May 13 14:51:35 CST 2015
     */
    public int updateByPrimaryKeySelective( SmRole record ) {
        int rows = getSqlMapClientTemplate().update(
                "sm_role.ibatorgenerated_updateByPrimaryKeySelective", record );
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table sm_role
     * @ibatorgenerated  Wed May 13 14:51:35 CST 2015
     */
    public int updateByPrimaryKey( SmRole record ) {
        int rows = getSqlMapClientTemplate().update( "sm_role.ibatorgenerated_updateByPrimaryKey",
                record );
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator. This class corresponds to the database table sm_role
     * @ibatorgenerated  Wed May 13 14:51:35 CST 2015
     */
    private static class UpdateByExampleParms extends SmRoleExample {
        
        private Object record;
        
        public UpdateByExampleParms( Object record, SmRoleExample example ) {
            super( example );
            this.record = record;
        }
        
        public Object getRecord() {
            return record;
        }
    }
}