package com.tour.dao.impl;

import com.tour.dao.ifc.SmUserDAO;
import com.tour.model.SmUser;
import com.tour.model.SmUserExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class SmUserDAOImpl extends 
SqlMapClientDaoSupport implements SmUserDAO {

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table sm_user
     * @ibatorgenerated  Wed May 13 14:51:35 CST 2015
     */
    public SmUserDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table sm_user
     * @ibatorgenerated  Wed May 13 14:51:35 CST 2015
     */
    public int countByExample( SmUserExample example ) {
        Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
                "sm_user.ibatorgenerated_countByExample", example );
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table sm_user
     * @ibatorgenerated  Wed May 13 14:51:35 CST 2015
     */
    public int deleteByExample( SmUserExample example ) {
        int rows = getSqlMapClientTemplate().delete( "sm_user.ibatorgenerated_deleteByExample",
                example );
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table sm_user
     * @ibatorgenerated  Wed May 13 14:51:35 CST 2015
     */
    public int deleteByPrimaryKey( Integer id ) {
        SmUser key = new SmUser();
        key.setId( id );
        int rows = getSqlMapClientTemplate().delete( "sm_user.ibatorgenerated_deleteByPrimaryKey",
                key );
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table sm_user
     * @ibatorgenerated  Wed May 13 14:51:35 CST 2015
     */
    public void insert( SmUser record ) {
        getSqlMapClientTemplate().insert( "sm_user.ibatorgenerated_insert", record );
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table sm_user
     * @ibatorgenerated  Wed May 13 14:51:35 CST 2015
     */
    public void insertSelective( SmUser record ) {
        getSqlMapClientTemplate().insert( "sm_user.ibatorgenerated_insertSelective", record );
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table sm_user
     * @ibatorgenerated  Wed May 13 14:51:35 CST 2015
     */
    public List selectByExample( SmUserExample example ) {
        List list = getSqlMapClientTemplate().queryForList(
                "sm_user.ibatorgenerated_selectByExample", example );
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table sm_user
     * @ibatorgenerated  Wed May 13 14:51:35 CST 2015
     */
    public SmUser selectByPrimaryKey( Integer id ) {
        SmUser key = new SmUser();
        key.setId( id );
        SmUser record = (SmUser) getSqlMapClientTemplate().queryForObject(
                "sm_user.ibatorgenerated_selectByPrimaryKey", key );
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table sm_user
     * @ibatorgenerated  Wed May 13 14:51:35 CST 2015
     */
    public int updateByExampleSelective( SmUser record, SmUserExample example ) {
        UpdateByExampleParms parms = new UpdateByExampleParms( record, example );
        int rows = getSqlMapClientTemplate().update(
                "sm_user.ibatorgenerated_updateByExampleSelective", parms );
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table sm_user
     * @ibatorgenerated  Wed May 13 14:51:35 CST 2015
     */
    public int updateByExample( SmUser record, SmUserExample example ) {
        UpdateByExampleParms parms = new UpdateByExampleParms( record, example );
        int rows = getSqlMapClientTemplate().update( "sm_user.ibatorgenerated_updateByExample",
                parms );
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table sm_user
     * @ibatorgenerated  Wed May 13 14:51:35 CST 2015
     */
    public int updateByPrimaryKeySelective( SmUser record ) {
        int rows = getSqlMapClientTemplate().update(
                "sm_user.ibatorgenerated_updateByPrimaryKeySelective", record );
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table sm_user
     * @ibatorgenerated  Wed May 13 14:51:35 CST 2015
     */
    public int updateByPrimaryKey( SmUser record ) {
        int rows = getSqlMapClientTemplate().update( "sm_user.ibatorgenerated_updateByPrimaryKey",
                record );
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator. This class corresponds to the database table sm_user
     * @ibatorgenerated  Wed May 13 14:51:35 CST 2015
     */
    private static class UpdateByExampleParms extends SmUserExample {
        
        private Object record;
        
        public UpdateByExampleParms( Object record, SmUserExample example ) {
            super( example );
            this.record = record;
        }
        
        public Object getRecord() {
            return record;
        }
    }
}