package com.tour.dao.impl;

import com.tour.dao.ifc.TmCustomerGroupDAO;
import com.tour.model.TmCustomerGroup;
import com.tour.model.TmCustomerGroupExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class TmCustomerGroupDAOImpl extends 
SqlMapClientDaoSupport implements TmCustomerGroupDAO {

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tm_customer_group
     * @ibatorgenerated  Wed May 13 14:51:35 CST 2015
     */
    public TmCustomerGroupDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tm_customer_group
     * @ibatorgenerated  Wed May 13 14:51:35 CST 2015
     */
    public int countByExample( TmCustomerGroupExample example ) {
        Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
                "tm_customer_group.ibatorgenerated_countByExample", example );
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tm_customer_group
     * @ibatorgenerated  Wed May 13 14:51:35 CST 2015
     */
    public int deleteByExample( TmCustomerGroupExample example ) {
        int rows = getSqlMapClientTemplate().delete(
                "tm_customer_group.ibatorgenerated_deleteByExample", example );
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tm_customer_group
     * @ibatorgenerated  Wed May 13 14:51:35 CST 2015
     */
    public int deleteByPrimaryKey( Integer id ) {
        TmCustomerGroup key = new TmCustomerGroup();
        key.setId( id );
        int rows = getSqlMapClientTemplate().delete(
                "tm_customer_group.ibatorgenerated_deleteByPrimaryKey", key );
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tm_customer_group
     * @ibatorgenerated  Wed May 13 14:51:35 CST 2015
     */
    public void insert( TmCustomerGroup record ) {
        getSqlMapClientTemplate().insert( "tm_customer_group.ibatorgenerated_insert", record );
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tm_customer_group
     * @ibatorgenerated  Wed May 13 14:51:35 CST 2015
     */
    public void insertSelective( TmCustomerGroup record ) {
        getSqlMapClientTemplate().insert( "tm_customer_group.ibatorgenerated_insertSelective",
                record );
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tm_customer_group
     * @ibatorgenerated  Wed May 13 14:51:35 CST 2015
     */
    public List selectByExample( TmCustomerGroupExample example ) {
        List list = getSqlMapClientTemplate().queryForList(
                "tm_customer_group.ibatorgenerated_selectByExample", example );
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tm_customer_group
     * @ibatorgenerated  Wed May 13 14:51:35 CST 2015
     */
    public TmCustomerGroup selectByPrimaryKey( Integer id ) {
        TmCustomerGroup key = new TmCustomerGroup();
        key.setId( id );
        TmCustomerGroup record = (TmCustomerGroup) getSqlMapClientTemplate().queryForObject(
                "tm_customer_group.ibatorgenerated_selectByPrimaryKey", key );
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tm_customer_group
     * @ibatorgenerated  Wed May 13 14:51:35 CST 2015
     */
    public int updateByExampleSelective( TmCustomerGroup record, TmCustomerGroupExample example ) {
        UpdateByExampleParms parms = new UpdateByExampleParms( record, example );
        int rows = getSqlMapClientTemplate().update(
                "tm_customer_group.ibatorgenerated_updateByExampleSelective", parms );
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tm_customer_group
     * @ibatorgenerated  Wed May 13 14:51:35 CST 2015
     */
    public int updateByExample( TmCustomerGroup record, TmCustomerGroupExample example ) {
        UpdateByExampleParms parms = new UpdateByExampleParms( record, example );
        int rows = getSqlMapClientTemplate().update(
                "tm_customer_group.ibatorgenerated_updateByExample", parms );
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tm_customer_group
     * @ibatorgenerated  Wed May 13 14:51:35 CST 2015
     */
    public int updateByPrimaryKeySelective( TmCustomerGroup record ) {
        int rows = getSqlMapClientTemplate().update(
                "tm_customer_group.ibatorgenerated_updateByPrimaryKeySelective", record );
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tm_customer_group
     * @ibatorgenerated  Wed May 13 14:51:35 CST 2015
     */
    public int updateByPrimaryKey( TmCustomerGroup record ) {
        int rows = getSqlMapClientTemplate().update(
                "tm_customer_group.ibatorgenerated_updateByPrimaryKey", record );
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator. This class corresponds to the database table tm_customer_group
     * @ibatorgenerated  Wed May 13 14:51:35 CST 2015
     */
    private static class UpdateByExampleParms extends TmCustomerGroupExample {
        
        private Object record;
        
        public UpdateByExampleParms( Object record, TmCustomerGroupExample example ) {
            super( example );
            this.record = record;
        }
        
        public Object getRecord() {
            return record;
        }
    }
}