package com.tour.dao.impl;

import com.tour.dao.ifc.TmCustomerDAO;
import com.tour.model.TmCustomer;
import com.tour.model.TmCustomerExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class TmCustomerDAOImpl extends 
SqlMapClientDaoSupport implements TmCustomerDAO {

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tm_customer
     * @ibatorgenerated  Wed May 13 14:51:35 CST 2015
     */
    public TmCustomerDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tm_customer
     * @ibatorgenerated  Wed May 13 14:51:35 CST 2015
     */
    public int countByExample( TmCustomerExample example ) {
        Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
                "tm_customer.ibatorgenerated_countByExample", example );
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tm_customer
     * @ibatorgenerated  Wed May 13 14:51:35 CST 2015
     */
    public int deleteByExample( TmCustomerExample example ) {
        int rows = getSqlMapClientTemplate().delete( "tm_customer.ibatorgenerated_deleteByExample",
                example );
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tm_customer
     * @ibatorgenerated  Wed May 13 14:51:35 CST 2015
     */
    public int deleteByPrimaryKey( Integer id ) {
        TmCustomer key = new TmCustomer();
        key.setId( id );
        int rows = getSqlMapClientTemplate().delete(
                "tm_customer.ibatorgenerated_deleteByPrimaryKey", key );
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tm_customer
     * @ibatorgenerated  Wed May 13 14:51:35 CST 2015
     */
    public void insert( TmCustomer record ) {
        getSqlMapClientTemplate().insert( "tm_customer.ibatorgenerated_insert", record );
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tm_customer
     * @ibatorgenerated  Wed May 13 14:51:35 CST 2015
     */
    public void insertSelective( TmCustomer record ) {
        getSqlMapClientTemplate().insert( "tm_customer.ibatorgenerated_insertSelective", record );
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tm_customer
     * @ibatorgenerated  Wed May 13 14:51:35 CST 2015
     */
    public List selectByExample( TmCustomerExample example ) {
        List list = getSqlMapClientTemplate().queryForList(
                "tm_customer.ibatorgenerated_selectByExample", example );
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tm_customer
     * @ibatorgenerated  Wed May 13 14:51:35 CST 2015
     */
    public TmCustomer selectByPrimaryKey( Integer id ) {
        TmCustomer key = new TmCustomer();
        key.setId( id );
        TmCustomer record = (TmCustomer) getSqlMapClientTemplate().queryForObject(
                "tm_customer.ibatorgenerated_selectByPrimaryKey", key );
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tm_customer
     * @ibatorgenerated  Wed May 13 14:51:35 CST 2015
     */
    public int updateByExampleSelective( TmCustomer record, TmCustomerExample example ) {
        UpdateByExampleParms parms = new UpdateByExampleParms( record, example );
        int rows = getSqlMapClientTemplate().update(
                "tm_customer.ibatorgenerated_updateByExampleSelective", parms );
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tm_customer
     * @ibatorgenerated  Wed May 13 14:51:35 CST 2015
     */
    public int updateByExample( TmCustomer record, TmCustomerExample example ) {
        UpdateByExampleParms parms = new UpdateByExampleParms( record, example );
        int rows = getSqlMapClientTemplate().update( "tm_customer.ibatorgenerated_updateByExample",
                parms );
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tm_customer
     * @ibatorgenerated  Wed May 13 14:51:35 CST 2015
     */
    public int updateByPrimaryKeySelective( TmCustomer record ) {
        int rows = getSqlMapClientTemplate().update(
                "tm_customer.ibatorgenerated_updateByPrimaryKeySelective", record );
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tm_customer
     * @ibatorgenerated  Wed May 13 14:51:35 CST 2015
     */
    public int updateByPrimaryKey( TmCustomer record ) {
        int rows = getSqlMapClientTemplate().update(
                "tm_customer.ibatorgenerated_updateByPrimaryKey", record );
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator. This class corresponds to the database table tm_customer
     * @ibatorgenerated  Wed May 13 14:51:35 CST 2015
     */
    private static class UpdateByExampleParms extends TmCustomerExample {
        
        private Object record;
        
        public UpdateByExampleParms( Object record, TmCustomerExample example ) {
            super( example );
            this.record = record;
        }
        
        public Object getRecord() {
            return record;
        }
    }
}