package com.tour.dao.impl;

import com.tour.dao.ifc.TmDepartmentDAO;
import com.tour.model.TmDepartment;
import com.tour.model.TmDepartmentExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class TmDepartmentDAOImpl extends 
SqlMapClientDaoSupport implements TmDepartmentDAO {

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tm_department
     * @ibatorgenerated  Wed May 13 14:51:35 CST 2015
     */
    public TmDepartmentDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tm_department
     * @ibatorgenerated  Wed May 13 14:51:35 CST 2015
     */
    public int countByExample( TmDepartmentExample example ) {
        Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
                "tm_department.ibatorgenerated_countByExample", example );
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tm_department
     * @ibatorgenerated  Wed May 13 14:51:35 CST 2015
     */
    public int deleteByExample( TmDepartmentExample example ) {
        int rows = getSqlMapClientTemplate().delete(
                "tm_department.ibatorgenerated_deleteByExample", example );
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tm_department
     * @ibatorgenerated  Wed May 13 14:51:35 CST 2015
     */
    public int deleteByPrimaryKey( Integer id ) {
        TmDepartment key = new TmDepartment();
        key.setId( id );
        int rows = getSqlMapClientTemplate().delete(
                "tm_department.ibatorgenerated_deleteByPrimaryKey", key );
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tm_department
     * @ibatorgenerated  Wed May 13 14:51:35 CST 2015
     */
    public void insert( TmDepartment record ) {
        getSqlMapClientTemplate().insert( "tm_department.ibatorgenerated_insert", record );
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tm_department
     * @ibatorgenerated  Wed May 13 14:51:35 CST 2015
     */
    public void insertSelective( TmDepartment record ) {
        getSqlMapClientTemplate().insert( "tm_department.ibatorgenerated_insertSelective", record );
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tm_department
     * @ibatorgenerated  Wed May 13 14:51:35 CST 2015
     */
    public List selectByExample( TmDepartmentExample example ) {
        List list = getSqlMapClientTemplate().queryForList(
                "tm_department.ibatorgenerated_selectByExample", example );
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tm_department
     * @ibatorgenerated  Wed May 13 14:51:35 CST 2015
     */
    public TmDepartment selectByPrimaryKey( Integer id ) {
        TmDepartment key = new TmDepartment();
        key.setId( id );
        TmDepartment record = (TmDepartment) getSqlMapClientTemplate().queryForObject(
                "tm_department.ibatorgenerated_selectByPrimaryKey", key );
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tm_department
     * @ibatorgenerated  Wed May 13 14:51:35 CST 2015
     */
    public int updateByExampleSelective( TmDepartment record, TmDepartmentExample example ) {
        UpdateByExampleParms parms = new UpdateByExampleParms( record, example );
        int rows = getSqlMapClientTemplate().update(
                "tm_department.ibatorgenerated_updateByExampleSelective", parms );
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tm_department
     * @ibatorgenerated  Wed May 13 14:51:35 CST 2015
     */
    public int updateByExample( TmDepartment record, TmDepartmentExample example ) {
        UpdateByExampleParms parms = new UpdateByExampleParms( record, example );
        int rows = getSqlMapClientTemplate().update(
                "tm_department.ibatorgenerated_updateByExample", parms );
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tm_department
     * @ibatorgenerated  Wed May 13 14:51:35 CST 2015
     */
    public int updateByPrimaryKeySelective( TmDepartment record ) {
        int rows = getSqlMapClientTemplate().update(
                "tm_department.ibatorgenerated_updateByPrimaryKeySelective", record );
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tm_department
     * @ibatorgenerated  Wed May 13 14:51:35 CST 2015
     */
    public int updateByPrimaryKey( TmDepartment record ) {
        int rows = getSqlMapClientTemplate().update(
                "tm_department.ibatorgenerated_updateByPrimaryKey", record );
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator. This class corresponds to the database table tm_department
     * @ibatorgenerated  Wed May 13 14:51:35 CST 2015
     */
    private static class UpdateByExampleParms extends TmDepartmentExample {
        
        private Object record;
        
        public UpdateByExampleParms( Object record, TmDepartmentExample example ) {
            super( example );
            this.record = record;
        }
        
        public Object getRecord() {
            return record;
        }
    }
}