package com.tour.dao.impl;

import com.tour.dao.ifc.TmDetailDAO;
import com.tour.model.TmDetail;
import com.tour.model.TmDetailExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class TmDetailDAOImpl extends 
SqlMapClientDaoSupport implements TmDetailDAO {

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tm_detail
     * @ibatorgenerated  Wed May 13 14:51:35 CST 2015
     */
    public TmDetailDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tm_detail
     * @ibatorgenerated  Wed May 13 14:51:35 CST 2015
     */
    public int countByExample( TmDetailExample example ) {
        Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
                "tm_detail.ibatorgenerated_countByExample", example );
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tm_detail
     * @ibatorgenerated  Wed May 13 14:51:35 CST 2015
     */
    public int deleteByExample( TmDetailExample example ) {
        int rows = getSqlMapClientTemplate().delete( "tm_detail.ibatorgenerated_deleteByExample",
                example );
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tm_detail
     * @ibatorgenerated  Wed May 13 14:51:35 CST 2015
     */
    public int deleteByPrimaryKey( Integer id ) {
        TmDetail key = new TmDetail();
        key.setId( id );
        int rows = getSqlMapClientTemplate().delete(
                "tm_detail.ibatorgenerated_deleteByPrimaryKey", key );
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tm_detail
     * @ibatorgenerated  Wed May 13 14:51:35 CST 2015
     */
    public void insert( TmDetail record ) {
        getSqlMapClientTemplate().insert( "tm_detail.ibatorgenerated_insert", record );
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tm_detail
     * @ibatorgenerated  Wed May 13 14:51:35 CST 2015
     */
    public void insertSelective( TmDetail record ) {
        getSqlMapClientTemplate().insert( "tm_detail.ibatorgenerated_insertSelective", record );
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tm_detail
     * @ibatorgenerated  Wed May 13 14:51:35 CST 2015
     */
    public List selectByExample( TmDetailExample example ) {
        List list = getSqlMapClientTemplate().queryForList(
                "tm_detail.ibatorgenerated_selectByExample", example );
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tm_detail
     * @ibatorgenerated  Wed May 13 14:51:35 CST 2015
     */
    public TmDetail selectByPrimaryKey( Integer id ) {
        TmDetail key = new TmDetail();
        key.setId( id );
        TmDetail record = (TmDetail) getSqlMapClientTemplate().queryForObject(
                "tm_detail.ibatorgenerated_selectByPrimaryKey", key );
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tm_detail
     * @ibatorgenerated  Wed May 13 14:51:35 CST 2015
     */
    public int updateByExampleSelective( TmDetail record, TmDetailExample example ) {
        UpdateByExampleParms parms = new UpdateByExampleParms( record, example );
        int rows = getSqlMapClientTemplate().update(
                "tm_detail.ibatorgenerated_updateByExampleSelective", parms );
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tm_detail
     * @ibatorgenerated  Wed May 13 14:51:35 CST 2015
     */
    public int updateByExample( TmDetail record, TmDetailExample example ) {
        UpdateByExampleParms parms = new UpdateByExampleParms( record, example );
        int rows = getSqlMapClientTemplate().update( "tm_detail.ibatorgenerated_updateByExample",
                parms );
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tm_detail
     * @ibatorgenerated  Wed May 13 14:51:35 CST 2015
     */
    public int updateByPrimaryKeySelective( TmDetail record ) {
        int rows = getSqlMapClientTemplate().update(
                "tm_detail.ibatorgenerated_updateByPrimaryKeySelective", record );
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tm_detail
     * @ibatorgenerated  Wed May 13 14:51:35 CST 2015
     */
    public int updateByPrimaryKey( TmDetail record ) {
        int rows = getSqlMapClientTemplate().update(
                "tm_detail.ibatorgenerated_updateByPrimaryKey", record );
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator. This class corresponds to the database table tm_detail
     * @ibatorgenerated  Wed May 13 14:51:35 CST 2015
     */
    private static class UpdateByExampleParms extends TmDetailExample {
        
        private Object record;
        
        public UpdateByExampleParms( Object record, TmDetailExample example ) {
            super( example );
            this.record = record;
        }
        
        public Object getRecord() {
            return record;
        }
    }
}