package com.tour.dao.impl;

import com.tour.dao.ifc.TmGroupDAO;
import com.tour.model.TmGroup;
import com.tour.model.TmGroupExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class TmGroupDAOImpl extends 
SqlMapClientDaoSupport implements TmGroupDAO {

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tm_group
     * @ibatorgenerated  Wed May 13 14:51:35 CST 2015
     */
    public TmGroupDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tm_group
     * @ibatorgenerated  Wed May 13 14:51:35 CST 2015
     */
    public int countByExample( TmGroupExample example ) {
        Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
                "tm_group.ibatorgenerated_countByExample", example );
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tm_group
     * @ibatorgenerated  Wed May 13 14:51:35 CST 2015
     */
    public int deleteByExample( TmGroupExample example ) {
        int rows = getSqlMapClientTemplate().delete( "tm_group.ibatorgenerated_deleteByExample",
                example );
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tm_group
     * @ibatorgenerated  Wed May 13 14:51:35 CST 2015
     */
    public int deleteByPrimaryKey( Integer id ) {
        TmGroup key = new TmGroup();
        key.setId( id );
        int rows = getSqlMapClientTemplate().delete( "tm_group.ibatorgenerated_deleteByPrimaryKey",
                key );
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tm_group
     * @ibatorgenerated  Wed May 13 14:51:35 CST 2015
     */
    public void insert( TmGroup record ) {
        getSqlMapClientTemplate().insert( "tm_group.ibatorgenerated_insert", record );
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tm_group
     * @ibatorgenerated  Wed May 13 14:51:35 CST 2015
     */
    public void insertSelective( TmGroup record ) {
        getSqlMapClientTemplate().insert( "tm_group.ibatorgenerated_insertSelective", record );
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tm_group
     * @ibatorgenerated  Wed May 13 14:51:35 CST 2015
     */
    public List selectByExample( TmGroupExample example ) {
        List list = getSqlMapClientTemplate().queryForList(
                "tm_group.ibatorgenerated_selectByExample", example );
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tm_group
     * @ibatorgenerated  Wed May 13 14:51:35 CST 2015
     */
    public TmGroup selectByPrimaryKey( Integer id ) {
        TmGroup key = new TmGroup();
        key.setId( id );
        TmGroup record = (TmGroup) getSqlMapClientTemplate().queryForObject(
                "tm_group.ibatorgenerated_selectByPrimaryKey", key );
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tm_group
     * @ibatorgenerated  Wed May 13 14:51:35 CST 2015
     */
    public int updateByExampleSelective( TmGroup record, TmGroupExample example ) {
        UpdateByExampleParms parms = new UpdateByExampleParms( record, example );
        int rows = getSqlMapClientTemplate().update(
                "tm_group.ibatorgenerated_updateByExampleSelective", parms );
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tm_group
     * @ibatorgenerated  Wed May 13 14:51:35 CST 2015
     */
    public int updateByExample( TmGroup record, TmGroupExample example ) {
        UpdateByExampleParms parms = new UpdateByExampleParms( record, example );
        int rows = getSqlMapClientTemplate().update( "tm_group.ibatorgenerated_updateByExample",
                parms );
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tm_group
     * @ibatorgenerated  Wed May 13 14:51:35 CST 2015
     */
    public int updateByPrimaryKeySelective( TmGroup record ) {
        int rows = getSqlMapClientTemplate().update(
                "tm_group.ibatorgenerated_updateByPrimaryKeySelective", record );
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tm_group
     * @ibatorgenerated  Wed May 13 14:51:35 CST 2015
     */
    public int updateByPrimaryKey( TmGroup record ) {
        int rows = getSqlMapClientTemplate().update( "tm_group.ibatorgenerated_updateByPrimaryKey",
                record );
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator. This class corresponds to the database table tm_group
     * @ibatorgenerated  Wed May 13 14:51:35 CST 2015
     */
    private static class UpdateByExampleParms extends TmGroupExample {
        
        private Object record;
        
        public UpdateByExampleParms( Object record, TmGroupExample example ) {
            super( example );
            this.record = record;
        }
        
        public Object getRecord() {
            return record;
        }
    }
}