package com.tour.dao.impl;

import com.tour.dao.ifc.TmOrderDAO;
import com.tour.model.TmOrder;
import com.tour.model.TmOrderExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class TmOrderDAOImpl extends 
SqlMapClientDaoSupport implements TmOrderDAO {

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tm_order
     * @ibatorgenerated  Wed May 13 14:51:35 CST 2015
     */
    public TmOrderDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tm_order
     * @ibatorgenerated  Wed May 13 14:51:35 CST 2015
     */
    public int countByExample( TmOrderExample example ) {
        Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
                "tm_order.ibatorgenerated_countByExample", example );
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tm_order
     * @ibatorgenerated  Wed May 13 14:51:35 CST 2015
     */
    public int deleteByExample( TmOrderExample example ) {
        int rows = getSqlMapClientTemplate().delete( "tm_order.ibatorgenerated_deleteByExample",
                example );
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tm_order
     * @ibatorgenerated  Wed May 13 14:51:35 CST 2015
     */
    public int deleteByPrimaryKey( Integer id ) {
        TmOrder key = new TmOrder();
        key.setId( id );
        int rows = getSqlMapClientTemplate().delete( "tm_order.ibatorgenerated_deleteByPrimaryKey",
                key );
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tm_order
     * @ibatorgenerated  Wed May 13 14:51:35 CST 2015
     */
    public void insert( TmOrder record ) {
        getSqlMapClientTemplate().insert( "tm_order.ibatorgenerated_insert", record );
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tm_order
     * @ibatorgenerated  Wed May 13 14:51:35 CST 2015
     */
    public void insertSelective( TmOrder record ) {
        getSqlMapClientTemplate().insert( "tm_order.ibatorgenerated_insertSelective", record );
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tm_order
     * @ibatorgenerated  Wed May 13 14:51:35 CST 2015
     */
    public List selectByExample( TmOrderExample example ) {
        List list = getSqlMapClientTemplate().queryForList(
                "tm_order.ibatorgenerated_selectByExample", example );
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tm_order
     * @ibatorgenerated  Wed May 13 14:51:35 CST 2015
     */
    public TmOrder selectByPrimaryKey( Integer id ) {
        TmOrder key = new TmOrder();
        key.setId( id );
        TmOrder record = (TmOrder) getSqlMapClientTemplate().queryForObject(
                "tm_order.ibatorgenerated_selectByPrimaryKey", key );
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tm_order
     * @ibatorgenerated  Wed May 13 14:51:35 CST 2015
     */
    public int updateByExampleSelective( TmOrder record, TmOrderExample example ) {
        UpdateByExampleParms parms = new UpdateByExampleParms( record, example );
        int rows = getSqlMapClientTemplate().update(
                "tm_order.ibatorgenerated_updateByExampleSelective", parms );
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tm_order
     * @ibatorgenerated  Wed May 13 14:51:35 CST 2015
     */
    public int updateByExample( TmOrder record, TmOrderExample example ) {
        UpdateByExampleParms parms = new UpdateByExampleParms( record, example );
        int rows = getSqlMapClientTemplate().update( "tm_order.ibatorgenerated_updateByExample",
                parms );
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tm_order
     * @ibatorgenerated  Wed May 13 14:51:35 CST 2015
     */
    public int updateByPrimaryKeySelective( TmOrder record ) {
        int rows = getSqlMapClientTemplate().update(
                "tm_order.ibatorgenerated_updateByPrimaryKeySelective", record );
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tm_order
     * @ibatorgenerated  Wed May 13 14:51:35 CST 2015
     */
    public int updateByPrimaryKey( TmOrder record ) {
        int rows = getSqlMapClientTemplate().update( "tm_order.ibatorgenerated_updateByPrimaryKey",
                record );
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator. This class corresponds to the database table tm_order
     * @ibatorgenerated  Wed May 13 14:51:35 CST 2015
     */
    private static class UpdateByExampleParms extends TmOrderExample {
        
        private Object record;
        
        public UpdateByExampleParms( Object record, TmOrderExample example ) {
            super( example );
            this.record = record;
        }
        
        public Object getRecord() {
            return record;
        }
    }
}