package com.tour.model;

import java.util.Date;

public class SmAutho {

    private String superAuthoName;
    
    public String getSuperAuthoName() {
        return superAuthoName;
    }

    public void setSuperAuthoName( String superAuthoName ) {
        this.superAuthoName = superAuthoName;
    }

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column sm_autho.id
     * @ibatorgenerated  Thu May 14 17:09:30 CST 2015
     */
    private Integer id;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column sm_autho.autho_name
     * @ibatorgenerated  Thu May 14 17:09:30 CST 2015
     */
    private String authoName;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column sm_autho.description
     * @ibatorgenerated  Thu May 14 17:09:30 CST 2015
     */
    private String description;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column sm_autho.url
     * @ibatorgenerated  Thu May 14 17:09:30 CST 2015
     */
    private String url;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column sm_autho.create_time
     * @ibatorgenerated  Thu May 14 17:09:30 CST 2015
     */
    private Date createTime;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column sm_autho.create_user_id
     * @ibatorgenerated  Thu May 14 17:09:30 CST 2015
     */
    private Integer createUserId;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column sm_autho.super_id
     * @ibatorgenerated  Thu May 14 17:09:30 CST 2015
     */
    private Integer superId;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column sm_autho.update_time
     * @ibatorgenerated  Thu May 14 17:09:30 CST 2015
     */
    private Date updateTime;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column sm_autho.update_user_id
     * @ibatorgenerated  Thu May 14 17:09:30 CST 2015
     */
    private Long updateUserId;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column sm_autho.is_del
     * @ibatorgenerated  Thu May 14 17:09:30 CST 2015
     */
    private String isDel;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column sm_autho.autho_icon
     * @ibatorgenerated  Thu May 14 17:09:30 CST 2015
     */
    private String authoIcon;

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column sm_autho.id
     * @return  the value of sm_autho.id
     * @ibatorgenerated  Thu May 14 17:09:30 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column sm_autho.id
     * @param id  the value for sm_autho.id
     * @ibatorgenerated  Thu May 14 17:09:30 CST 2015
     */
    public void setId( Integer id ) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column sm_autho.autho_name
     * @return  the value of sm_autho.autho_name
     * @ibatorgenerated  Thu May 14 17:09:30 CST 2015
     */
    public String getAuthoName() {
        return authoName;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column sm_autho.autho_name
     * @param authoName  the value for sm_autho.autho_name
     * @ibatorgenerated  Thu May 14 17:09:30 CST 2015
     */
    public void setAuthoName( String authoName ) {
        this.authoName = authoName;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column sm_autho.description
     * @return  the value of sm_autho.description
     * @ibatorgenerated  Thu May 14 17:09:30 CST 2015
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column sm_autho.description
     * @param description  the value for sm_autho.description
     * @ibatorgenerated  Thu May 14 17:09:30 CST 2015
     */
    public void setDescription( String description ) {
        this.description = description;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column sm_autho.url
     * @return  the value of sm_autho.url
     * @ibatorgenerated  Thu May 14 17:09:30 CST 2015
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column sm_autho.url
     * @param url  the value for sm_autho.url
     * @ibatorgenerated  Thu May 14 17:09:30 CST 2015
     */
    public void setUrl( String url ) {
        this.url = url;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column sm_autho.create_time
     * @return  the value of sm_autho.create_time
     * @ibatorgenerated  Thu May 14 17:09:30 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column sm_autho.create_time
     * @param createTime  the value for sm_autho.create_time
     * @ibatorgenerated  Thu May 14 17:09:30 CST 2015
     */
    public void setCreateTime( Date createTime ) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column sm_autho.create_user_id
     * @return  the value of sm_autho.create_user_id
     * @ibatorgenerated  Thu May 14 17:09:30 CST 2015
     */
    public Integer getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column sm_autho.create_user_id
     * @param createUserId  the value for sm_autho.create_user_id
     * @ibatorgenerated  Thu May 14 17:09:30 CST 2015
     */
    public void setCreateUserId( Integer createUserId ) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column sm_autho.super_id
     * @return  the value of sm_autho.super_id
     * @ibatorgenerated  Thu May 14 17:09:30 CST 2015
     */
    public Integer getSuperId() {
        return superId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column sm_autho.super_id
     * @param superId  the value for sm_autho.super_id
     * @ibatorgenerated  Thu May 14 17:09:30 CST 2015
     */
    public void setSuperId( Integer superId ) {
        this.superId = superId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column sm_autho.update_time
     * @return  the value of sm_autho.update_time
     * @ibatorgenerated  Thu May 14 17:09:30 CST 2015
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column sm_autho.update_time
     * @param updateTime  the value for sm_autho.update_time
     * @ibatorgenerated  Thu May 14 17:09:30 CST 2015
     */
    public void setUpdateTime( Date updateTime ) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column sm_autho.update_user_id
     * @return  the value of sm_autho.update_user_id
     * @ibatorgenerated  Thu May 14 17:09:30 CST 2015
     */
    public Long getUpdateUserId() {
        return updateUserId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column sm_autho.update_user_id
     * @param updateUserId  the value for sm_autho.update_user_id
     * @ibatorgenerated  Thu May 14 17:09:30 CST 2015
     */
    public void setUpdateUserId( Long updateUserId ) {
        this.updateUserId = updateUserId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column sm_autho.is_del
     * @return  the value of sm_autho.is_del
     * @ibatorgenerated  Thu May 14 17:09:30 CST 2015
     */
    public String getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column sm_autho.is_del
     * @param isDel  the value for sm_autho.is_del
     * @ibatorgenerated  Thu May 14 17:09:30 CST 2015
     */
    public void setIsDel( String isDel ) {
        this.isDel = isDel;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column sm_autho.autho_icon
     * @return  the value of sm_autho.autho_icon
     * @ibatorgenerated  Thu May 14 17:09:30 CST 2015
     */
    public String getAuthoIcon() {
        return authoIcon;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column sm_autho.autho_icon
     * @param authoIcon  the value for sm_autho.autho_icon
     * @ibatorgenerated  Thu May 14 17:09:30 CST 2015
     */
    public void setAuthoIcon( String authoIcon ) {
        this.authoIcon = authoIcon;
    }
}