package com.tour.model;

import java.util.Date;

public class SmUserRole {

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column sm_user_role.id
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    private Integer id;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column sm_user_role.user_id
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    private Integer userId;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column sm_user_role.role_id
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    private Integer roleId;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column sm_user_role.is_del
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    private String isDel;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column sm_user_role.create_time
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    private Date createTime;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column sm_user_role.create_user_id
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    private Integer createUserId;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column sm_user_role.update_time
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    private Date updateTime;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column sm_user_role.update_user_id
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    private Integer updateUserId;

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column sm_user_role.id
     * @return  the value of sm_user_role.id
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column sm_user_role.id
     * @param id  the value for sm_user_role.id
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public void setId( Integer id ) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column sm_user_role.user_id
     * @return  the value of sm_user_role.user_id
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column sm_user_role.user_id
     * @param userId  the value for sm_user_role.user_id
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public void setUserId( Integer userId ) {
        this.userId = userId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column sm_user_role.role_id
     * @return  the value of sm_user_role.role_id
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column sm_user_role.role_id
     * @param roleId  the value for sm_user_role.role_id
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public void setRoleId( Integer roleId ) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column sm_user_role.is_del
     * @return  the value of sm_user_role.is_del
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public String getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column sm_user_role.is_del
     * @param isDel  the value for sm_user_role.is_del
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public void setIsDel( String isDel ) {
        this.isDel = isDel;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column sm_user_role.create_time
     * @return  the value of sm_user_role.create_time
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column sm_user_role.create_time
     * @param createTime  the value for sm_user_role.create_time
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public void setCreateTime( Date createTime ) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column sm_user_role.create_user_id
     * @return  the value of sm_user_role.create_user_id
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public Integer getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column sm_user_role.create_user_id
     * @param createUserId  the value for sm_user_role.create_user_id
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public void setCreateUserId( Integer createUserId ) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column sm_user_role.update_time
     * @return  the value of sm_user_role.update_time
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column sm_user_role.update_time
     * @param updateTime  the value for sm_user_role.update_time
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public void setUpdateTime( Date updateTime ) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column sm_user_role.update_user_id
     * @return  the value of sm_user_role.update_user_id
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public Integer getUpdateUserId() {
        return updateUserId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column sm_user_role.update_user_id
     * @param updateUserId  the value for sm_user_role.update_user_id
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public void setUpdateUserId( Integer updateUserId ) {
        this.updateUserId = updateUserId;
    }
}