package com.tour.model;

import java.util.Date;

public class SmUser {

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column sm_user.id
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    private Integer id;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column sm_user.login_name
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    private String loginName;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column sm_user.real_name
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    private String realName;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column sm_user.password
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    private String password;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column sm_user.tel
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    private String tel;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column sm_user.sex
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    private Integer sex;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column sm_user.is_admin
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    private Integer isAdmin;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column sm_user.age
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    private Integer age;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column sm_user.create_time
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    private Date createTime;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column sm_user.create_user_id
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    private Integer createUserId;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column sm_user.update_time
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    private Date updateTime;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column sm_user.update_user_id
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    private Integer updateUserId;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column sm_user.status
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    private Integer status;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column sm_user.is_del
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    private String isDel;

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column sm_user.id
     * @return  the value of sm_user.id
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column sm_user.id
     * @param id  the value for sm_user.id
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public void setId( Integer id ) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column sm_user.login_name
     * @return  the value of sm_user.login_name
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public String getLoginName() {
        return loginName;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column sm_user.login_name
     * @param loginName  the value for sm_user.login_name
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public void setLoginName( String loginName ) {
        this.loginName = loginName;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column sm_user.real_name
     * @return  the value of sm_user.real_name
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public String getRealName() {
        return realName;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column sm_user.real_name
     * @param realName  the value for sm_user.real_name
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public void setRealName( String realName ) {
        this.realName = realName;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column sm_user.password
     * @return  the value of sm_user.password
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column sm_user.password
     * @param password  the value for sm_user.password
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public void setPassword( String password ) {
        this.password = password;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column sm_user.tel
     * @return  the value of sm_user.tel
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column sm_user.tel
     * @param tel  the value for sm_user.tel
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public void setTel( String tel ) {
        this.tel = tel;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column sm_user.sex
     * @return  the value of sm_user.sex
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public Integer getSex() {
        return sex;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column sm_user.sex
     * @param sex  the value for sm_user.sex
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public void setSex( Integer sex ) {
        this.sex = sex;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column sm_user.is_admin
     * @return  the value of sm_user.is_admin
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public Integer getIsAdmin() {
        return isAdmin;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column sm_user.is_admin
     * @param isAdmin  the value for sm_user.is_admin
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public void setIsAdmin( Integer isAdmin ) {
        this.isAdmin = isAdmin;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column sm_user.age
     * @return  the value of sm_user.age
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column sm_user.age
     * @param age  the value for sm_user.age
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public void setAge( Integer age ) {
        this.age = age;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column sm_user.create_time
     * @return  the value of sm_user.create_time
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column sm_user.create_time
     * @param createTime  the value for sm_user.create_time
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public void setCreateTime( Date createTime ) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column sm_user.create_user_id
     * @return  the value of sm_user.create_user_id
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public Integer getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column sm_user.create_user_id
     * @param createUserId  the value for sm_user.create_user_id
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public void setCreateUserId( Integer createUserId ) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column sm_user.update_time
     * @return  the value of sm_user.update_time
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column sm_user.update_time
     * @param updateTime  the value for sm_user.update_time
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public void setUpdateTime( Date updateTime ) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column sm_user.update_user_id
     * @return  the value of sm_user.update_user_id
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public Integer getUpdateUserId() {
        return updateUserId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column sm_user.update_user_id
     * @param updateUserId  the value for sm_user.update_user_id
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public void setUpdateUserId( Integer updateUserId ) {
        this.updateUserId = updateUserId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column sm_user.status
     * @return  the value of sm_user.status
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column sm_user.status
     * @param status  the value for sm_user.status
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public void setStatus( Integer status ) {
        this.status = status;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column sm_user.is_del
     * @return  the value of sm_user.is_del
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public String getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column sm_user.is_del
     * @param isDel  the value for sm_user.is_del
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public void setIsDel( String isDel ) {
        this.isDel = isDel;
    }
}