package com.tour.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Map;

public class TmCustomerExample {

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database table tm_customer
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    protected String orderByClause;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database table tm_customer
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    protected List oredCriteria;

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tm_customer
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public TmCustomerExample() {
        oredCriteria = new ArrayList();
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tm_customer
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    protected TmCustomerExample( TmCustomerExample example ) {
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tm_customer
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public void setOrderByClause( String orderByClause ) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tm_customer
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tm_customer
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public List getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tm_customer
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public void or( Criteria criteria ) {
        oredCriteria.add( criteria );
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tm_customer
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add( criteria );
        }
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tm_customer
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tm_customer
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public void clear() {
        oredCriteria.clear();
    }

    /**
     * This class was generated by Apache iBATIS ibator. This class corresponds to the database table tm_customer
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public static class Criteria {
        
        protected List criteriaWithoutValue;
        protected List criteriaWithSingleValue;
        protected List criteriaWithListValue;
        protected List criteriaWithBetweenValue;
        
        protected Criteria() {
            super();
            criteriaWithoutValue = new ArrayList();
            criteriaWithSingleValue = new ArrayList();
            criteriaWithListValue = new ArrayList();
            criteriaWithBetweenValue = new ArrayList();
        }
        
        public boolean isValid() {
            return criteriaWithoutValue.size() > 0 || criteriaWithSingleValue.size() > 0
                    || criteriaWithListValue.size() > 0 || criteriaWithBetweenValue.size() > 0;
        }
        
        public List getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }
        
        public List getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }
        
        public List getCriteriaWithListValue() {
            return criteriaWithListValue;
        }
        
        public List getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }
        
        protected void addCriterion( String condition ) {
            if (condition == null) {
                throw new RuntimeException( "Value for condition cannot be null" );
            }
            criteriaWithoutValue.add( condition );
        }
        
        protected void addCriterion( String condition, Object value, String property ) {
            if (value == null) {
                throw new RuntimeException( "Value for " + property + " cannot be null" );
            }
            Map map = new HashMap();
            map.put( "condition", condition );
            map.put( "value", value );
            criteriaWithSingleValue.add( map );
        }
        
        protected void addCriterion( String condition, List values, String property ) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException( "Value list for " + property
                        + " cannot be null or empty" );
            }
            Map map = new HashMap();
            map.put( "condition", condition );
            map.put( "values", values );
            criteriaWithListValue.add( map );
        }
        
        protected void addCriterion( String condition, Object value1, Object value2, String property ) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException( "Between values for " + property + " cannot be null" );
            }
            List list = new ArrayList();
            list.add( value1 );
            list.add( value2 );
            Map map = new HashMap();
            map.put( "condition", condition );
            map.put( "values", list );
            criteriaWithBetweenValue.add( map );
        }
        
        protected void addCriterionForJDBCDate( String condition, Date value, String property ) {
            addCriterion( condition, new java.sql.Date( value.getTime() ), property );
        }
        
        protected void addCriterionForJDBCDate( String condition, List values, String property ) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException( "Value list for " + property
                        + " cannot be null or empty" );
            }
            List dateList = new ArrayList();
            Iterator iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add( new java.sql.Date( ((Date) iter.next()).getTime() ) );
            }
            addCriterion( condition, dateList, property );
        }
        
        protected void addCriterionForJDBCDate( String condition, Date value1, Date value2,
                String property ) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException( "Between values for " + property + " cannot be null" );
            }
            addCriterion( condition, new java.sql.Date( value1.getTime() ), new java.sql.Date(
                    value2.getTime() ), property );
        }
        
        public Criteria andIdIsNull() {
            addCriterion( "id is null" );
            return this;
        }
        
        public Criteria andIdIsNotNull() {
            addCriterion( "id is not null" );
            return this;
        }
        
        public Criteria andIdEqualTo( Integer value ) {
            addCriterion( "id =", value, "id" );
            return this;
        }
        
        public Criteria andIdNotEqualTo( Integer value ) {
            addCriterion( "id <>", value, "id" );
            return this;
        }
        
        public Criteria andIdGreaterThan( Integer value ) {
            addCriterion( "id >", value, "id" );
            return this;
        }
        
        public Criteria andIdGreaterThanOrEqualTo( Integer value ) {
            addCriterion( "id >=", value, "id" );
            return this;
        }
        
        public Criteria andIdLessThan( Integer value ) {
            addCriterion( "id <", value, "id" );
            return this;
        }
        
        public Criteria andIdLessThanOrEqualTo( Integer value ) {
            addCriterion( "id <=", value, "id" );
            return this;
        }
        
        public Criteria andIdIn( List values ) {
            addCriterion( "id in", values, "id" );
            return this;
        }
        
        public Criteria andIdNotIn( List values ) {
            addCriterion( "id not in", values, "id" );
            return this;
        }
        
        public Criteria andIdBetween( Integer value1, Integer value2 ) {
            addCriterion( "id between", value1, value2, "id" );
            return this;
        }
        
        public Criteria andIdNotBetween( Integer value1, Integer value2 ) {
            addCriterion( "id not between", value1, value2, "id" );
            return this;
        }
        
        public Criteria andUserIdIsNull() {
            addCriterion( "user_id is null" );
            return this;
        }
        
        public Criteria andUserIdIsNotNull() {
            addCriterion( "user_id is not null" );
            return this;
        }
        
        public Criteria andUserIdEqualTo( Integer value ) {
            addCriterion( "user_id =", value, "userId" );
            return this;
        }
        
        public Criteria andUserIdNotEqualTo( Integer value ) {
            addCriterion( "user_id <>", value, "userId" );
            return this;
        }
        
        public Criteria andUserIdGreaterThan( Integer value ) {
            addCriterion( "user_id >", value, "userId" );
            return this;
        }
        
        public Criteria andUserIdGreaterThanOrEqualTo( Integer value ) {
            addCriterion( "user_id >=", value, "userId" );
            return this;
        }
        
        public Criteria andUserIdLessThan( Integer value ) {
            addCriterion( "user_id <", value, "userId" );
            return this;
        }
        
        public Criteria andUserIdLessThanOrEqualTo( Integer value ) {
            addCriterion( "user_id <=", value, "userId" );
            return this;
        }
        
        public Criteria andUserIdIn( List values ) {
            addCriterion( "user_id in", values, "userId" );
            return this;
        }
        
        public Criteria andUserIdNotIn( List values ) {
            addCriterion( "user_id not in", values, "userId" );
            return this;
        }
        
        public Criteria andUserIdBetween( Integer value1, Integer value2 ) {
            addCriterion( "user_id between", value1, value2, "userId" );
            return this;
        }
        
        public Criteria andUserIdNotBetween( Integer value1, Integer value2 ) {
            addCriterion( "user_id not between", value1, value2, "userId" );
            return this;
        }
        
        public Criteria andIdentityNumIsNull() {
            addCriterion( "identity_num is null" );
            return this;
        }
        
        public Criteria andIdentityNumIsNotNull() {
            addCriterion( "identity_num is not null" );
            return this;
        }
        
        public Criteria andIdentityNumEqualTo( String value ) {
            addCriterion( "identity_num =", value, "identityNum" );
            return this;
        }
        
        public Criteria andIdentityNumNotEqualTo( String value ) {
            addCriterion( "identity_num <>", value, "identityNum" );
            return this;
        }
        
        public Criteria andIdentityNumGreaterThan( String value ) {
            addCriterion( "identity_num >", value, "identityNum" );
            return this;
        }
        
        public Criteria andIdentityNumGreaterThanOrEqualTo( String value ) {
            addCriterion( "identity_num >=", value, "identityNum" );
            return this;
        }
        
        public Criteria andIdentityNumLessThan( String value ) {
            addCriterion( "identity_num <", value, "identityNum" );
            return this;
        }
        
        public Criteria andIdentityNumLessThanOrEqualTo( String value ) {
            addCriterion( "identity_num <=", value, "identityNum" );
            return this;
        }
        
        public Criteria andIdentityNumLike( String value ) {
            addCriterion( "identity_num like", value, "identityNum" );
            return this;
        }
        
        public Criteria andIdentityNumNotLike( String value ) {
            addCriterion( "identity_num not like", value, "identityNum" );
            return this;
        }
        
        public Criteria andIdentityNumIn( List values ) {
            addCriterion( "identity_num in", values, "identityNum" );
            return this;
        }
        
        public Criteria andIdentityNumNotIn( List values ) {
            addCriterion( "identity_num not in", values, "identityNum" );
            return this;
        }
        
        public Criteria andIdentityNumBetween( String value1, String value2 ) {
            addCriterion( "identity_num between", value1, value2, "identityNum" );
            return this;
        }
        
        public Criteria andIdentityNumNotBetween( String value1, String value2 ) {
            addCriterion( "identity_num not between", value1, value2, "identityNum" );
            return this;
        }
        
        public Criteria andTelIsNull() {
            addCriterion( "tel is null" );
            return this;
        }
        
        public Criteria andTelIsNotNull() {
            addCriterion( "tel is not null" );
            return this;
        }
        
        public Criteria andTelEqualTo( String value ) {
            addCriterion( "tel =", value, "tel" );
            return this;
        }
        
        public Criteria andTelNotEqualTo( String value ) {
            addCriterion( "tel <>", value, "tel" );
            return this;
        }
        
        public Criteria andTelGreaterThan( String value ) {
            addCriterion( "tel >", value, "tel" );
            return this;
        }
        
        public Criteria andTelGreaterThanOrEqualTo( String value ) {
            addCriterion( "tel >=", value, "tel" );
            return this;
        }
        
        public Criteria andTelLessThan( String value ) {
            addCriterion( "tel <", value, "tel" );
            return this;
        }
        
        public Criteria andTelLessThanOrEqualTo( String value ) {
            addCriterion( "tel <=", value, "tel" );
            return this;
        }
        
        public Criteria andTelLike( String value ) {
            addCriterion( "tel like", value, "tel" );
            return this;
        }
        
        public Criteria andTelNotLike( String value ) {
            addCriterion( "tel not like", value, "tel" );
            return this;
        }
        
        public Criteria andTelIn( List values ) {
            addCriterion( "tel in", values, "tel" );
            return this;
        }
        
        public Criteria andTelNotIn( List values ) {
            addCriterion( "tel not in", values, "tel" );
            return this;
        }
        
        public Criteria andTelBetween( String value1, String value2 ) {
            addCriterion( "tel between", value1, value2, "tel" );
            return this;
        }
        
        public Criteria andTelNotBetween( String value1, String value2 ) {
            addCriterion( "tel not between", value1, value2, "tel" );
            return this;
        }
        
        public Criteria andTypeIsNull() {
            addCriterion( "type is null" );
            return this;
        }
        
        public Criteria andTypeIsNotNull() {
            addCriterion( "type is not null" );
            return this;
        }
        
        public Criteria andTypeEqualTo( Integer value ) {
            addCriterion( "type =", value, "type" );
            return this;
        }
        
        public Criteria andTypeNotEqualTo( Integer value ) {
            addCriterion( "type <>", value, "type" );
            return this;
        }
        
        public Criteria andTypeGreaterThan( Integer value ) {
            addCriterion( "type >", value, "type" );
            return this;
        }
        
        public Criteria andTypeGreaterThanOrEqualTo( Integer value ) {
            addCriterion( "type >=", value, "type" );
            return this;
        }
        
        public Criteria andTypeLessThan( Integer value ) {
            addCriterion( "type <", value, "type" );
            return this;
        }
        
        public Criteria andTypeLessThanOrEqualTo( Integer value ) {
            addCriterion( "type <=", value, "type" );
            return this;
        }
        
        public Criteria andTypeIn( List values ) {
            addCriterion( "type in", values, "type" );
            return this;
        }
        
        public Criteria andTypeNotIn( List values ) {
            addCriterion( "type not in", values, "type" );
            return this;
        }
        
        public Criteria andTypeBetween( Integer value1, Integer value2 ) {
            addCriterion( "type between", value1, value2, "type" );
            return this;
        }
        
        public Criteria andTypeNotBetween( Integer value1, Integer value2 ) {
            addCriterion( "type not between", value1, value2, "type" );
            return this;
        }
        
        public Criteria andClassifyIsNull() {
            addCriterion( "classify is null" );
            return this;
        }
        
        public Criteria andClassifyIsNotNull() {
            addCriterion( "classify is not null" );
            return this;
        }
        
        public Criteria andClassifyEqualTo( Integer value ) {
            addCriterion( "classify =", value, "classify" );
            return this;
        }
        
        public Criteria andClassifyNotEqualTo( Integer value ) {
            addCriterion( "classify <>", value, "classify" );
            return this;
        }
        
        public Criteria andClassifyGreaterThan( Integer value ) {
            addCriterion( "classify >", value, "classify" );
            return this;
        }
        
        public Criteria andClassifyGreaterThanOrEqualTo( Integer value ) {
            addCriterion( "classify >=", value, "classify" );
            return this;
        }
        
        public Criteria andClassifyLessThan( Integer value ) {
            addCriterion( "classify <", value, "classify" );
            return this;
        }
        
        public Criteria andClassifyLessThanOrEqualTo( Integer value ) {
            addCriterion( "classify <=", value, "classify" );
            return this;
        }
        
        public Criteria andClassifyIn( List values ) {
            addCriterion( "classify in", values, "classify" );
            return this;
        }
        
        public Criteria andClassifyNotIn( List values ) {
            addCriterion( "classify not in", values, "classify" );
            return this;
        }
        
        public Criteria andClassifyBetween( Integer value1, Integer value2 ) {
            addCriterion( "classify between", value1, value2, "classify" );
            return this;
        }
        
        public Criteria andClassifyNotBetween( Integer value1, Integer value2 ) {
            addCriterion( "classify not between", value1, value2, "classify" );
            return this;
        }
        
        public Criteria andIsKeyIsNull() {
            addCriterion( "is_key is null" );
            return this;
        }
        
        public Criteria andIsKeyIsNotNull() {
            addCriterion( "is_key is not null" );
            return this;
        }
        
        public Criteria andIsKeyEqualTo( Integer value ) {
            addCriterion( "is_key =", value, "isKey" );
            return this;
        }
        
        public Criteria andIsKeyNotEqualTo( Integer value ) {
            addCriterion( "is_key <>", value, "isKey" );
            return this;
        }
        
        public Criteria andIsKeyGreaterThan( Integer value ) {
            addCriterion( "is_key >", value, "isKey" );
            return this;
        }
        
        public Criteria andIsKeyGreaterThanOrEqualTo( Integer value ) {
            addCriterion( "is_key >=", value, "isKey" );
            return this;
        }
        
        public Criteria andIsKeyLessThan( Integer value ) {
            addCriterion( "is_key <", value, "isKey" );
            return this;
        }
        
        public Criteria andIsKeyLessThanOrEqualTo( Integer value ) {
            addCriterion( "is_key <=", value, "isKey" );
            return this;
        }
        
        public Criteria andIsKeyIn( List values ) {
            addCriterion( "is_key in", values, "isKey" );
            return this;
        }
        
        public Criteria andIsKeyNotIn( List values ) {
            addCriterion( "is_key not in", values, "isKey" );
            return this;
        }
        
        public Criteria andIsKeyBetween( Integer value1, Integer value2 ) {
            addCriterion( "is_key between", value1, value2, "isKey" );
            return this;
        }
        
        public Criteria andIsKeyNotBetween( Integer value1, Integer value2 ) {
            addCriterion( "is_key not between", value1, value2, "isKey" );
            return this;
        }
        
        public Criteria andSuperIdIsNull() {
            addCriterion( "super_id is null" );
            return this;
        }
        
        public Criteria andSuperIdIsNotNull() {
            addCriterion( "super_id is not null" );
            return this;
        }
        
        public Criteria andSuperIdEqualTo( Integer value ) {
            addCriterion( "super_id =", value, "superId" );
            return this;
        }
        
        public Criteria andSuperIdNotEqualTo( Integer value ) {
            addCriterion( "super_id <>", value, "superId" );
            return this;
        }
        
        public Criteria andSuperIdGreaterThan( Integer value ) {
            addCriterion( "super_id >", value, "superId" );
            return this;
        }
        
        public Criteria andSuperIdGreaterThanOrEqualTo( Integer value ) {
            addCriterion( "super_id >=", value, "superId" );
            return this;
        }
        
        public Criteria andSuperIdLessThan( Integer value ) {
            addCriterion( "super_id <", value, "superId" );
            return this;
        }
        
        public Criteria andSuperIdLessThanOrEqualTo( Integer value ) {
            addCriterion( "super_id <=", value, "superId" );
            return this;
        }
        
        public Criteria andSuperIdIn( List values ) {
            addCriterion( "super_id in", values, "superId" );
            return this;
        }
        
        public Criteria andSuperIdNotIn( List values ) {
            addCriterion( "super_id not in", values, "superId" );
            return this;
        }
        
        public Criteria andSuperIdBetween( Integer value1, Integer value2 ) {
            addCriterion( "super_id between", value1, value2, "superId" );
            return this;
        }
        
        public Criteria andSuperIdNotBetween( Integer value1, Integer value2 ) {
            addCriterion( "super_id not between", value1, value2, "superId" );
            return this;
        }
        
        public Criteria andSexIsNull() {
            addCriterion( "sex is null" );
            return this;
        }
        
        public Criteria andSexIsNotNull() {
            addCriterion( "sex is not null" );
            return this;
        }
        
        public Criteria andSexEqualTo( Integer value ) {
            addCriterion( "sex =", value, "sex" );
            return this;
        }
        
        public Criteria andSexNotEqualTo( Integer value ) {
            addCriterion( "sex <>", value, "sex" );
            return this;
        }
        
        public Criteria andSexGreaterThan( Integer value ) {
            addCriterion( "sex >", value, "sex" );
            return this;
        }
        
        public Criteria andSexGreaterThanOrEqualTo( Integer value ) {
            addCriterion( "sex >=", value, "sex" );
            return this;
        }
        
        public Criteria andSexLessThan( Integer value ) {
            addCriterion( "sex <", value, "sex" );
            return this;
        }
        
        public Criteria andSexLessThanOrEqualTo( Integer value ) {
            addCriterion( "sex <=", value, "sex" );
            return this;
        }
        
        public Criteria andSexIn( List values ) {
            addCriterion( "sex in", values, "sex" );
            return this;
        }
        
        public Criteria andSexNotIn( List values ) {
            addCriterion( "sex not in", values, "sex" );
            return this;
        }
        
        public Criteria andSexBetween( Integer value1, Integer value2 ) {
            addCriterion( "sex between", value1, value2, "sex" );
            return this;
        }
        
        public Criteria andSexNotBetween( Integer value1, Integer value2 ) {
            addCriterion( "sex not between", value1, value2, "sex" );
            return this;
        }
        
        public Criteria andAgeIsNull() {
            addCriterion( "age is null" );
            return this;
        }
        
        public Criteria andAgeIsNotNull() {
            addCriterion( "age is not null" );
            return this;
        }
        
        public Criteria andAgeEqualTo( Integer value ) {
            addCriterion( "age =", value, "age" );
            return this;
        }
        
        public Criteria andAgeNotEqualTo( Integer value ) {
            addCriterion( "age <>", value, "age" );
            return this;
        }
        
        public Criteria andAgeGreaterThan( Integer value ) {
            addCriterion( "age >", value, "age" );
            return this;
        }
        
        public Criteria andAgeGreaterThanOrEqualTo( Integer value ) {
            addCriterion( "age >=", value, "age" );
            return this;
        }
        
        public Criteria andAgeLessThan( Integer value ) {
            addCriterion( "age <", value, "age" );
            return this;
        }
        
        public Criteria andAgeLessThanOrEqualTo( Integer value ) {
            addCriterion( "age <=", value, "age" );
            return this;
        }
        
        public Criteria andAgeIn( List values ) {
            addCriterion( "age in", values, "age" );
            return this;
        }
        
        public Criteria andAgeNotIn( List values ) {
            addCriterion( "age not in", values, "age" );
            return this;
        }
        
        public Criteria andAgeBetween( Integer value1, Integer value2 ) {
            addCriterion( "age between", value1, value2, "age" );
            return this;
        }
        
        public Criteria andAgeNotBetween( Integer value1, Integer value2 ) {
            addCriterion( "age not between", value1, value2, "age" );
            return this;
        }
        
        public Criteria andIsDelIsNull() {
            addCriterion( "is_del is null" );
            return this;
        }
        
        public Criteria andIsDelIsNotNull() {
            addCriterion( "is_del is not null" );
            return this;
        }
        
        public Criteria andIsDelEqualTo( String value ) {
            addCriterion( "is_del =", value, "isDel" );
            return this;
        }
        
        public Criteria andIsDelNotEqualTo( String value ) {
            addCriterion( "is_del <>", value, "isDel" );
            return this;
        }
        
        public Criteria andIsDelGreaterThan( String value ) {
            addCriterion( "is_del >", value, "isDel" );
            return this;
        }
        
        public Criteria andIsDelGreaterThanOrEqualTo( String value ) {
            addCriterion( "is_del >=", value, "isDel" );
            return this;
        }
        
        public Criteria andIsDelLessThan( String value ) {
            addCriterion( "is_del <", value, "isDel" );
            return this;
        }
        
        public Criteria andIsDelLessThanOrEqualTo( String value ) {
            addCriterion( "is_del <=", value, "isDel" );
            return this;
        }
        
        public Criteria andIsDelLike( String value ) {
            addCriterion( "is_del like", value, "isDel" );
            return this;
        }
        
        public Criteria andIsDelNotLike( String value ) {
            addCriterion( "is_del not like", value, "isDel" );
            return this;
        }
        
        public Criteria andIsDelIn( List values ) {
            addCriterion( "is_del in", values, "isDel" );
            return this;
        }
        
        public Criteria andIsDelNotIn( List values ) {
            addCriterion( "is_del not in", values, "isDel" );
            return this;
        }
        
        public Criteria andIsDelBetween( String value1, String value2 ) {
            addCriterion( "is_del between", value1, value2, "isDel" );
            return this;
        }
        
        public Criteria andIsDelNotBetween( String value1, String value2 ) {
            addCriterion( "is_del not between", value1, value2, "isDel" );
            return this;
        }
        
        public Criteria andCreateTimeIsNull() {
            addCriterion( "create_time is null" );
            return this;
        }
        
        public Criteria andCreateTimeIsNotNull() {
            addCriterion( "create_time is not null" );
            return this;
        }
        
        public Criteria andCreateTimeEqualTo( Date value ) {
            addCriterionForJDBCDate( "create_time =", value, "createTime" );
            return this;
        }
        
        public Criteria andCreateTimeNotEqualTo( Date value ) {
            addCriterionForJDBCDate( "create_time <>", value, "createTime" );
            return this;
        }
        
        public Criteria andCreateTimeGreaterThan( Date value ) {
            addCriterionForJDBCDate( "create_time >", value, "createTime" );
            return this;
        }
        
        public Criteria andCreateTimeGreaterThanOrEqualTo( Date value ) {
            addCriterionForJDBCDate( "create_time >=", value, "createTime" );
            return this;
        }
        
        public Criteria andCreateTimeLessThan( Date value ) {
            addCriterionForJDBCDate( "create_time <", value, "createTime" );
            return this;
        }
        
        public Criteria andCreateTimeLessThanOrEqualTo( Date value ) {
            addCriterionForJDBCDate( "create_time <=", value, "createTime" );
            return this;
        }
        
        public Criteria andCreateTimeIn( List values ) {
            addCriterionForJDBCDate( "create_time in", values, "createTime" );
            return this;
        }
        
        public Criteria andCreateTimeNotIn( List values ) {
            addCriterionForJDBCDate( "create_time not in", values, "createTime" );
            return this;
        }
        
        public Criteria andCreateTimeBetween( Date value1, Date value2 ) {
            addCriterionForJDBCDate( "create_time between", value1, value2, "createTime" );
            return this;
        }
        
        public Criteria andCreateTimeNotBetween( Date value1, Date value2 ) {
            addCriterionForJDBCDate( "create_time not between", value1, value2, "createTime" );
            return this;
        }
        
        public Criteria andCreateUserIdIsNull() {
            addCriterion( "create_user_id is null" );
            return this;
        }
        
        public Criteria andCreateUserIdIsNotNull() {
            addCriterion( "create_user_id is not null" );
            return this;
        }
        
        public Criteria andCreateUserIdEqualTo( Integer value ) {
            addCriterion( "create_user_id =", value, "createUserId" );
            return this;
        }
        
        public Criteria andCreateUserIdNotEqualTo( Integer value ) {
            addCriterion( "create_user_id <>", value, "createUserId" );
            return this;
        }
        
        public Criteria andCreateUserIdGreaterThan( Integer value ) {
            addCriterion( "create_user_id >", value, "createUserId" );
            return this;
        }
        
        public Criteria andCreateUserIdGreaterThanOrEqualTo( Integer value ) {
            addCriterion( "create_user_id >=", value, "createUserId" );
            return this;
        }
        
        public Criteria andCreateUserIdLessThan( Integer value ) {
            addCriterion( "create_user_id <", value, "createUserId" );
            return this;
        }
        
        public Criteria andCreateUserIdLessThanOrEqualTo( Integer value ) {
            addCriterion( "create_user_id <=", value, "createUserId" );
            return this;
        }
        
        public Criteria andCreateUserIdIn( List values ) {
            addCriterion( "create_user_id in", values, "createUserId" );
            return this;
        }
        
        public Criteria andCreateUserIdNotIn( List values ) {
            addCriterion( "create_user_id not in", values, "createUserId" );
            return this;
        }
        
        public Criteria andCreateUserIdBetween( Integer value1, Integer value2 ) {
            addCriterion( "create_user_id between", value1, value2, "createUserId" );
            return this;
        }
        
        public Criteria andCreateUserIdNotBetween( Integer value1, Integer value2 ) {
            addCriterion( "create_user_id not between", value1, value2, "createUserId" );
            return this;
        }
        
        public Criteria andUpdateTimeIsNull() {
            addCriterion( "update_time is null" );
            return this;
        }
        
        public Criteria andUpdateTimeIsNotNull() {
            addCriterion( "update_time is not null" );
            return this;
        }
        
        public Criteria andUpdateTimeEqualTo( Date value ) {
            addCriterionForJDBCDate( "update_time =", value, "updateTime" );
            return this;
        }
        
        public Criteria andUpdateTimeNotEqualTo( Date value ) {
            addCriterionForJDBCDate( "update_time <>", value, "updateTime" );
            return this;
        }
        
        public Criteria andUpdateTimeGreaterThan( Date value ) {
            addCriterionForJDBCDate( "update_time >", value, "updateTime" );
            return this;
        }
        
        public Criteria andUpdateTimeGreaterThanOrEqualTo( Date value ) {
            addCriterionForJDBCDate( "update_time >=", value, "updateTime" );
            return this;
        }
        
        public Criteria andUpdateTimeLessThan( Date value ) {
            addCriterionForJDBCDate( "update_time <", value, "updateTime" );
            return this;
        }
        
        public Criteria andUpdateTimeLessThanOrEqualTo( Date value ) {
            addCriterionForJDBCDate( "update_time <=", value, "updateTime" );
            return this;
        }
        
        public Criteria andUpdateTimeIn( List values ) {
            addCriterionForJDBCDate( "update_time in", values, "updateTime" );
            return this;
        }
        
        public Criteria andUpdateTimeNotIn( List values ) {
            addCriterionForJDBCDate( "update_time not in", values, "updateTime" );
            return this;
        }
        
        public Criteria andUpdateTimeBetween( Date value1, Date value2 ) {
            addCriterionForJDBCDate( "update_time between", value1, value2, "updateTime" );
            return this;
        }
        
        public Criteria andUpdateTimeNotBetween( Date value1, Date value2 ) {
            addCriterionForJDBCDate( "update_time not between", value1, value2, "updateTime" );
            return this;
        }
        
        public Criteria andUpdateUserIdIsNull() {
            addCriterion( "update_user_id is null" );
            return this;
        }
        
        public Criteria andUpdateUserIdIsNotNull() {
            addCriterion( "update_user_id is not null" );
            return this;
        }
        
        public Criteria andUpdateUserIdEqualTo( Integer value ) {
            addCriterion( "update_user_id =", value, "updateUserId" );
            return this;
        }
        
        public Criteria andUpdateUserIdNotEqualTo( Integer value ) {
            addCriterion( "update_user_id <>", value, "updateUserId" );
            return this;
        }
        
        public Criteria andUpdateUserIdGreaterThan( Integer value ) {
            addCriterion( "update_user_id >", value, "updateUserId" );
            return this;
        }
        
        public Criteria andUpdateUserIdGreaterThanOrEqualTo( Integer value ) {
            addCriterion( "update_user_id >=", value, "updateUserId" );
            return this;
        }
        
        public Criteria andUpdateUserIdLessThan( Integer value ) {
            addCriterion( "update_user_id <", value, "updateUserId" );
            return this;
        }
        
        public Criteria andUpdateUserIdLessThanOrEqualTo( Integer value ) {
            addCriterion( "update_user_id <=", value, "updateUserId" );
            return this;
        }
        
        public Criteria andUpdateUserIdIn( List values ) {
            addCriterion( "update_user_id in", values, "updateUserId" );
            return this;
        }
        
        public Criteria andUpdateUserIdNotIn( List values ) {
            addCriterion( "update_user_id not in", values, "updateUserId" );
            return this;
        }
        
        public Criteria andUpdateUserIdBetween( Integer value1, Integer value2 ) {
            addCriterion( "update_user_id between", value1, value2, "updateUserId" );
            return this;
        }
        
        public Criteria andUpdateUserIdNotBetween( Integer value1, Integer value2 ) {
            addCriterion( "update_user_id not between", value1, value2, "updateUserId" );
            return this;
        }
        
        public Criteria andIdentityPicIsNull() {
            addCriterion( "identity_pic is null" );
            return this;
        }
        
        public Criteria andIdentityPicIsNotNull() {
            addCriterion( "identity_pic is not null" );
            return this;
        }
        
        public Criteria andIdentityPicEqualTo( String value ) {
            addCriterion( "identity_pic =", value, "identityPic" );
            return this;
        }
        
        public Criteria andIdentityPicNotEqualTo( String value ) {
            addCriterion( "identity_pic <>", value, "identityPic" );
            return this;
        }
        
        public Criteria andIdentityPicGreaterThan( String value ) {
            addCriterion( "identity_pic >", value, "identityPic" );
            return this;
        }
        
        public Criteria andIdentityPicGreaterThanOrEqualTo( String value ) {
            addCriterion( "identity_pic >=", value, "identityPic" );
            return this;
        }
        
        public Criteria andIdentityPicLessThan( String value ) {
            addCriterion( "identity_pic <", value, "identityPic" );
            return this;
        }
        
        public Criteria andIdentityPicLessThanOrEqualTo( String value ) {
            addCriterion( "identity_pic <=", value, "identityPic" );
            return this;
        }
        
        public Criteria andIdentityPicLike( String value ) {
            addCriterion( "identity_pic like", value, "identityPic" );
            return this;
        }
        
        public Criteria andIdentityPicNotLike( String value ) {
            addCriterion( "identity_pic not like", value, "identityPic" );
            return this;
        }
        
        public Criteria andIdentityPicIn( List values ) {
            addCriterion( "identity_pic in", values, "identityPic" );
            return this;
        }
        
        public Criteria andIdentityPicNotIn( List values ) {
            addCriterion( "identity_pic not in", values, "identityPic" );
            return this;
        }
        
        public Criteria andIdentityPicBetween( String value1, String value2 ) {
            addCriterion( "identity_pic between", value1, value2, "identityPic" );
            return this;
        }
        
        public Criteria andIdentityPicNotBetween( String value1, String value2 ) {
            addCriterion( "identity_pic not between", value1, value2, "identityPic" );
            return this;
        }
    }
}