package com.tour.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Map;

public class TmDetailExample {
    
    protected int limitStart = 0;
    protected int limitEnd = 20;
    
    public int getLimitStart() {
        return limitStart;
    }

    
    public void setLimitStart( int limitStart ) {
        this.limitStart = limitStart;
    }

    
    public int getLimitEnd() {
        return limitEnd;
    }

    
    public void setLimitEnd( int limitEnd ) {
        this.limitEnd = limitEnd;
    }
    
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database table tm_detail
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    protected String orderByClause;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database table tm_detail
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    protected List oredCriteria;

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tm_detail
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public TmDetailExample() {
        oredCriteria = new ArrayList();
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tm_detail
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    protected TmDetailExample( TmDetailExample example ) {
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tm_detail
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public void setOrderByClause( String orderByClause ) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tm_detail
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tm_detail
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public List getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tm_detail
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public void or( Criteria criteria ) {
        oredCriteria.add( criteria );
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tm_detail
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add( criteria );
        }
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tm_detail
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tm_detail
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public void clear() {
        oredCriteria.clear();
    }

    /**
     * This class was generated by Apache iBATIS ibator. This class corresponds to the database table tm_detail
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public static class Criteria {
        
        protected List criteriaWithoutValue;
        protected List criteriaWithSingleValue;
        protected List criteriaWithListValue;
        protected List criteriaWithBetweenValue;
        
        protected Criteria() {
            super();
            criteriaWithoutValue = new ArrayList();
            criteriaWithSingleValue = new ArrayList();
            criteriaWithListValue = new ArrayList();
            criteriaWithBetweenValue = new ArrayList();
        }
        
        public boolean isValid() {
            return criteriaWithoutValue.size() > 0 || criteriaWithSingleValue.size() > 0
                    || criteriaWithListValue.size() > 0 || criteriaWithBetweenValue.size() > 0;
        }
        
        public List getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }
        
        public List getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }
        
        public List getCriteriaWithListValue() {
            return criteriaWithListValue;
        }
        
        public List getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }
        
        protected void addCriterion( String condition ) {
            if (condition == null) {
                throw new RuntimeException( "Value for condition cannot be null" );
            }
            criteriaWithoutValue.add( condition );
        }
        
        protected void addCriterion( String condition, Object value, String property ) {
            if (value == null) {
                throw new RuntimeException( "Value for " + property + " cannot be null" );
            }
            Map map = new HashMap();
            map.put( "condition", condition );
            map.put( "value", value );
            criteriaWithSingleValue.add( map );
        }
        
        protected void addCriterion( String condition, List values, String property ) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException( "Value list for " + property
                        + " cannot be null or empty" );
            }
            Map map = new HashMap();
            map.put( "condition", condition );
            map.put( "values", values );
            criteriaWithListValue.add( map );
        }
        
        protected void addCriterion( String condition, Object value1, Object value2, String property ) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException( "Between values for " + property + " cannot be null" );
            }
            List list = new ArrayList();
            list.add( value1 );
            list.add( value2 );
            Map map = new HashMap();
            map.put( "condition", condition );
            map.put( "values", list );
            criteriaWithBetweenValue.add( map );
        }
        
        protected void addCriterionForJDBCDate( String condition, Date value, String property ) {
            addCriterion( condition, new java.sql.Date( value.getTime() ), property );
        }
        
        protected void addCriterionForJDBCDate( String condition, List values, String property ) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException( "Value list for " + property
                        + " cannot be null or empty" );
            }
            List dateList = new ArrayList();
            Iterator iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add( new java.sql.Date( ((Date) iter.next()).getTime() ) );
            }
            addCriterion( condition, dateList, property );
        }
        
        protected void addCriterionForJDBCDate( String condition, Date value1, Date value2,
                String property ) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException( "Between values for " + property + " cannot be null" );
            }
            addCriterion( condition, new java.sql.Date( value1.getTime() ), new java.sql.Date(
                    value2.getTime() ), property );
        }
        
        public Criteria andIdIsNull() {
            addCriterion( "id is null" );
            return this;
        }
        
        public Criteria andIdIsNotNull() {
            addCriterion( "id is not null" );
            return this;
        }
        
        public Criteria andIdEqualTo( Integer value ) {
            addCriterion( "id =", value, "id" );
            return this;
        }
        
        public Criteria andIdNotEqualTo( Integer value ) {
            addCriterion( "id <>", value, "id" );
            return this;
        }
        
        public Criteria andIdGreaterThan( Integer value ) {
            addCriterion( "id >", value, "id" );
            return this;
        }
        
        public Criteria andIdGreaterThanOrEqualTo( Integer value ) {
            addCriterion( "id >=", value, "id" );
            return this;
        }
        
        public Criteria andIdLessThan( Integer value ) {
            addCriterion( "id <", value, "id" );
            return this;
        }
        
        public Criteria andIdLessThanOrEqualTo( Integer value ) {
            addCriterion( "id <=", value, "id" );
            return this;
        }
        
        public Criteria andIdIn( List values ) {
            addCriterion( "id in", values, "id" );
            return this;
        }
        
        public Criteria andIdNotIn( List values ) {
            addCriterion( "id not in", values, "id" );
            return this;
        }
        
        public Criteria andIdBetween( Integer value1, Integer value2 ) {
            addCriterion( "id between", value1, value2, "id" );
            return this;
        }
        
        public Criteria andIdNotBetween( Integer value1, Integer value2 ) {
            addCriterion( "id not between", value1, value2, "id" );
            return this;
        }
        
        public Criteria andHotelIdIsNull() {
            addCriterion( "hotel_id is null" );
            return this;
        }
        
        public Criteria andHotelIdIsNotNull() {
            addCriterion( "hotel_id is not null" );
            return this;
        }
        
        public Criteria andHotelIdEqualTo( Integer value ) {
            addCriterion( "hotel_id =", value, "hotelId" );
            return this;
        }
        
        public Criteria andHotelIdNotEqualTo( Integer value ) {
            addCriterion( "hotel_id <>", value, "hotelId" );
            return this;
        }
        
        public Criteria andHotelIdGreaterThan( Integer value ) {
            addCriterion( "hotel_id >", value, "hotelId" );
            return this;
        }
        
        public Criteria andHotelIdGreaterThanOrEqualTo( Integer value ) {
            addCriterion( "hotel_id >=", value, "hotelId" );
            return this;
        }
        
        public Criteria andHotelIdLessThan( Integer value ) {
            addCriterion( "hotel_id <", value, "hotelId" );
            return this;
        }
        
        public Criteria andHotelIdLessThanOrEqualTo( Integer value ) {
            addCriterion( "hotel_id <=", value, "hotelId" );
            return this;
        }
        
        public Criteria andHotelIdIn( List values ) {
            addCriterion( "hotel_id in", values, "hotelId" );
            return this;
        }
        
        public Criteria andHotelIdNotIn( List values ) {
            addCriterion( "hotel_id not in", values, "hotelId" );
            return this;
        }
        
        public Criteria andHotelIdBetween( Integer value1, Integer value2 ) {
            addCriterion( "hotel_id between", value1, value2, "hotelId" );
            return this;
        }
        
        public Criteria andHotelIdNotBetween( Integer value1, Integer value2 ) {
            addCriterion( "hotel_id not between", value1, value2, "hotelId" );
            return this;
        }
        
        public Criteria andTourIsNull() {
            addCriterion( "tour is null" );
            return this;
        }
        
        public Criteria andTourIsNotNull() {
            addCriterion( "tour is not null" );
            return this;
        }
        
        public Criteria andTourEqualTo( String value ) {
            addCriterion( "tour =", value, "tour" );
            return this;
        }
        
        public Criteria andTourNotEqualTo( String value ) {
            addCriterion( "tour <>", value, "tour" );
            return this;
        }
        
        public Criteria andTourGreaterThan( String value ) {
            addCriterion( "tour >", value, "tour" );
            return this;
        }
        
        public Criteria andTourGreaterThanOrEqualTo( String value ) {
            addCriterion( "tour >=", value, "tour" );
            return this;
        }
        
        public Criteria andTourLessThan( String value ) {
            addCriterion( "tour <", value, "tour" );
            return this;
        }
        
        public Criteria andTourLessThanOrEqualTo( String value ) {
            addCriterion( "tour <=", value, "tour" );
            return this;
        }
        
        public Criteria andTourLike( String value ) {
            addCriterion( "tour like", value, "tour" );
            return this;
        }
        
        public Criteria andTourNotLike( String value ) {
            addCriterion( "tour not like", value, "tour" );
            return this;
        }
        
        public Criteria andTourIn( List values ) {
            addCriterion( "tour in", values, "tour" );
            return this;
        }
        
        public Criteria andTourNotIn( List values ) {
            addCriterion( "tour not in", values, "tour" );
            return this;
        }
        
        public Criteria andTourBetween( String value1, String value2 ) {
            addCriterion( "tour between", value1, value2, "tour" );
            return this;
        }
        
        public Criteria andTourNotBetween( String value1, String value2 ) {
            addCriterion( "tour not between", value1, value2, "tour" );
            return this;
        }
        
        public Criteria andWalkIsNull() {
            addCriterion( "walk is null" );
            return this;
        }
        
        public Criteria andWalkIsNotNull() {
            addCriterion( "walk is not null" );
            return this;
        }
        
        public Criteria andWalkEqualTo( String value ) {
            addCriterion( "walk =", value, "walk" );
            return this;
        }
        
        public Criteria andWalkNotEqualTo( String value ) {
            addCriterion( "walk <>", value, "walk" );
            return this;
        }
        
        public Criteria andWalkGreaterThan( String value ) {
            addCriterion( "walk >", value, "walk" );
            return this;
        }
        
        public Criteria andWalkGreaterThanOrEqualTo( String value ) {
            addCriterion( "walk >=", value, "walk" );
            return this;
        }
        
        public Criteria andWalkLessThan( String value ) {
            addCriterion( "walk <", value, "walk" );
            return this;
        }
        
        public Criteria andWalkLessThanOrEqualTo( String value ) {
            addCriterion( "walk <=", value, "walk" );
            return this;
        }
        
        public Criteria andWalkLike( String value ) {
            addCriterion( "walk like", value, "walk" );
            return this;
        }
        
        public Criteria andWalkNotLike( String value ) {
            addCriterion( "walk not like", value, "walk" );
            return this;
        }
        
        public Criteria andWalkIn( List values ) {
            addCriterion( "walk in", values, "walk" );
            return this;
        }
        
        public Criteria andWalkNotIn( List values ) {
            addCriterion( "walk not in", values, "walk" );
            return this;
        }
        
        public Criteria andWalkBetween( String value1, String value2 ) {
            addCriterion( "walk between", value1, value2, "walk" );
            return this;
        }
        
        public Criteria andWalkNotBetween( String value1, String value2 ) {
            addCriterion( "walk not between", value1, value2, "walk" );
            return this;
        }
        
        public Criteria andEatIsNull() {
            addCriterion( "eat is null" );
            return this;
        }
        
        public Criteria andEatIsNotNull() {
            addCriterion( "eat is not null" );
            return this;
        }
        
        public Criteria andEatEqualTo( String value ) {
            addCriterion( "eat =", value, "eat" );
            return this;
        }
        
        public Criteria andEatNotEqualTo( String value ) {
            addCriterion( "eat <>", value, "eat" );
            return this;
        }
        
        public Criteria andEatGreaterThan( String value ) {
            addCriterion( "eat >", value, "eat" );
            return this;
        }
        
        public Criteria andEatGreaterThanOrEqualTo( String value ) {
            addCriterion( "eat >=", value, "eat" );
            return this;
        }
        
        public Criteria andEatLessThan( String value ) {
            addCriterion( "eat <", value, "eat" );
            return this;
        }
        
        public Criteria andEatLessThanOrEqualTo( String value ) {
            addCriterion( "eat <=", value, "eat" );
            return this;
        }
        
        public Criteria andEatLike( String value ) {
            addCriterion( "eat like", value, "eat" );
            return this;
        }
        
        public Criteria andEatNotLike( String value ) {
            addCriterion( "eat not like", value, "eat" );
            return this;
        }
        
        public Criteria andEatIn( List values ) {
            addCriterion( "eat in", values, "eat" );
            return this;
        }
        
        public Criteria andEatNotIn( List values ) {
            addCriterion( "eat not in", values, "eat" );
            return this;
        }
        
        public Criteria andEatBetween( String value1, String value2 ) {
            addCriterion( "eat between", value1, value2, "eat" );
            return this;
        }
        
        public Criteria andEatNotBetween( String value1, String value2 ) {
            addCriterion( "eat not between", value1, value2, "eat" );
            return this;
        }
        
        public Criteria andHotelNameIsNull() {
            addCriterion( "hotel_name is null" );
            return this;
        }
        
        public Criteria andHotelNameIsNotNull() {
            addCriterion( "hotel_name is not null" );
            return this;
        }
        
        public Criteria andHotelNameEqualTo( String value ) {
            addCriterion( "hotel_name =", value, "hotelName" );
            return this;
        }
        
        public Criteria andHotelNameNotEqualTo( String value ) {
            addCriterion( "hotel_name <>", value, "hotelName" );
            return this;
        }
        
        public Criteria andHotelNameGreaterThan( String value ) {
            addCriterion( "hotel_name >", value, "hotelName" );
            return this;
        }
        
        public Criteria andHotelNameGreaterThanOrEqualTo( String value ) {
            addCriterion( "hotel_name >=", value, "hotelName" );
            return this;
        }
        
        public Criteria andHotelNameLessThan( String value ) {
            addCriterion( "hotel_name <", value, "hotelName" );
            return this;
        }
        
        public Criteria andHotelNameLessThanOrEqualTo( String value ) {
            addCriterion( "hotel_name <=", value, "hotelName" );
            return this;
        }
        
        public Criteria andHotelNameLike( String value ) {
            addCriterion( "hotel_name like", value, "hotelName" );
            return this;
        }
        
        public Criteria andHotelNameNotLike( String value ) {
            addCriterion( "hotel_name not like", value, "hotelName" );
            return this;
        }
        
        public Criteria andHotelNameIn( List values ) {
            addCriterion( "hotel_name in", values, "hotelName" );
            return this;
        }
        
        public Criteria andHotelNameNotIn( List values ) {
            addCriterion( "hotel_name not in", values, "hotelName" );
            return this;
        }
        
        public Criteria andHotelNameBetween( String value1, String value2 ) {
            addCriterion( "hotel_name between", value1, value2, "hotelName" );
            return this;
        }
        
        public Criteria andHotelNameNotBetween( String value1, String value2 ) {
            addCriterion( "hotel_name not between", value1, value2, "hotelName" );
            return this;
        }
        
        public Criteria andInfoIsNull() {
            addCriterion( "info is null" );
            return this;
        }
        
        public Criteria andInfoIsNotNull() {
            addCriterion( "info is not null" );
            return this;
        }
        
        public Criteria andInfoEqualTo( String value ) {
            addCriterion( "info =", value, "info" );
            return this;
        }
        
        public Criteria andInfoNotEqualTo( String value ) {
            addCriterion( "info <>", value, "info" );
            return this;
        }
        
        public Criteria andInfoGreaterThan( String value ) {
            addCriterion( "info >", value, "info" );
            return this;
        }
        
        public Criteria andInfoGreaterThanOrEqualTo( String value ) {
            addCriterion( "info >=", value, "info" );
            return this;
        }
        
        public Criteria andInfoLessThan( String value ) {
            addCriterion( "info <", value, "info" );
            return this;
        }
        
        public Criteria andInfoLessThanOrEqualTo( String value ) {
            addCriterion( "info <=", value, "info" );
            return this;
        }
        
        public Criteria andInfoLike( String value ) {
            addCriterion( "info like", value, "info" );
            return this;
        }
        
        public Criteria andInfoNotLike( String value ) {
            addCriterion( "info not like", value, "info" );
            return this;
        }
        
        public Criteria andInfoIn( List values ) {
            addCriterion( "info in", values, "info" );
            return this;
        }
        
        public Criteria andInfoNotIn( List values ) {
            addCriterion( "info not in", values, "info" );
            return this;
        }
        
        public Criteria andInfoBetween( String value1, String value2 ) {
            addCriterion( "info between", value1, value2, "info" );
            return this;
        }
        
        public Criteria andInfoNotBetween( String value1, String value2 ) {
            addCriterion( "info not between", value1, value2, "info" );
            return this;
        }
        
        public Criteria andIsDelIsNull() {
            addCriterion( "is_del is null" );
            return this;
        }
        
        public Criteria andIsDelIsNotNull() {
            addCriterion( "is_del is not null" );
            return this;
        }
        
        public Criteria andIsDelEqualTo( String value ) {
            addCriterion( "is_del =", value, "isDel" );
            return this;
        }
        
        public Criteria andIsDelNotEqualTo( String value ) {
            addCriterion( "is_del <>", value, "isDel" );
            return this;
        }
        
        public Criteria andIsDelGreaterThan( String value ) {
            addCriterion( "is_del >", value, "isDel" );
            return this;
        }
        
        public Criteria andIsDelGreaterThanOrEqualTo( String value ) {
            addCriterion( "is_del >=", value, "isDel" );
            return this;
        }
        
        public Criteria andIsDelLessThan( String value ) {
            addCriterion( "is_del <", value, "isDel" );
            return this;
        }
        
        public Criteria andIsDelLessThanOrEqualTo( String value ) {
            addCriterion( "is_del <=", value, "isDel" );
            return this;
        }
        
        public Criteria andIsDelLike( String value ) {
            addCriterion( "is_del like", value, "isDel" );
            return this;
        }
        
        public Criteria andIsDelNotLike( String value ) {
            addCriterion( "is_del not like", value, "isDel" );
            return this;
        }
        
        public Criteria andIsDelIn( List values ) {
            addCriterion( "is_del in", values, "isDel" );
            return this;
        }
        
        public Criteria andIsDelNotIn( List values ) {
            addCriterion( "is_del not in", values, "isDel" );
            return this;
        }
        
        public Criteria andIsDelBetween( String value1, String value2 ) {
            addCriterion( "is_del between", value1, value2, "isDel" );
            return this;
        }
        
        public Criteria andIsDelNotBetween( String value1, String value2 ) {
            addCriterion( "is_del not between", value1, value2, "isDel" );
            return this;
        }
        
        public Criteria andCreateTimeIsNull() {
            addCriterion( "create_time is null" );
            return this;
        }
        
        public Criteria andCreateTimeIsNotNull() {
            addCriterion( "create_time is not null" );
            return this;
        }
        
        public Criteria andCreateTimeEqualTo( Date value ) {
            addCriterionForJDBCDate( "create_time =", value, "createTime" );
            return this;
        }
        
        public Criteria andCreateTimeNotEqualTo( Date value ) {
            addCriterionForJDBCDate( "create_time <>", value, "createTime" );
            return this;
        }
        
        public Criteria andCreateTimeGreaterThan( Date value ) {
            addCriterionForJDBCDate( "create_time >", value, "createTime" );
            return this;
        }
        
        public Criteria andCreateTimeGreaterThanOrEqualTo( Date value ) {
            addCriterionForJDBCDate( "create_time >=", value, "createTime" );
            return this;
        }
        
        public Criteria andCreateTimeLessThan( Date value ) {
            addCriterionForJDBCDate( "create_time <", value, "createTime" );
            return this;
        }
        
        public Criteria andCreateTimeLessThanOrEqualTo( Date value ) {
            addCriterionForJDBCDate( "create_time <=", value, "createTime" );
            return this;
        }
        
        public Criteria andCreateTimeIn( List values ) {
            addCriterionForJDBCDate( "create_time in", values, "createTime" );
            return this;
        }
        
        public Criteria andCreateTimeNotIn( List values ) {
            addCriterionForJDBCDate( "create_time not in", values, "createTime" );
            return this;
        }
        
        public Criteria andCreateTimeBetween( Date value1, Date value2 ) {
            addCriterionForJDBCDate( "create_time between", value1, value2, "createTime" );
            return this;
        }
        
        public Criteria andCreateTimeNotBetween( Date value1, Date value2 ) {
            addCriterionForJDBCDate( "create_time not between", value1, value2, "createTime" );
            return this;
        }
        
        public Criteria andCreateUserIdIsNull() {
            addCriterion( "create_user_id is null" );
            return this;
        }
        
        public Criteria andCreateUserIdIsNotNull() {
            addCriterion( "create_user_id is not null" );
            return this;
        }
        
        public Criteria andCreateUserIdEqualTo( Integer value ) {
            addCriterion( "create_user_id =", value, "createUserId" );
            return this;
        }
        
        public Criteria andCreateUserIdNotEqualTo( Integer value ) {
            addCriterion( "create_user_id <>", value, "createUserId" );
            return this;
        }
        
        public Criteria andCreateUserIdGreaterThan( Integer value ) {
            addCriterion( "create_user_id >", value, "createUserId" );
            return this;
        }
        
        public Criteria andCreateUserIdGreaterThanOrEqualTo( Integer value ) {
            addCriterion( "create_user_id >=", value, "createUserId" );
            return this;
        }
        
        public Criteria andCreateUserIdLessThan( Integer value ) {
            addCriterion( "create_user_id <", value, "createUserId" );
            return this;
        }
        
        public Criteria andCreateUserIdLessThanOrEqualTo( Integer value ) {
            addCriterion( "create_user_id <=", value, "createUserId" );
            return this;
        }
        
        public Criteria andCreateUserIdIn( List values ) {
            addCriterion( "create_user_id in", values, "createUserId" );
            return this;
        }
        
        public Criteria andCreateUserIdNotIn( List values ) {
            addCriterion( "create_user_id not in", values, "createUserId" );
            return this;
        }
        
        public Criteria andCreateUserIdBetween( Integer value1, Integer value2 ) {
            addCriterion( "create_user_id between", value1, value2, "createUserId" );
            return this;
        }
        
        public Criteria andCreateUserIdNotBetween( Integer value1, Integer value2 ) {
            addCriterion( "create_user_id not between", value1, value2, "createUserId" );
            return this;
        }
        
        public Criteria andUpdateTimeIsNull() {
            addCriterion( "update_time is null" );
            return this;
        }
        
        public Criteria andUpdateTimeIsNotNull() {
            addCriterion( "update_time is not null" );
            return this;
        }
        
        public Criteria andUpdateTimeEqualTo( Date value ) {
            addCriterionForJDBCDate( "update_time =", value, "updateTime" );
            return this;
        }
        
        public Criteria andUpdateTimeNotEqualTo( Date value ) {
            addCriterionForJDBCDate( "update_time <>", value, "updateTime" );
            return this;
        }
        
        public Criteria andUpdateTimeGreaterThan( Date value ) {
            addCriterionForJDBCDate( "update_time >", value, "updateTime" );
            return this;
        }
        
        public Criteria andUpdateTimeGreaterThanOrEqualTo( Date value ) {
            addCriterionForJDBCDate( "update_time >=", value, "updateTime" );
            return this;
        }
        
        public Criteria andUpdateTimeLessThan( Date value ) {
            addCriterionForJDBCDate( "update_time <", value, "updateTime" );
            return this;
        }
        
        public Criteria andUpdateTimeLessThanOrEqualTo( Date value ) {
            addCriterionForJDBCDate( "update_time <=", value, "updateTime" );
            return this;
        }
        
        public Criteria andUpdateTimeIn( List values ) {
            addCriterionForJDBCDate( "update_time in", values, "updateTime" );
            return this;
        }
        
        public Criteria andUpdateTimeNotIn( List values ) {
            addCriterionForJDBCDate( "update_time not in", values, "updateTime" );
            return this;
        }
        
        public Criteria andUpdateTimeBetween( Date value1, Date value2 ) {
            addCriterionForJDBCDate( "update_time between", value1, value2, "updateTime" );
            return this;
        }
        
        public Criteria andUpdateTimeNotBetween( Date value1, Date value2 ) {
            addCriterionForJDBCDate( "update_time not between", value1, value2, "updateTime" );
            return this;
        }
        
        public Criteria andUpdateUserIdIsNull() {
            addCriterion( "update_user_id is null" );
            return this;
        }
        
        public Criteria andUpdateUserIdIsNotNull() {
            addCriterion( "update_user_id is not null" );
            return this;
        }
        
        public Criteria andUpdateUserIdEqualTo( Integer value ) {
            addCriterion( "update_user_id =", value, "updateUserId" );
            return this;
        }
        
        public Criteria andUpdateUserIdNotEqualTo( Integer value ) {
            addCriterion( "update_user_id <>", value, "updateUserId" );
            return this;
        }
        
        public Criteria andUpdateUserIdGreaterThan( Integer value ) {
            addCriterion( "update_user_id >", value, "updateUserId" );
            return this;
        }
        
        public Criteria andUpdateUserIdGreaterThanOrEqualTo( Integer value ) {
            addCriterion( "update_user_id >=", value, "updateUserId" );
            return this;
        }
        
        public Criteria andUpdateUserIdLessThan( Integer value ) {
            addCriterion( "update_user_id <", value, "updateUserId" );
            return this;
        }
        
        public Criteria andUpdateUserIdLessThanOrEqualTo( Integer value ) {
            addCriterion( "update_user_id <=", value, "updateUserId" );
            return this;
        }
        
        public Criteria andUpdateUserIdIn( List values ) {
            addCriterion( "update_user_id in", values, "updateUserId" );
            return this;
        }
        
        public Criteria andUpdateUserIdNotIn( List values ) {
            addCriterion( "update_user_id not in", values, "updateUserId" );
            return this;
        }
        
        public Criteria andUpdateUserIdBetween( Integer value1, Integer value2 ) {
            addCriterion( "update_user_id between", value1, value2, "updateUserId" );
            return this;
        }
        
        public Criteria andUpdateUserIdNotBetween( Integer value1, Integer value2 ) {
            addCriterion( "update_user_id not between", value1, value2, "updateUserId" );
            return this;
        }
    }
}