package com.tour.model;

import java.util.Date;

public class TmDepartment {

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column tm_department.id
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    private Integer id;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column tm_department.dept_name
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    private String deptName;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column tm_department.super_id
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    private Integer superId;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column tm_department.description
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    private String description;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column tm_department.is_del
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    private String isDel;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column tm_department.create_time
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    private Date createTime;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column tm_department.create_user_id
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    private Integer createUserId;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column tm_department.update_time
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    private Date updateTime;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column tm_department.update_user_id
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    private Integer updateUserId;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column tm_department.dept_icon
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    private String deptIcon;

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column tm_department.id
     * @return  the value of tm_department.id
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column tm_department.id
     * @param id  the value for tm_department.id
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public void setId( Integer id ) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column tm_department.dept_name
     * @return  the value of tm_department.dept_name
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public String getDeptName() {
        return deptName;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column tm_department.dept_name
     * @param deptName  the value for tm_department.dept_name
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public void setDeptName( String deptName ) {
        this.deptName = deptName;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column tm_department.super_id
     * @return  the value of tm_department.super_id
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public Integer getSuperId() {
        return superId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column tm_department.super_id
     * @param superId  the value for tm_department.super_id
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public void setSuperId( Integer superId ) {
        this.superId = superId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column tm_department.description
     * @return  the value of tm_department.description
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column tm_department.description
     * @param description  the value for tm_department.description
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public void setDescription( String description ) {
        this.description = description;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column tm_department.is_del
     * @return  the value of tm_department.is_del
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public String getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column tm_department.is_del
     * @param isDel  the value for tm_department.is_del
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public void setIsDel( String isDel ) {
        this.isDel = isDel;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column tm_department.create_time
     * @return  the value of tm_department.create_time
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column tm_department.create_time
     * @param createTime  the value for tm_department.create_time
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public void setCreateTime( Date createTime ) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column tm_department.create_user_id
     * @return  the value of tm_department.create_user_id
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public Integer getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column tm_department.create_user_id
     * @param createUserId  the value for tm_department.create_user_id
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public void setCreateUserId( Integer createUserId ) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column tm_department.update_time
     * @return  the value of tm_department.update_time
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column tm_department.update_time
     * @param updateTime  the value for tm_department.update_time
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public void setUpdateTime( Date updateTime ) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column tm_department.update_user_id
     * @return  the value of tm_department.update_user_id
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public Integer getUpdateUserId() {
        return updateUserId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column tm_department.update_user_id
     * @param updateUserId  the value for tm_department.update_user_id
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public void setUpdateUserId( Integer updateUserId ) {
        this.updateUserId = updateUserId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column tm_department.dept_icon
     * @return  the value of tm_department.dept_icon
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public String getDeptIcon() {
        return deptIcon;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column tm_department.dept_icon
     * @param deptIcon  the value for tm_department.dept_icon
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public void setDeptIcon( String deptIcon ) {
        this.deptIcon = deptIcon;
    }
}