package com.tour.model;

import java.util.Date;

public class TmDetail {

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column tm_detail.id
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    private Integer id;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column tm_detail.hotel_id
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    private Integer hotelId;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column tm_detail.tour
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    private String tour;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column tm_detail.walk
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    private String walk;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column tm_detail.eat
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    private String eat;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column tm_detail.hotel_name
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    private String hotelName;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column tm_detail.info
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    private String info;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column tm_detail.is_del
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    private String isDel;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column tm_detail.create_time
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    private Date createTime;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column tm_detail.create_user_id
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    private Integer createUserId;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column tm_detail.update_time
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    private Date updateTime;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column tm_detail.update_user_id
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    private Integer updateUserId;

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column tm_detail.id
     * @return  the value of tm_detail.id
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column tm_detail.id
     * @param id  the value for tm_detail.id
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public void setId( Integer id ) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column tm_detail.hotel_id
     * @return  the value of tm_detail.hotel_id
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public Integer getHotelId() {
        return hotelId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column tm_detail.hotel_id
     * @param hotelId  the value for tm_detail.hotel_id
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public void setHotelId( Integer hotelId ) {
        this.hotelId = hotelId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column tm_detail.tour
     * @return  the value of tm_detail.tour
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public String getTour() {
        return tour;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column tm_detail.tour
     * @param tour  the value for tm_detail.tour
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public void setTour( String tour ) {
        this.tour = tour;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column tm_detail.walk
     * @return  the value of tm_detail.walk
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public String getWalk() {
        return walk;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column tm_detail.walk
     * @param walk  the value for tm_detail.walk
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public void setWalk( String walk ) {
        this.walk = walk;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column tm_detail.eat
     * @return  the value of tm_detail.eat
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public String getEat() {
        return eat;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column tm_detail.eat
     * @param eat  the value for tm_detail.eat
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public void setEat( String eat ) {
        this.eat = eat;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column tm_detail.hotel_name
     * @return  the value of tm_detail.hotel_name
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public String getHotelName() {
        return hotelName;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column tm_detail.hotel_name
     * @param hotelName  the value for tm_detail.hotel_name
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public void setHotelName( String hotelName ) {
        this.hotelName = hotelName;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column tm_detail.info
     * @return  the value of tm_detail.info
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public String getInfo() {
        return info;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column tm_detail.info
     * @param info  the value for tm_detail.info
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public void setInfo( String info ) {
        this.info = info;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column tm_detail.is_del
     * @return  the value of tm_detail.is_del
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public String getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column tm_detail.is_del
     * @param isDel  the value for tm_detail.is_del
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public void setIsDel( String isDel ) {
        this.isDel = isDel;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column tm_detail.create_time
     * @return  the value of tm_detail.create_time
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column tm_detail.create_time
     * @param createTime  the value for tm_detail.create_time
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public void setCreateTime( Date createTime ) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column tm_detail.create_user_id
     * @return  the value of tm_detail.create_user_id
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public Integer getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column tm_detail.create_user_id
     * @param createUserId  the value for tm_detail.create_user_id
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public void setCreateUserId( Integer createUserId ) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column tm_detail.update_time
     * @return  the value of tm_detail.update_time
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column tm_detail.update_time
     * @param updateTime  the value for tm_detail.update_time
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public void setUpdateTime( Date updateTime ) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column tm_detail.update_user_id
     * @return  the value of tm_detail.update_user_id
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public Integer getUpdateUserId() {
        return updateUserId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column tm_detail.update_user_id
     * @param updateUserId  the value for tm_detail.update_user_id
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public void setUpdateUserId( Integer updateUserId ) {
        this.updateUserId = updateUserId;
    }
}