package com.tour.model;

public class TmEmployee {

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column tm_employee.id
     * @ibatorgenerated  Thu May 14 09:05:10 CST 2015
     */
    private Integer id;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column tm_employee.employee_num
     * @ibatorgenerated  Thu May 14 09:05:10 CST 2015
     */
    private String employeeNum;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column tm_employee.real_name
     * @ibatorgenerated  Thu May 14 09:05:10 CST 2015
     */
    private String realName;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column tm_employee.tel
     * @ibatorgenerated  Thu May 14 09:05:10 CST 2015
     */
    private String tel;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column tm_employee.dept_id
     * @ibatorgenerated  Thu May 14 09:05:10 CST 2015
     */
    private Integer deptId;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column tm_employee.user_id
     * @ibatorgenerated  Thu May 14 09:05:10 CST 2015
     */
    private Integer userId;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column tm_employee.sex
     * @ibatorgenerated  Thu May 14 09:05:10 CST 2015
     */
    private Integer sex;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column tm_employee.is_guider
     * @ibatorgenerated  Thu May 14 09:05:10 CST 2015
     */
    private Integer isGuider;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column tm_employee.is_del
     * @ibatorgenerated  Thu May 14 09:05:10 CST 2015
     */
    private String isDel;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column tm_employee.head
     * @ibatorgenerated  Thu May 14 09:05:10 CST 2015
     */
    private String head;

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column tm_employee.id
     * @return  the value of tm_employee.id
     * @ibatorgenerated  Thu May 14 09:05:10 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column tm_employee.id
     * @param id  the value for tm_employee.id
     * @ibatorgenerated  Thu May 14 09:05:10 CST 2015
     */
    public void setId( Integer id ) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column tm_employee.employee_num
     * @return  the value of tm_employee.employee_num
     * @ibatorgenerated  Thu May 14 09:05:10 CST 2015
     */
    public String getEmployeeNum() {
        return employeeNum;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column tm_employee.employee_num
     * @param employeeNum  the value for tm_employee.employee_num
     * @ibatorgenerated  Thu May 14 09:05:10 CST 2015
     */
    public void setEmployeeNum( String employeeNum ) {
        this.employeeNum = employeeNum;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column tm_employee.real_name
     * @return  the value of tm_employee.real_name
     * @ibatorgenerated  Thu May 14 09:05:10 CST 2015
     */
    public String getRealName() {
        return realName;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column tm_employee.real_name
     * @param realName  the value for tm_employee.real_name
     * @ibatorgenerated  Thu May 14 09:05:10 CST 2015
     */
    public void setRealName( String realName ) {
        this.realName = realName;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column tm_employee.tel
     * @return  the value of tm_employee.tel
     * @ibatorgenerated  Thu May 14 09:05:10 CST 2015
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column tm_employee.tel
     * @param tel  the value for tm_employee.tel
     * @ibatorgenerated  Thu May 14 09:05:10 CST 2015
     */
    public void setTel( String tel ) {
        this.tel = tel;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column tm_employee.dept_id
     * @return  the value of tm_employee.dept_id
     * @ibatorgenerated  Thu May 14 09:05:10 CST 2015
     */
    public Integer getDeptId() {
        return deptId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column tm_employee.dept_id
     * @param deptId  the value for tm_employee.dept_id
     * @ibatorgenerated  Thu May 14 09:05:10 CST 2015
     */
    public void setDeptId( Integer deptId ) {
        this.deptId = deptId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column tm_employee.user_id
     * @return  the value of tm_employee.user_id
     * @ibatorgenerated  Thu May 14 09:05:10 CST 2015
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column tm_employee.user_id
     * @param userId  the value for tm_employee.user_id
     * @ibatorgenerated  Thu May 14 09:05:10 CST 2015
     */
    public void setUserId( Integer userId ) {
        this.userId = userId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column tm_employee.sex
     * @return  the value of tm_employee.sex
     * @ibatorgenerated  Thu May 14 09:05:10 CST 2015
     */
    public Integer getSex() {
        return sex;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column tm_employee.sex
     * @param sex  the value for tm_employee.sex
     * @ibatorgenerated  Thu May 14 09:05:10 CST 2015
     */
    public void setSex( Integer sex ) {
        this.sex = sex;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column tm_employee.is_guider
     * @return  the value of tm_employee.is_guider
     * @ibatorgenerated  Thu May 14 09:05:10 CST 2015
     */
    public Integer getIsGuider() {
        return isGuider;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column tm_employee.is_guider
     * @param isGuider  the value for tm_employee.is_guider
     * @ibatorgenerated  Thu May 14 09:05:10 CST 2015
     */
    public void setIsGuider( Integer isGuider ) {
        this.isGuider = isGuider;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column tm_employee.is_del
     * @return  the value of tm_employee.is_del
     * @ibatorgenerated  Thu May 14 09:05:10 CST 2015
     */
    public String getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column tm_employee.is_del
     * @param isDel  the value for tm_employee.is_del
     * @ibatorgenerated  Thu May 14 09:05:10 CST 2015
     */
    public void setIsDel( String isDel ) {
        this.isDel = isDel;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column tm_employee.head
     * @return  the value of tm_employee.head
     * @ibatorgenerated  Thu May 14 09:05:10 CST 2015
     */
    public String getHead() {
        return head;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column tm_employee.head
     * @param head  the value for tm_employee.head
     * @ibatorgenerated  Thu May 14 09:05:10 CST 2015
     */
    public void setHead( String head ) {
        this.head = head;
    }
}