package com.tour.model;

import java.util.Date;

public class TmGroup {

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column tm_group.id
     * @ibatorgenerated  Thu Jun 11 00:35:49 CST 2015
     */
    private Integer id;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column tm_group.group_name
     * @ibatorgenerated  Thu Jun 11 00:35:49 CST 2015
     */
    private String groupName;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column tm_group.tour_id
     * @ibatorgenerated  Thu Jun 11 00:35:49 CST 2015
     */
    private Integer tourId;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column tm_group.is_del
     * @ibatorgenerated  Thu Jun 11 00:35:49 CST 2015
     */
    private String isDel;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column tm_group.schedule_id
     * @ibatorgenerated  Thu Jun 11 00:35:49 CST 2015
     */
    private Integer scheduleId;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column tm_group.create_time
     * @ibatorgenerated  Thu Jun 11 00:35:49 CST 2015
     */
    private Date createTime;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column tm_group.create_user_id
     * @ibatorgenerated  Thu Jun 11 00:35:49 CST 2015
     */
    private Integer createUserId;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column tm_group.update_time
     * @ibatorgenerated  Thu Jun 11 00:35:49 CST 2015
     */
    private Date updateTime;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column tm_group.update_user_id
     * @ibatorgenerated  Thu Jun 11 00:35:49 CST 2015
     */
    private Integer updateUserId;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column tm_group.status
     * @ibatorgenerated  Thu Jun 11 00:35:49 CST 2015
     */
    private Integer status;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column tm_group.guider_ids
     * @ibatorgenerated  Thu Jun 11 00:35:49 CST 2015
     */
    private String guiderIds;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column tm_group.start_time
     * @ibatorgenerated  Thu Jun 11 00:35:49 CST 2015
     */
    private Date startTime;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column tm_group.end_time
     * @ibatorgenerated  Thu Jun 11 00:35:49 CST 2015
     */
    private Date endTime;

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column tm_group.id
     * @return  the value of tm_group.id
     * @ibatorgenerated  Thu Jun 11 00:35:49 CST 2015
     */
    public Integer getId() {
        return id;
    }


    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column tm_group.id
     * @param id  the value for tm_group.id
     * @ibatorgenerated  Thu Jun 11 00:35:49 CST 2015
     */
    public void setId( Integer id ) {
        this.id = id;
    }


    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column tm_group.group_name
     * @return  the value of tm_group.group_name
     * @ibatorgenerated  Thu Jun 11 00:35:49 CST 2015
     */
    public String getGroupName() {
        return groupName;
    }


    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column tm_group.group_name
     * @param groupName  the value for tm_group.group_name
     * @ibatorgenerated  Thu Jun 11 00:35:49 CST 2015
     */
    public void setGroupName( String groupName ) {
        this.groupName = groupName;
    }


    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column tm_group.tour_id
     * @return  the value of tm_group.tour_id
     * @ibatorgenerated  Thu Jun 11 00:35:49 CST 2015
     */
    public Integer getTourId() {
        return tourId;
    }


    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column tm_group.tour_id
     * @param tourId  the value for tm_group.tour_id
     * @ibatorgenerated  Thu Jun 11 00:35:49 CST 2015
     */
    public void setTourId( Integer tourId ) {
        this.tourId = tourId;
    }


    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column tm_group.is_del
     * @return  the value of tm_group.is_del
     * @ibatorgenerated  Thu Jun 11 00:35:49 CST 2015
     */
    public String getIsDel() {
        return isDel;
    }


    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column tm_group.is_del
     * @param isDel  the value for tm_group.is_del
     * @ibatorgenerated  Thu Jun 11 00:35:49 CST 2015
     */
    public void setIsDel( String isDel ) {
        this.isDel = isDel;
    }


    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column tm_group.schedule_id
     * @return  the value of tm_group.schedule_id
     * @ibatorgenerated  Thu Jun 11 00:35:49 CST 2015
     */
    public Integer getScheduleId() {
        return scheduleId;
    }


    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column tm_group.schedule_id
     * @param scheduleId  the value for tm_group.schedule_id
     * @ibatorgenerated  Thu Jun 11 00:35:49 CST 2015
     */
    public void setScheduleId( Integer scheduleId ) {
        this.scheduleId = scheduleId;
    }


    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column tm_group.create_time
     * @return  the value of tm_group.create_time
     * @ibatorgenerated  Thu Jun 11 00:35:49 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }


    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column tm_group.create_time
     * @param createTime  the value for tm_group.create_time
     * @ibatorgenerated  Thu Jun 11 00:35:49 CST 2015
     */
    public void setCreateTime( Date createTime ) {
        this.createTime = createTime;
    }


    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column tm_group.create_user_id
     * @return  the value of tm_group.create_user_id
     * @ibatorgenerated  Thu Jun 11 00:35:49 CST 2015
     */
    public Integer getCreateUserId() {
        return createUserId;
    }


    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column tm_group.create_user_id
     * @param createUserId  the value for tm_group.create_user_id
     * @ibatorgenerated  Thu Jun 11 00:35:49 CST 2015
     */
    public void setCreateUserId( Integer createUserId ) {
        this.createUserId = createUserId;
    }


    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column tm_group.update_time
     * @return  the value of tm_group.update_time
     * @ibatorgenerated  Thu Jun 11 00:35:49 CST 2015
     */
    public Date getUpdateTime() {
        return updateTime;
    }


    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column tm_group.update_time
     * @param updateTime  the value for tm_group.update_time
     * @ibatorgenerated  Thu Jun 11 00:35:49 CST 2015
     */
    public void setUpdateTime( Date updateTime ) {
        this.updateTime = updateTime;
    }


    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column tm_group.update_user_id
     * @return  the value of tm_group.update_user_id
     * @ibatorgenerated  Thu Jun 11 00:35:49 CST 2015
     */
    public Integer getUpdateUserId() {
        return updateUserId;
    }


    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column tm_group.update_user_id
     * @param updateUserId  the value for tm_group.update_user_id
     * @ibatorgenerated  Thu Jun 11 00:35:49 CST 2015
     */
    public void setUpdateUserId( Integer updateUserId ) {
        this.updateUserId = updateUserId;
    }


    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column tm_group.status
     * @return  the value of tm_group.status
     * @ibatorgenerated  Thu Jun 11 00:35:49 CST 2015
     */
    public Integer getStatus() {
        return status;
    }


    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column tm_group.status
     * @param status  the value for tm_group.status
     * @ibatorgenerated  Thu Jun 11 00:35:49 CST 2015
     */
    public void setStatus( Integer status ) {
        this.status = status;
    }


    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column tm_group.guider_ids
     * @return  the value of tm_group.guider_ids
     * @ibatorgenerated  Thu Jun 11 00:35:49 CST 2015
     */
    public String getGuiderIds() {
        return guiderIds;
    }


    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column tm_group.guider_ids
     * @param guiderIds  the value for tm_group.guider_ids
     * @ibatorgenerated  Thu Jun 11 00:35:49 CST 2015
     */
    public void setGuiderIds( String guiderIds ) {
        this.guiderIds = guiderIds;
    }


    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column tm_group.start_time
     * @return  the value of tm_group.start_time
     * @ibatorgenerated  Thu Jun 11 00:35:49 CST 2015
     */
    public Date getStartTime() {
        return startTime;
    }


    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column tm_group.start_time
     * @param startTime  the value for tm_group.start_time
     * @ibatorgenerated  Thu Jun 11 00:35:49 CST 2015
     */
    public void setStartTime( Date startTime ) {
        this.startTime = startTime;
    }


    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column tm_group.end_time
     * @return  the value of tm_group.end_time
     * @ibatorgenerated  Thu Jun 11 00:35:49 CST 2015
     */
    public Date getEndTime() {
        return endTime;
    }


    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column tm_group.end_time
     * @param endTime  the value for tm_group.end_time
     * @ibatorgenerated  Thu Jun 11 00:35:49 CST 2015
     */
    public void setEndTime( Date endTime ) {
        this.endTime = endTime;
    }

    private String scheduleName;
    private String guilderNames;
    
    public String getScheduleName() {
        return scheduleName;
    }

    
    public void setScheduleName( String scheduleName ) {
        this.scheduleName = scheduleName;
    }

    
    public String getGuilderNames() {
        return guilderNames;
    }

    private String guilderIds;
    
    
    public String getGuilderIds() {
        return guilderIds;
    }


    
    public void setGuilderIds( String guilderIds ) {
        this.guilderIds = guilderIds;
    }


    public void setGuilderNames( String guilderNames ) {
        this.guilderNames = guilderNames;
    }
}