package com.tour.model;

import java.util.Date;

public class TmHotel {

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column tm_hotel.id
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    private Integer id;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column tm_hotel.name
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    private String name;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column tm_hotel.region_id
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    private Integer regionId;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column tm_hotel.star
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    private Integer star;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column tm_hotel.create_time
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    private Date createTime;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column tm_hotel.create_user_id
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    private Integer createUserId;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column tm_hotel.update_time
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    private Date updateTime;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column tm_hotel.update_user_id
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    private Integer updateUserId;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column tm_hotel.is_del
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    private String isDel;

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column tm_hotel.id
     * @return  the value of tm_hotel.id
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column tm_hotel.id
     * @param id  the value for tm_hotel.id
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public void setId( Integer id ) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column tm_hotel.name
     * @return  the value of tm_hotel.name
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column tm_hotel.name
     * @param name  the value for tm_hotel.name
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public void setName( String name ) {
        this.name = name;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column tm_hotel.region_id
     * @return  the value of tm_hotel.region_id
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public Integer getRegionId() {
        return regionId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column tm_hotel.region_id
     * @param regionId  the value for tm_hotel.region_id
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public void setRegionId( Integer regionId ) {
        this.regionId = regionId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column tm_hotel.star
     * @return  the value of tm_hotel.star
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public Integer getStar() {
        return star;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column tm_hotel.star
     * @param star  the value for tm_hotel.star
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public void setStar( Integer star ) {
        this.star = star;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column tm_hotel.create_time
     * @return  the value of tm_hotel.create_time
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column tm_hotel.create_time
     * @param createTime  the value for tm_hotel.create_time
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public void setCreateTime( Date createTime ) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column tm_hotel.create_user_id
     * @return  the value of tm_hotel.create_user_id
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public Integer getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column tm_hotel.create_user_id
     * @param createUserId  the value for tm_hotel.create_user_id
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public void setCreateUserId( Integer createUserId ) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column tm_hotel.update_time
     * @return  the value of tm_hotel.update_time
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column tm_hotel.update_time
     * @param updateTime  the value for tm_hotel.update_time
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public void setUpdateTime( Date updateTime ) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column tm_hotel.update_user_id
     * @return  the value of tm_hotel.update_user_id
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public Integer getUpdateUserId() {
        return updateUserId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column tm_hotel.update_user_id
     * @param updateUserId  the value for tm_hotel.update_user_id
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public void setUpdateUserId( Integer updateUserId ) {
        this.updateUserId = updateUserId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column tm_hotel.is_del
     * @return  the value of tm_hotel.is_del
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public String getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column tm_hotel.is_del
     * @param isDel  the value for tm_hotel.is_del
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public void setIsDel( String isDel ) {
        this.isDel = isDel;
    }
}