package com.tour.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Map;

public class TmInfoExample {
    
    protected int limitStart = 0;
    protected int limitEnd = 20;
    
    public int getLimitStart() {
        return limitStart;
    }

    
    public void setLimitStart( int limitStart ) {
        this.limitStart = limitStart;
    }

    
    public int getLimitEnd() {
        return limitEnd;
    }

    
    public void setLimitEnd( int limitEnd ) {
        this.limitEnd = limitEnd;
    }
    
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database table tm_info
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    protected String orderByClause;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database table tm_info
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    protected List oredCriteria;

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tm_info
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public TmInfoExample() {
        oredCriteria = new ArrayList();
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tm_info
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    protected TmInfoExample( TmInfoExample example ) {
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tm_info
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public void setOrderByClause( String orderByClause ) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tm_info
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tm_info
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public List getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tm_info
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public void or( Criteria criteria ) {
        oredCriteria.add( criteria );
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tm_info
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add( criteria );
        }
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tm_info
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tm_info
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public void clear() {
        oredCriteria.clear();
    }

    /**
     * This class was generated by Apache iBATIS ibator. This class corresponds to the database table tm_info
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public static class Criteria {
        
        protected List criteriaWithoutValue;
        protected List criteriaWithSingleValue;
        protected List criteriaWithListValue;
        protected List criteriaWithBetweenValue;
        
        protected Criteria() {
            super();
            criteriaWithoutValue = new ArrayList();
            criteriaWithSingleValue = new ArrayList();
            criteriaWithListValue = new ArrayList();
            criteriaWithBetweenValue = new ArrayList();
        }
        
        public boolean isValid() {
            return criteriaWithoutValue.size() > 0 || criteriaWithSingleValue.size() > 0
                    || criteriaWithListValue.size() > 0 || criteriaWithBetweenValue.size() > 0;
        }
        
        public List getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }
        
        public List getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }
        
        public List getCriteriaWithListValue() {
            return criteriaWithListValue;
        }
        
        public List getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }
        
        protected void addCriterion( String condition ) {
            if (condition == null) {
                throw new RuntimeException( "Value for condition cannot be null" );
            }
            criteriaWithoutValue.add( condition );
        }
        
        protected void addCriterion( String condition, Object value, String property ) {
            if (value == null) {
                throw new RuntimeException( "Value for " + property + " cannot be null" );
            }
            Map map = new HashMap();
            map.put( "condition", condition );
            map.put( "value", value );
            criteriaWithSingleValue.add( map );
        }
        
        protected void addCriterion( String condition, List values, String property ) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException( "Value list for " + property
                        + " cannot be null or empty" );
            }
            Map map = new HashMap();
            map.put( "condition", condition );
            map.put( "values", values );
            criteriaWithListValue.add( map );
        }
        
        protected void addCriterion( String condition, Object value1, Object value2, String property ) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException( "Between values for " + property + " cannot be null" );
            }
            List list = new ArrayList();
            list.add( value1 );
            list.add( value2 );
            Map map = new HashMap();
            map.put( "condition", condition );
            map.put( "values", list );
            criteriaWithBetweenValue.add( map );
        }
        
        protected void addCriterionForJDBCDate( String condition, Date value, String property ) {
            addCriterion( condition, new java.sql.Date( value.getTime() ), property );
        }
        
        protected void addCriterionForJDBCDate( String condition, List values, String property ) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException( "Value list for " + property
                        + " cannot be null or empty" );
            }
            List dateList = new ArrayList();
            Iterator iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add( new java.sql.Date( ((Date) iter.next()).getTime() ) );
            }
            addCriterion( condition, dateList, property );
        }
        
        protected void addCriterionForJDBCDate( String condition, Date value1, Date value2,
                String property ) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException( "Between values for " + property + " cannot be null" );
            }
            addCriterion( condition, new java.sql.Date( value1.getTime() ), new java.sql.Date(
                    value2.getTime() ), property );
        }
        
        public Criteria andIdIsNull() {
            addCriterion( "id is null" );
            return this;
        }
        
        public Criteria andIdIsNotNull() {
            addCriterion( "id is not null" );
            return this;
        }
        
        public Criteria andIdEqualTo( Integer value ) {
            addCriterion( "id =", value, "id" );
            return this;
        }
        
        public Criteria andIdNotEqualTo( Integer value ) {
            addCriterion( "id <>", value, "id" );
            return this;
        }
        
        public Criteria andIdGreaterThan( Integer value ) {
            addCriterion( "id >", value, "id" );
            return this;
        }
        
        public Criteria andIdGreaterThanOrEqualTo( Integer value ) {
            addCriterion( "id >=", value, "id" );
            return this;
        }
        
        public Criteria andIdLessThan( Integer value ) {
            addCriterion( "id <", value, "id" );
            return this;
        }
        
        public Criteria andIdLessThanOrEqualTo( Integer value ) {
            addCriterion( "id <=", value, "id" );
            return this;
        }
        
        public Criteria andIdIn( List values ) {
            addCriterion( "id in", values, "id" );
            return this;
        }
        
        public Criteria andIdNotIn( List values ) {
            addCriterion( "id not in", values, "id" );
            return this;
        }
        
        public Criteria andIdBetween( Integer value1, Integer value2 ) {
            addCriterion( "id between", value1, value2, "id" );
            return this;
        }
        
        public Criteria andIdNotBetween( Integer value1, Integer value2 ) {
            addCriterion( "id not between", value1, value2, "id" );
            return this;
        }
        
        public Criteria andTitleIsNull() {
            addCriterion( "title is null" );
            return this;
        }
        
        public Criteria andTitleIsNotNull() {
            addCriterion( "title is not null" );
            return this;
        }
        
        public Criteria andTitleEqualTo( String value ) {
            addCriterion( "title =", value, "title" );
            return this;
        }
        
        public Criteria andTitleNotEqualTo( String value ) {
            addCriterion( "title <>", value, "title" );
            return this;
        }
        
        public Criteria andTitleGreaterThan( String value ) {
            addCriterion( "title >", value, "title" );
            return this;
        }
        
        public Criteria andTitleGreaterThanOrEqualTo( String value ) {
            addCriterion( "title >=", value, "title" );
            return this;
        }
        
        public Criteria andTitleLessThan( String value ) {
            addCriterion( "title <", value, "title" );
            return this;
        }
        
        public Criteria andTitleLessThanOrEqualTo( String value ) {
            addCriterion( "title <=", value, "title" );
            return this;
        }
        
        public Criteria andTitleLike( String value ) {
            addCriterion( "title like", value, "title" );
            return this;
        }
        
        public Criteria andTitleNotLike( String value ) {
            addCriterion( "title not like", value, "title" );
            return this;
        }
        
        public Criteria andTitleIn( List values ) {
            addCriterion( "title in", values, "title" );
            return this;
        }
        
        public Criteria andTitleNotIn( List values ) {
            addCriterion( "title not in", values, "title" );
            return this;
        }
        
        public Criteria andTitleBetween( String value1, String value2 ) {
            addCriterion( "title between", value1, value2, "title" );
            return this;
        }
        
        public Criteria andTitleNotBetween( String value1, String value2 ) {
            addCriterion( "title not between", value1, value2, "title" );
            return this;
        }
        
        public Criteria andContentIsNull() {
            addCriterion( "content is null" );
            return this;
        }
        
        public Criteria andContentIsNotNull() {
            addCriterion( "content is not null" );
            return this;
        }
        
        public Criteria andContentEqualTo( String value ) {
            addCriterion( "content =", value, "content" );
            return this;
        }
        
        public Criteria andContentNotEqualTo( String value ) {
            addCriterion( "content <>", value, "content" );
            return this;
        }
        
        public Criteria andContentGreaterThan( String value ) {
            addCriterion( "content >", value, "content" );
            return this;
        }
        
        public Criteria andContentGreaterThanOrEqualTo( String value ) {
            addCriterion( "content >=", value, "content" );
            return this;
        }
        
        public Criteria andContentLessThan( String value ) {
            addCriterion( "content <", value, "content" );
            return this;
        }
        
        public Criteria andContentLessThanOrEqualTo( String value ) {
            addCriterion( "content <=", value, "content" );
            return this;
        }
        
        public Criteria andContentLike( String value ) {
            addCriterion( "content like", value, "content" );
            return this;
        }
        
        public Criteria andContentNotLike( String value ) {
            addCriterion( "content not like", value, "content" );
            return this;
        }
        
        public Criteria andContentIn( List values ) {
            addCriterion( "content in", values, "content" );
            return this;
        }
        
        public Criteria andContentNotIn( List values ) {
            addCriterion( "content not in", values, "content" );
            return this;
        }
        
        public Criteria andContentBetween( String value1, String value2 ) {
            addCriterion( "content between", value1, value2, "content" );
            return this;
        }
        
        public Criteria andContentNotBetween( String value1, String value2 ) {
            addCriterion( "content not between", value1, value2, "content" );
            return this;
        }
        
        public Criteria andAuthorIsNull() {
            addCriterion( "author is null" );
            return this;
        }
        
        public Criteria andAuthorIsNotNull() {
            addCriterion( "author is not null" );
            return this;
        }
        
        public Criteria andAuthorEqualTo( String value ) {
            addCriterion( "author =", value, "author" );
            return this;
        }
        
        public Criteria andAuthorNotEqualTo( String value ) {
            addCriterion( "author <>", value, "author" );
            return this;
        }
        
        public Criteria andAuthorGreaterThan( String value ) {
            addCriterion( "author >", value, "author" );
            return this;
        }
        
        public Criteria andAuthorGreaterThanOrEqualTo( String value ) {
            addCriterion( "author >=", value, "author" );
            return this;
        }
        
        public Criteria andAuthorLessThan( String value ) {
            addCriterion( "author <", value, "author" );
            return this;
        }
        
        public Criteria andAuthorLessThanOrEqualTo( String value ) {
            addCriterion( "author <=", value, "author" );
            return this;
        }
        
        public Criteria andAuthorLike( String value ) {
            addCriterion( "author like", value, "author" );
            return this;
        }
        
        public Criteria andAuthorNotLike( String value ) {
            addCriterion( "author not like", value, "author" );
            return this;
        }
        
        public Criteria andAuthorIn( List values ) {
            addCriterion( "author in", values, "author" );
            return this;
        }
        
        public Criteria andAuthorNotIn( List values ) {
            addCriterion( "author not in", values, "author" );
            return this;
        }
        
        public Criteria andAuthorBetween( String value1, String value2 ) {
            addCriterion( "author between", value1, value2, "author" );
            return this;
        }
        
        public Criteria andAuthorNotBetween( String value1, String value2 ) {
            addCriterion( "author not between", value1, value2, "author" );
            return this;
        }
        
        public Criteria andCreateTimeIsNull() {
            addCriterion( "create_time is null" );
            return this;
        }
        
        public Criteria andCreateTimeIsNotNull() {
            addCriterion( "create_time is not null" );
            return this;
        }
        
        public Criteria andCreateTimeEqualTo( Date value ) {
            addCriterionForJDBCDate( "create_time =", value, "createTime" );
            return this;
        }
        
        public Criteria andCreateTimeNotEqualTo( Date value ) {
            addCriterionForJDBCDate( "create_time <>", value, "createTime" );
            return this;
        }
        
        public Criteria andCreateTimeGreaterThan( Date value ) {
            addCriterionForJDBCDate( "create_time >", value, "createTime" );
            return this;
        }
        
        public Criteria andCreateTimeGreaterThanOrEqualTo( Date value ) {
            addCriterionForJDBCDate( "create_time >=", value, "createTime" );
            return this;
        }
        
        public Criteria andCreateTimeLessThan( Date value ) {
            addCriterionForJDBCDate( "create_time <", value, "createTime" );
            return this;
        }
        
        public Criteria andCreateTimeLessThanOrEqualTo( Date value ) {
            addCriterionForJDBCDate( "create_time <=", value, "createTime" );
            return this;
        }
        
        public Criteria andCreateTimeIn( List values ) {
            addCriterionForJDBCDate( "create_time in", values, "createTime" );
            return this;
        }
        
        public Criteria andCreateTimeNotIn( List values ) {
            addCriterionForJDBCDate( "create_time not in", values, "createTime" );
            return this;
        }
        
        public Criteria andCreateTimeBetween( Date value1, Date value2 ) {
            addCriterionForJDBCDate( "create_time between", value1, value2, "createTime" );
            return this;
        }
        
        public Criteria andCreateTimeNotBetween( Date value1, Date value2 ) {
            addCriterionForJDBCDate( "create_time not between", value1, value2, "createTime" );
            return this;
        }
        
        public Criteria andCreateUserIdIsNull() {
            addCriterion( "create_user_id is null" );
            return this;
        }
        
        public Criteria andCreateUserIdIsNotNull() {
            addCriterion( "create_user_id is not null" );
            return this;
        }
        
        public Criteria andCreateUserIdEqualTo( Integer value ) {
            addCriterion( "create_user_id =", value, "createUserId" );
            return this;
        }
        
        public Criteria andCreateUserIdNotEqualTo( Integer value ) {
            addCriterion( "create_user_id <>", value, "createUserId" );
            return this;
        }
        
        public Criteria andCreateUserIdGreaterThan( Integer value ) {
            addCriterion( "create_user_id >", value, "createUserId" );
            return this;
        }
        
        public Criteria andCreateUserIdGreaterThanOrEqualTo( Integer value ) {
            addCriterion( "create_user_id >=", value, "createUserId" );
            return this;
        }
        
        public Criteria andCreateUserIdLessThan( Integer value ) {
            addCriterion( "create_user_id <", value, "createUserId" );
            return this;
        }
        
        public Criteria andCreateUserIdLessThanOrEqualTo( Integer value ) {
            addCriterion( "create_user_id <=", value, "createUserId" );
            return this;
        }
        
        public Criteria andCreateUserIdIn( List values ) {
            addCriterion( "create_user_id in", values, "createUserId" );
            return this;
        }
        
        public Criteria andCreateUserIdNotIn( List values ) {
            addCriterion( "create_user_id not in", values, "createUserId" );
            return this;
        }
        
        public Criteria andCreateUserIdBetween( Integer value1, Integer value2 ) {
            addCriterion( "create_user_id between", value1, value2, "createUserId" );
            return this;
        }
        
        public Criteria andCreateUserIdNotBetween( Integer value1, Integer value2 ) {
            addCriterion( "create_user_id not between", value1, value2, "createUserId" );
            return this;
        }
        
        public Criteria andUpdateTimeIsNull() {
            addCriterion( "update_time is null" );
            return this;
        }
        
        public Criteria andUpdateTimeIsNotNull() {
            addCriterion( "update_time is not null" );
            return this;
        }
        
        public Criteria andUpdateTimeEqualTo( Date value ) {
            addCriterionForJDBCDate( "update_time =", value, "updateTime" );
            return this;
        }
        
        public Criteria andUpdateTimeNotEqualTo( Date value ) {
            addCriterionForJDBCDate( "update_time <>", value, "updateTime" );
            return this;
        }
        
        public Criteria andUpdateTimeGreaterThan( Date value ) {
            addCriterionForJDBCDate( "update_time >", value, "updateTime" );
            return this;
        }
        
        public Criteria andUpdateTimeGreaterThanOrEqualTo( Date value ) {
            addCriterionForJDBCDate( "update_time >=", value, "updateTime" );
            return this;
        }
        
        public Criteria andUpdateTimeLessThan( Date value ) {
            addCriterionForJDBCDate( "update_time <", value, "updateTime" );
            return this;
        }
        
        public Criteria andUpdateTimeLessThanOrEqualTo( Date value ) {
            addCriterionForJDBCDate( "update_time <=", value, "updateTime" );
            return this;
        }
        
        public Criteria andUpdateTimeIn( List values ) {
            addCriterionForJDBCDate( "update_time in", values, "updateTime" );
            return this;
        }
        
        public Criteria andUpdateTimeNotIn( List values ) {
            addCriterionForJDBCDate( "update_time not in", values, "updateTime" );
            return this;
        }
        
        public Criteria andUpdateTimeBetween( Date value1, Date value2 ) {
            addCriterionForJDBCDate( "update_time between", value1, value2, "updateTime" );
            return this;
        }
        
        public Criteria andUpdateTimeNotBetween( Date value1, Date value2 ) {
            addCriterionForJDBCDate( "update_time not between", value1, value2, "updateTime" );
            return this;
        }
        
        public Criteria andUpdateUserIdIsNull() {
            addCriterion( "update_user_id is null" );
            return this;
        }
        
        public Criteria andUpdateUserIdIsNotNull() {
            addCriterion( "update_user_id is not null" );
            return this;
        }
        
        public Criteria andUpdateUserIdEqualTo( Integer value ) {
            addCriterion( "update_user_id =", value, "updateUserId" );
            return this;
        }
        
        public Criteria andUpdateUserIdNotEqualTo( Integer value ) {
            addCriterion( "update_user_id <>", value, "updateUserId" );
            return this;
        }
        
        public Criteria andUpdateUserIdGreaterThan( Integer value ) {
            addCriterion( "update_user_id >", value, "updateUserId" );
            return this;
        }
        
        public Criteria andUpdateUserIdGreaterThanOrEqualTo( Integer value ) {
            addCriterion( "update_user_id >=", value, "updateUserId" );
            return this;
        }
        
        public Criteria andUpdateUserIdLessThan( Integer value ) {
            addCriterion( "update_user_id <", value, "updateUserId" );
            return this;
        }
        
        public Criteria andUpdateUserIdLessThanOrEqualTo( Integer value ) {
            addCriterion( "update_user_id <=", value, "updateUserId" );
            return this;
        }
        
        public Criteria andUpdateUserIdIn( List values ) {
            addCriterion( "update_user_id in", values, "updateUserId" );
            return this;
        }
        
        public Criteria andUpdateUserIdNotIn( List values ) {
            addCriterion( "update_user_id not in", values, "updateUserId" );
            return this;
        }
        
        public Criteria andUpdateUserIdBetween( Integer value1, Integer value2 ) {
            addCriterion( "update_user_id between", value1, value2, "updateUserId" );
            return this;
        }
        
        public Criteria andUpdateUserIdNotBetween( Integer value1, Integer value2 ) {
            addCriterion( "update_user_id not between", value1, value2, "updateUserId" );
            return this;
        }
        
        public Criteria andPicUrlIsNull() {
            addCriterion( "pic_url is null" );
            return this;
        }
        
        public Criteria andPicUrlIsNotNull() {
            addCriterion( "pic_url is not null" );
            return this;
        }
        
        public Criteria andPicUrlEqualTo( String value ) {
            addCriterion( "pic_url =", value, "picUrl" );
            return this;
        }
        
        public Criteria andPicUrlNotEqualTo( String value ) {
            addCriterion( "pic_url <>", value, "picUrl" );
            return this;
        }
        
        public Criteria andPicUrlGreaterThan( String value ) {
            addCriterion( "pic_url >", value, "picUrl" );
            return this;
        }
        
        public Criteria andPicUrlGreaterThanOrEqualTo( String value ) {
            addCriterion( "pic_url >=", value, "picUrl" );
            return this;
        }
        
        public Criteria andPicUrlLessThan( String value ) {
            addCriterion( "pic_url <", value, "picUrl" );
            return this;
        }
        
        public Criteria andPicUrlLessThanOrEqualTo( String value ) {
            addCriterion( "pic_url <=", value, "picUrl" );
            return this;
        }
        
        public Criteria andPicUrlLike( String value ) {
            addCriterion( "pic_url like", value, "picUrl" );
            return this;
        }
        
        public Criteria andPicUrlNotLike( String value ) {
            addCriterion( "pic_url not like", value, "picUrl" );
            return this;
        }
        
        public Criteria andPicUrlIn( List values ) {
            addCriterion( "pic_url in", values, "picUrl" );
            return this;
        }
        
        public Criteria andPicUrlNotIn( List values ) {
            addCriterion( "pic_url not in", values, "picUrl" );
            return this;
        }
        
        public Criteria andPicUrlBetween( String value1, String value2 ) {
            addCriterion( "pic_url between", value1, value2, "picUrl" );
            return this;
        }
        
        public Criteria andPicUrlNotBetween( String value1, String value2 ) {
            addCriterion( "pic_url not between", value1, value2, "picUrl" );
            return this;
        }
        
        public Criteria andTypeIsNull() {
            addCriterion( "type is null" );
            return this;
        }
        
        public Criteria andTypeIsNotNull() {
            addCriterion( "type is not null" );
            return this;
        }
        
        public Criteria andTypeEqualTo( Integer value ) {
            addCriterion( "type =", value, "type" );
            return this;
        }
        
        public Criteria andTypeNotEqualTo( Integer value ) {
            addCriterion( "type <>", value, "type" );
            return this;
        }
        
        public Criteria andTypeGreaterThan( Integer value ) {
            addCriterion( "type >", value, "type" );
            return this;
        }
        
        public Criteria andTypeGreaterThanOrEqualTo( Integer value ) {
            addCriterion( "type >=", value, "type" );
            return this;
        }
        
        public Criteria andTypeLessThan( Integer value ) {
            addCriterion( "type <", value, "type" );
            return this;
        }
        
        public Criteria andTypeLessThanOrEqualTo( Integer value ) {
            addCriterion( "type <=", value, "type" );
            return this;
        }
        
        public Criteria andTypeIn( List values ) {
            addCriterion( "type in", values, "type" );
            return this;
        }
        
        public Criteria andTypeNotIn( List values ) {
            addCriterion( "type not in", values, "type" );
            return this;
        }
        
        public Criteria andTypeBetween( Integer value1, Integer value2 ) {
            addCriterion( "type between", value1, value2, "type" );
            return this;
        }
        
        public Criteria andTypeNotBetween( Integer value1, Integer value2 ) {
            addCriterion( "type not between", value1, value2, "type" );
            return this;
        }
        
        public Criteria andIsDelIsNull() {
            addCriterion( "is_del is null" );
            return this;
        }
        
        public Criteria andIsDelIsNotNull() {
            addCriterion( "is_del is not null" );
            return this;
        }
        
        public Criteria andIsDelEqualTo( String value ) {
            addCriterion( "is_del =", value, "isDel" );
            return this;
        }
        
        public Criteria andIsDelNotEqualTo( String value ) {
            addCriterion( "is_del <>", value, "isDel" );
            return this;
        }
        
        public Criteria andIsDelGreaterThan( String value ) {
            addCriterion( "is_del >", value, "isDel" );
            return this;
        }
        
        public Criteria andIsDelGreaterThanOrEqualTo( String value ) {
            addCriterion( "is_del >=", value, "isDel" );
            return this;
        }
        
        public Criteria andIsDelLessThan( String value ) {
            addCriterion( "is_del <", value, "isDel" );
            return this;
        }
        
        public Criteria andIsDelLessThanOrEqualTo( String value ) {
            addCriterion( "is_del <=", value, "isDel" );
            return this;
        }
        
        public Criteria andIsDelLike( String value ) {
            addCriterion( "is_del like", value, "isDel" );
            return this;
        }
        
        public Criteria andIsDelNotLike( String value ) {
            addCriterion( "is_del not like", value, "isDel" );
            return this;
        }
        
        public Criteria andIsDelIn( List values ) {
            addCriterion( "is_del in", values, "isDel" );
            return this;
        }
        
        public Criteria andIsDelNotIn( List values ) {
            addCriterion( "is_del not in", values, "isDel" );
            return this;
        }
        
        public Criteria andIsDelBetween( String value1, String value2 ) {
            addCriterion( "is_del between", value1, value2, "isDel" );
            return this;
        }
        
        public Criteria andIsDelNotBetween( String value1, String value2 ) {
            addCriterion( "is_del not between", value1, value2, "isDel" );
            return this;
        }
    }
}