package com.tour.model;

import java.util.Date;

public class TmInfo {

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column tm_info.id
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    private Integer id;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column tm_info.title
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    private String title;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column tm_info.content
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    private String content;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column tm_info.author
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    private String author;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column tm_info.create_time
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    private Date createTime;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column tm_info.create_user_id
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    private Integer createUserId;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column tm_info.update_time
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    private Date updateTime;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column tm_info.update_user_id
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    private Integer updateUserId;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column tm_info.pic_url
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    private String picUrl;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column tm_info.type
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    private Integer type;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column tm_info.is_del
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    private String isDel;

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column tm_info.id
     * @return  the value of tm_info.id
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column tm_info.id
     * @param id  the value for tm_info.id
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public void setId( Integer id ) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column tm_info.title
     * @return  the value of tm_info.title
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column tm_info.title
     * @param title  the value for tm_info.title
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public void setTitle( String title ) {
        this.title = title;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column tm_info.content
     * @return  the value of tm_info.content
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column tm_info.content
     * @param content  the value for tm_info.content
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public void setContent( String content ) {
        this.content = content;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column tm_info.author
     * @return  the value of tm_info.author
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public String getAuthor() {
        return author;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column tm_info.author
     * @param author  the value for tm_info.author
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public void setAuthor( String author ) {
        this.author = author;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column tm_info.create_time
     * @return  the value of tm_info.create_time
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column tm_info.create_time
     * @param createTime  the value for tm_info.create_time
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public void setCreateTime( Date createTime ) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column tm_info.create_user_id
     * @return  the value of tm_info.create_user_id
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public Integer getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column tm_info.create_user_id
     * @param createUserId  the value for tm_info.create_user_id
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public void setCreateUserId( Integer createUserId ) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column tm_info.update_time
     * @return  the value of tm_info.update_time
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column tm_info.update_time
     * @param updateTime  the value for tm_info.update_time
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public void setUpdateTime( Date updateTime ) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column tm_info.update_user_id
     * @return  the value of tm_info.update_user_id
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public Integer getUpdateUserId() {
        return updateUserId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column tm_info.update_user_id
     * @param updateUserId  the value for tm_info.update_user_id
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public void setUpdateUserId( Integer updateUserId ) {
        this.updateUserId = updateUserId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column tm_info.pic_url
     * @return  the value of tm_info.pic_url
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public String getPicUrl() {
        return picUrl;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column tm_info.pic_url
     * @param picUrl  the value for tm_info.pic_url
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public void setPicUrl( String picUrl ) {
        this.picUrl = picUrl;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column tm_info.type
     * @return  the value of tm_info.type
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column tm_info.type
     * @param type  the value for tm_info.type
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public void setType( Integer type ) {
        this.type = type;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column tm_info.is_del
     * @return  the value of tm_info.is_del
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public String getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column tm_info.is_del
     * @param isDel  the value for tm_info.is_del
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public void setIsDel( String isDel ) {
        this.isDel = isDel;
    }
}