package com.tour.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Map;

public class TmOrderExample {
    
    protected int limitStart = 0;
    protected int limitEnd = 20;
    
    public int getLimitStart() {
        return limitStart;
    }

    
    public void setLimitStart( int limitStart ) {
        this.limitStart = limitStart;
    }

    
    public int getLimitEnd() {
        return limitEnd;
    }

    
    public void setLimitEnd( int limitEnd ) {
        this.limitEnd = limitEnd;
    }
    
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database table tm_order
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    protected String orderByClause;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database table tm_order
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    protected List oredCriteria;

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tm_order
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public TmOrderExample() {
        oredCriteria = new ArrayList();
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tm_order
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    protected TmOrderExample( TmOrderExample example ) {
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tm_order
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public void setOrderByClause( String orderByClause ) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tm_order
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tm_order
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public List getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tm_order
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public void or( Criteria criteria ) {
        oredCriteria.add( criteria );
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tm_order
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add( criteria );
        }
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tm_order
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tm_order
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public void clear() {
        oredCriteria.clear();
    }

    /**
     * This class was generated by Apache iBATIS ibator. This class corresponds to the database table tm_order
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public static class Criteria {
        
        protected List criteriaWithoutValue;
        protected List criteriaWithSingleValue;
        protected List criteriaWithListValue;
        protected List criteriaWithBetweenValue;
        
        protected Criteria() {
            super();
            criteriaWithoutValue = new ArrayList();
            criteriaWithSingleValue = new ArrayList();
            criteriaWithListValue = new ArrayList();
            criteriaWithBetweenValue = new ArrayList();
        }
        
        public boolean isValid() {
            return criteriaWithoutValue.size() > 0 || criteriaWithSingleValue.size() > 0
                    || criteriaWithListValue.size() > 0 || criteriaWithBetweenValue.size() > 0;
        }
        
        public List getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }
        
        public List getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }
        
        public List getCriteriaWithListValue() {
            return criteriaWithListValue;
        }
        
        public List getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }
        
        protected void addCriterion( String condition ) {
            if (condition == null) {
                throw new RuntimeException( "Value for condition cannot be null" );
            }
            criteriaWithoutValue.add( condition );
        }
        
        protected void addCriterion( String condition, Object value, String property ) {
            if (value == null) {
                throw new RuntimeException( "Value for " + property + " cannot be null" );
            }
            Map map = new HashMap();
            map.put( "condition", condition );
            map.put( "value", value );
            criteriaWithSingleValue.add( map );
        }
        
        protected void addCriterion( String condition, List values, String property ) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException( "Value list for " + property
                        + " cannot be null or empty" );
            }
            Map map = new HashMap();
            map.put( "condition", condition );
            map.put( "values", values );
            criteriaWithListValue.add( map );
        }
        
        protected void addCriterion( String condition, Object value1, Object value2, String property ) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException( "Between values for " + property + " cannot be null" );
            }
            List list = new ArrayList();
            list.add( value1 );
            list.add( value2 );
            Map map = new HashMap();
            map.put( "condition", condition );
            map.put( "values", list );
            criteriaWithBetweenValue.add( map );
        }
        
        protected void addCriterionForJDBCDate( String condition, Date value, String property ) {
            addCriterion( condition, new java.sql.Date( value.getTime() ), property );
        }
        
        protected void addCriterionForJDBCDate( String condition, List values, String property ) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException( "Value list for " + property
                        + " cannot be null or empty" );
            }
            List dateList = new ArrayList();
            Iterator iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add( new java.sql.Date( ((Date) iter.next()).getTime() ) );
            }
            addCriterion( condition, dateList, property );
        }
        
        protected void addCriterionForJDBCDate( String condition, Date value1, Date value2,
                String property ) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException( "Between values for " + property + " cannot be null" );
            }
            addCriterion( condition, new java.sql.Date( value1.getTime() ), new java.sql.Date(
                    value2.getTime() ), property );
        }
        
        public Criteria andIdIsNull() {
            addCriterion( "id is null" );
            return this;
        }
        
        public Criteria andIdIsNotNull() {
            addCriterion( "id is not null" );
            return this;
        }
        
        public Criteria andIdEqualTo( Integer value ) {
            addCriterion( "id =", value, "id" );
            return this;
        }
        
        public Criteria andIdNotEqualTo( Integer value ) {
            addCriterion( "id <>", value, "id" );
            return this;
        }
        
        public Criteria andIdGreaterThan( Integer value ) {
            addCriterion( "id >", value, "id" );
            return this;
        }
        
        public Criteria andIdGreaterThanOrEqualTo( Integer value ) {
            addCriterion( "id >=", value, "id" );
            return this;
        }
        
        public Criteria andIdLessThan( Integer value ) {
            addCriterion( "id <", value, "id" );
            return this;
        }
        
        public Criteria andIdLessThanOrEqualTo( Integer value ) {
            addCriterion( "id <=", value, "id" );
            return this;
        }
        
        public Criteria andIdIn( List values ) {
            addCriterion( "id in", values, "id" );
            return this;
        }
        
        public Criteria andIdNotIn( List values ) {
            addCriterion( "id not in", values, "id" );
            return this;
        }
        
        public Criteria andIdBetween( Integer value1, Integer value2 ) {
            addCriterion( "id between", value1, value2, "id" );
            return this;
        }
        
        public Criteria andIdNotBetween( Integer value1, Integer value2 ) {
            addCriterion( "id not between", value1, value2, "id" );
            return this;
        }
        
        public Criteria andCustomIdIsNull() {
            addCriterion( "custom_id is null" );
            return this;
        }
        
        public Criteria andCustomIdIsNotNull() {
            addCriterion( "custom_id is not null" );
            return this;
        }
        
        public Criteria andCustomIdEqualTo( Integer value ) {
            addCriterion( "custom_id =", value, "customId" );
            return this;
        }
        
        public Criteria andCustomIdNotEqualTo( Integer value ) {
            addCriterion( "custom_id <>", value, "customId" );
            return this;
        }
        
        public Criteria andCustomIdGreaterThan( Integer value ) {
            addCriterion( "custom_id >", value, "customId" );
            return this;
        }
        
        public Criteria andCustomIdGreaterThanOrEqualTo( Integer value ) {
            addCriterion( "custom_id >=", value, "customId" );
            return this;
        }
        
        public Criteria andCustomIdLessThan( Integer value ) {
            addCriterion( "custom_id <", value, "customId" );
            return this;
        }
        
        public Criteria andCustomIdLessThanOrEqualTo( Integer value ) {
            addCriterion( "custom_id <=", value, "customId" );
            return this;
        }
        
        public Criteria andCustomIdIn( List values ) {
            addCriterion( "custom_id in", values, "customId" );
            return this;
        }
        
        public Criteria andCustomIdNotIn( List values ) {
            addCriterion( "custom_id not in", values, "customId" );
            return this;
        }
        
        public Criteria andCustomIdBetween( Integer value1, Integer value2 ) {
            addCriterion( "custom_id between", value1, value2, "customId" );
            return this;
        }
        
        public Criteria andCustomIdNotBetween( Integer value1, Integer value2 ) {
            addCriterion( "custom_id not between", value1, value2, "customId" );
            return this;
        }
        
        public Criteria andTotalPeopleIsNull() {
            addCriterion( "total_people is null" );
            return this;
        }
        
        public Criteria andTotalPeopleIsNotNull() {
            addCriterion( "total_people is not null" );
            return this;
        }
        
        public Criteria andTotalPeopleEqualTo( Integer value ) {
            addCriterion( "total_people =", value, "totalPeople" );
            return this;
        }
        
        public Criteria andTotalPeopleNotEqualTo( Integer value ) {
            addCriterion( "total_people <>", value, "totalPeople" );
            return this;
        }
        
        public Criteria andTotalPeopleGreaterThan( Integer value ) {
            addCriterion( "total_people >", value, "totalPeople" );
            return this;
        }
        
        public Criteria andTotalPeopleGreaterThanOrEqualTo( Integer value ) {
            addCriterion( "total_people >=", value, "totalPeople" );
            return this;
        }
        
        public Criteria andTotalPeopleLessThan( Integer value ) {
            addCriterion( "total_people <", value, "totalPeople" );
            return this;
        }
        
        public Criteria andTotalPeopleLessThanOrEqualTo( Integer value ) {
            addCriterion( "total_people <=", value, "totalPeople" );
            return this;
        }
        
        public Criteria andTotalPeopleIn( List values ) {
            addCriterion( "total_people in", values, "totalPeople" );
            return this;
        }
        
        public Criteria andTotalPeopleNotIn( List values ) {
            addCriterion( "total_people not in", values, "totalPeople" );
            return this;
        }
        
        public Criteria andTotalPeopleBetween( Integer value1, Integer value2 ) {
            addCriterion( "total_people between", value1, value2, "totalPeople" );
            return this;
        }
        
        public Criteria andTotalPeopleNotBetween( Integer value1, Integer value2 ) {
            addCriterion( "total_people not between", value1, value2, "totalPeople" );
            return this;
        }
        
        public Criteria andScheduleIdIsNull() {
            addCriterion( "schedule_id is null" );
            return this;
        }
        
        public Criteria andScheduleIdIsNotNull() {
            addCriterion( "schedule_id is not null" );
            return this;
        }
        
        public Criteria andScheduleIdEqualTo( Integer value ) {
            addCriterion( "schedule_id =", value, "scheduleId" );
            return this;
        }
        
        public Criteria andScheduleIdNotEqualTo( Integer value ) {
            addCriterion( "schedule_id <>", value, "scheduleId" );
            return this;
        }
        
        public Criteria andScheduleIdGreaterThan( Integer value ) {
            addCriterion( "schedule_id >", value, "scheduleId" );
            return this;
        }
        
        public Criteria andScheduleIdGreaterThanOrEqualTo( Integer value ) {
            addCriterion( "schedule_id >=", value, "scheduleId" );
            return this;
        }
        
        public Criteria andScheduleIdLessThan( Integer value ) {
            addCriterion( "schedule_id <", value, "scheduleId" );
            return this;
        }
        
        public Criteria andScheduleIdLessThanOrEqualTo( Integer value ) {
            addCriterion( "schedule_id <=", value, "scheduleId" );
            return this;
        }
        
        public Criteria andScheduleIdIn( List values ) {
            addCriterion( "schedule_id in", values, "scheduleId" );
            return this;
        }
        
        public Criteria andScheduleIdNotIn( List values ) {
            addCriterion( "schedule_id not in", values, "scheduleId" );
            return this;
        }
        
        public Criteria andScheduleIdBetween( Integer value1, Integer value2 ) {
            addCriterion( "schedule_id between", value1, value2, "scheduleId" );
            return this;
        }
        
        public Criteria andScheduleIdNotBetween( Integer value1, Integer value2 ) {
            addCriterion( "schedule_id not between", value1, value2, "scheduleId" );
            return this;
        }
        
        public Criteria andTotalPriceIsNull() {
            addCriterion( "total_price is null" );
            return this;
        }
        
        public Criteria andTotalPriceIsNotNull() {
            addCriterion( "total_price is not null" );
            return this;
        }
        
        public Criteria andTotalPriceEqualTo( Double value ) {
            addCriterion( "total_price =", value, "totalPrice" );
            return this;
        }
        
        public Criteria andTotalPriceNotEqualTo( Double value ) {
            addCriterion( "total_price <>", value, "totalPrice" );
            return this;
        }
        
        public Criteria andTotalPriceGreaterThan( Double value ) {
            addCriterion( "total_price >", value, "totalPrice" );
            return this;
        }
        
        public Criteria andTotalPriceGreaterThanOrEqualTo( Double value ) {
            addCriterion( "total_price >=", value, "totalPrice" );
            return this;
        }
        
        public Criteria andTotalPriceLessThan( Double value ) {
            addCriterion( "total_price <", value, "totalPrice" );
            return this;
        }
        
        public Criteria andTotalPriceLessThanOrEqualTo( Double value ) {
            addCriterion( "total_price <=", value, "totalPrice" );
            return this;
        }
        
        public Criteria andTotalPriceIn( List values ) {
            addCriterion( "total_price in", values, "totalPrice" );
            return this;
        }
        
        public Criteria andTotalPriceNotIn( List values ) {
            addCriterion( "total_price not in", values, "totalPrice" );
            return this;
        }
        
        public Criteria andTotalPriceBetween( Double value1, Double value2 ) {
            addCriterion( "total_price between", value1, value2, "totalPrice" );
            return this;
        }
        
        public Criteria andTotalPriceNotBetween( Double value1, Double value2 ) {
            addCriterion( "total_price not between", value1, value2, "totalPrice" );
            return this;
        }
        
        public Criteria andIsConfirmIsNull() {
            addCriterion( "is_confirm is null" );
            return this;
        }
        
        public Criteria andIsConfirmIsNotNull() {
            addCriterion( "is_confirm is not null" );
            return this;
        }
        
        public Criteria andIsConfirmEqualTo( Integer value ) {
            addCriterion( "is_confirm =", value, "isConfirm" );
            return this;
        }
        
        public Criteria andIsConfirmNotEqualTo( Integer value ) {
            addCriterion( "is_confirm <>", value, "isConfirm" );
            return this;
        }
        
        public Criteria andIsConfirmGreaterThan( Integer value ) {
            addCriterion( "is_confirm >", value, "isConfirm" );
            return this;
        }
        
        public Criteria andIsConfirmGreaterThanOrEqualTo( Integer value ) {
            addCriterion( "is_confirm >=", value, "isConfirm" );
            return this;
        }
        
        public Criteria andIsConfirmLessThan( Integer value ) {
            addCriterion( "is_confirm <", value, "isConfirm" );
            return this;
        }
        
        public Criteria andIsConfirmLessThanOrEqualTo( Integer value ) {
            addCriterion( "is_confirm <=", value, "isConfirm" );
            return this;
        }
        
        public Criteria andIsConfirmIn( List values ) {
            addCriterion( "is_confirm in", values, "isConfirm" );
            return this;
        }
        
        public Criteria andIsConfirmNotIn( List values ) {
            addCriterion( "is_confirm not in", values, "isConfirm" );
            return this;
        }
        
        public Criteria andIsConfirmBetween( Integer value1, Integer value2 ) {
            addCriterion( "is_confirm between", value1, value2, "isConfirm" );
            return this;
        }
        
        public Criteria andIsConfirmNotBetween( Integer value1, Integer value2 ) {
            addCriterion( "is_confirm not between", value1, value2, "isConfirm" );
            return this;
        }
        
        public Criteria andIsPayIsNull() {
            addCriterion( "is_pay is null" );
            return this;
        }
        
        public Criteria andIsPayIsNotNull() {
            addCriterion( "is_pay is not null" );
            return this;
        }
        
        public Criteria andIsPayEqualTo( Integer value ) {
            addCriterion( "is_pay =", value, "isPay" );
            return this;
        }
        
        public Criteria andIsPayNotEqualTo( Integer value ) {
            addCriterion( "is_pay <>", value, "isPay" );
            return this;
        }
        
        public Criteria andIsPayGreaterThan( Integer value ) {
            addCriterion( "is_pay >", value, "isPay" );
            return this;
        }
        
        public Criteria andIsPayGreaterThanOrEqualTo( Integer value ) {
            addCriterion( "is_pay >=", value, "isPay" );
            return this;
        }
        
        public Criteria andIsPayLessThan( Integer value ) {
            addCriterion( "is_pay <", value, "isPay" );
            return this;
        }
        
        public Criteria andIsPayLessThanOrEqualTo( Integer value ) {
            addCriterion( "is_pay <=", value, "isPay" );
            return this;
        }
        
        public Criteria andIsPayIn( List values ) {
            addCriterion( "is_pay in", values, "isPay" );
            return this;
        }
        
        public Criteria andIsPayNotIn( List values ) {
            addCriterion( "is_pay not in", values, "isPay" );
            return this;
        }
        
        public Criteria andIsPayBetween( Integer value1, Integer value2 ) {
            addCriterion( "is_pay between", value1, value2, "isPay" );
            return this;
        }
        
        public Criteria andIsPayNotBetween( Integer value1, Integer value2 ) {
            addCriterion( "is_pay not between", value1, value2, "isPay" );
            return this;
        }
        
        public Criteria andIsDelIsNull() {
            addCriterion( "is_del is null" );
            return this;
        }
        
        public Criteria andIsDelIsNotNull() {
            addCriterion( "is_del is not null" );
            return this;
        }
        
        public Criteria andIsDelEqualTo( String value ) {
            addCriterion( "is_del =", value, "isDel" );
            return this;
        }
        
        public Criteria andIsDelNotEqualTo( String value ) {
            addCriterion( "is_del <>", value, "isDel" );
            return this;
        }
        
        public Criteria andIsDelGreaterThan( String value ) {
            addCriterion( "is_del >", value, "isDel" );
            return this;
        }
        
        public Criteria andIsDelGreaterThanOrEqualTo( String value ) {
            addCriterion( "is_del >=", value, "isDel" );
            return this;
        }
        
        public Criteria andIsDelLessThan( String value ) {
            addCriterion( "is_del <", value, "isDel" );
            return this;
        }
        
        public Criteria andIsDelLessThanOrEqualTo( String value ) {
            addCriterion( "is_del <=", value, "isDel" );
            return this;
        }
        
        public Criteria andIsDelLike( String value ) {
            addCriterion( "is_del like", value, "isDel" );
            return this;
        }
        
        public Criteria andIsDelNotLike( String value ) {
            addCriterion( "is_del not like", value, "isDel" );
            return this;
        }
        
        public Criteria andIsDelIn( List values ) {
            addCriterion( "is_del in", values, "isDel" );
            return this;
        }
        
        public Criteria andIsDelNotIn( List values ) {
            addCriterion( "is_del not in", values, "isDel" );
            return this;
        }
        
        public Criteria andIsDelBetween( String value1, String value2 ) {
            addCriterion( "is_del between", value1, value2, "isDel" );
            return this;
        }
        
        public Criteria andIsDelNotBetween( String value1, String value2 ) {
            addCriterion( "is_del not between", value1, value2, "isDel" );
            return this;
        }
        
        public Criteria andCreateTimeIsNull() {
            addCriterion( "create_time is null" );
            return this;
        }
        
        public Criteria andCreateTimeIsNotNull() {
            addCriterion( "create_time is not null" );
            return this;
        }
        
        public Criteria andCreateTimeEqualTo( Date value ) {
            addCriterionForJDBCDate( "create_time =", value, "createTime" );
            return this;
        }
        
        public Criteria andCreateTimeNotEqualTo( Date value ) {
            addCriterionForJDBCDate( "create_time <>", value, "createTime" );
            return this;
        }
        
        public Criteria andCreateTimeGreaterThan( Date value ) {
            addCriterionForJDBCDate( "create_time >", value, "createTime" );
            return this;
        }
        
        public Criteria andCreateTimeGreaterThanOrEqualTo( Date value ) {
            addCriterionForJDBCDate( "create_time >=", value, "createTime" );
            return this;
        }
        
        public Criteria andCreateTimeLessThan( Date value ) {
            addCriterionForJDBCDate( "create_time <", value, "createTime" );
            return this;
        }
        
        public Criteria andCreateTimeLessThanOrEqualTo( Date value ) {
            addCriterionForJDBCDate( "create_time <=", value, "createTime" );
            return this;
        }
        
        public Criteria andCreateTimeIn( List values ) {
            addCriterionForJDBCDate( "create_time in", values, "createTime" );
            return this;
        }
        
        public Criteria andCreateTimeNotIn( List values ) {
            addCriterionForJDBCDate( "create_time not in", values, "createTime" );
            return this;
        }
        
        public Criteria andCreateTimeBetween( Date value1, Date value2 ) {
            addCriterionForJDBCDate( "create_time between", value1, value2, "createTime" );
            return this;
        }
        
        public Criteria andCreateTimeNotBetween( Date value1, Date value2 ) {
            addCriterionForJDBCDate( "create_time not between", value1, value2, "createTime" );
            return this;
        }
        
        public Criteria andCreateUserIdIsNull() {
            addCriterion( "create_user_id is null" );
            return this;
        }
        
        public Criteria andCreateUserIdIsNotNull() {
            addCriterion( "create_user_id is not null" );
            return this;
        }
        
        public Criteria andCreateUserIdEqualTo( Integer value ) {
            addCriterion( "create_user_id =", value, "createUserId" );
            return this;
        }
        
        public Criteria andCreateUserIdNotEqualTo( Integer value ) {
            addCriterion( "create_user_id <>", value, "createUserId" );
            return this;
        }
        
        public Criteria andCreateUserIdGreaterThan( Integer value ) {
            addCriterion( "create_user_id >", value, "createUserId" );
            return this;
        }
        
        public Criteria andCreateUserIdGreaterThanOrEqualTo( Integer value ) {
            addCriterion( "create_user_id >=", value, "createUserId" );
            return this;
        }
        
        public Criteria andCreateUserIdLessThan( Integer value ) {
            addCriterion( "create_user_id <", value, "createUserId" );
            return this;
        }
        
        public Criteria andCreateUserIdLessThanOrEqualTo( Integer value ) {
            addCriterion( "create_user_id <=", value, "createUserId" );
            return this;
        }
        
        public Criteria andCreateUserIdIn( List values ) {
            addCriterion( "create_user_id in", values, "createUserId" );
            return this;
        }
        
        public Criteria andCreateUserIdNotIn( List values ) {
            addCriterion( "create_user_id not in", values, "createUserId" );
            return this;
        }
        
        public Criteria andCreateUserIdBetween( Integer value1, Integer value2 ) {
            addCriterion( "create_user_id between", value1, value2, "createUserId" );
            return this;
        }
        
        public Criteria andCreateUserIdNotBetween( Integer value1, Integer value2 ) {
            addCriterion( "create_user_id not between", value1, value2, "createUserId" );
            return this;
        }
        
        public Criteria andUpdateTimeIsNull() {
            addCriterion( "update_time is null" );
            return this;
        }
        
        public Criteria andUpdateTimeIsNotNull() {
            addCriterion( "update_time is not null" );
            return this;
        }
        
        public Criteria andUpdateTimeEqualTo( Date value ) {
            addCriterionForJDBCDate( "update_time =", value, "updateTime" );
            return this;
        }
        
        public Criteria andUpdateTimeNotEqualTo( Date value ) {
            addCriterionForJDBCDate( "update_time <>", value, "updateTime" );
            return this;
        }
        
        public Criteria andUpdateTimeGreaterThan( Date value ) {
            addCriterionForJDBCDate( "update_time >", value, "updateTime" );
            return this;
        }
        
        public Criteria andUpdateTimeGreaterThanOrEqualTo( Date value ) {
            addCriterionForJDBCDate( "update_time >=", value, "updateTime" );
            return this;
        }
        
        public Criteria andUpdateTimeLessThan( Date value ) {
            addCriterionForJDBCDate( "update_time <", value, "updateTime" );
            return this;
        }
        
        public Criteria andUpdateTimeLessThanOrEqualTo( Date value ) {
            addCriterionForJDBCDate( "update_time <=", value, "updateTime" );
            return this;
        }
        
        public Criteria andUpdateTimeIn( List values ) {
            addCriterionForJDBCDate( "update_time in", values, "updateTime" );
            return this;
        }
        
        public Criteria andUpdateTimeNotIn( List values ) {
            addCriterionForJDBCDate( "update_time not in", values, "updateTime" );
            return this;
        }
        
        public Criteria andUpdateTimeBetween( Date value1, Date value2 ) {
            addCriterionForJDBCDate( "update_time between", value1, value2, "updateTime" );
            return this;
        }
        
        public Criteria andUpdateTimeNotBetween( Date value1, Date value2 ) {
            addCriterionForJDBCDate( "update_time not between", value1, value2, "updateTime" );
            return this;
        }
        
        public Criteria andUpdateUserIdIsNull() {
            addCriterion( "update_user_id is null" );
            return this;
        }
        
        public Criteria andUpdateUserIdIsNotNull() {
            addCriterion( "update_user_id is not null" );
            return this;
        }
        
        public Criteria andUpdateUserIdEqualTo( Long value ) {
            addCriterion( "update_user_id =", value, "updateUserId" );
            return this;
        }
        
        public Criteria andUpdateUserIdNotEqualTo( Long value ) {
            addCriterion( "update_user_id <>", value, "updateUserId" );
            return this;
        }
        
        public Criteria andUpdateUserIdGreaterThan( Long value ) {
            addCriterion( "update_user_id >", value, "updateUserId" );
            return this;
        }
        
        public Criteria andUpdateUserIdGreaterThanOrEqualTo( Long value ) {
            addCriterion( "update_user_id >=", value, "updateUserId" );
            return this;
        }
        
        public Criteria andUpdateUserIdLessThan( Long value ) {
            addCriterion( "update_user_id <", value, "updateUserId" );
            return this;
        }
        
        public Criteria andUpdateUserIdLessThanOrEqualTo( Long value ) {
            addCriterion( "update_user_id <=", value, "updateUserId" );
            return this;
        }
        
        public Criteria andUpdateUserIdIn( List values ) {
            addCriterion( "update_user_id in", values, "updateUserId" );
            return this;
        }
        
        public Criteria andUpdateUserIdNotIn( List values ) {
            addCriterion( "update_user_id not in", values, "updateUserId" );
            return this;
        }
        
        public Criteria andUpdateUserIdBetween( Long value1, Long value2 ) {
            addCriterion( "update_user_id between", value1, value2, "updateUserId" );
            return this;
        }
        
        public Criteria andUpdateUserIdNotBetween( Long value1, Long value2 ) {
            addCriterion( "update_user_id not between", value1, value2, "updateUserId" );
            return this;
        }
        
        public Criteria andOrderTypeIsNull() {
            addCriterion( "order_type is null" );
            return this;
        }
        
        public Criteria andOrderTypeIsNotNull() {
            addCriterion( "order_type is not null" );
            return this;
        }
        
        public Criteria andOrderTypeEqualTo( Integer value ) {
            addCriterion( "order_type =", value, "orderType" );
            return this;
        }
        
        public Criteria andOrderTypeNotEqualTo( Integer value ) {
            addCriterion( "order_type <>", value, "orderType" );
            return this;
        }
        
        public Criteria andOrderTypeGreaterThan( Integer value ) {
            addCriterion( "order_type >", value, "orderType" );
            return this;
        }
        
        public Criteria andOrderTypeGreaterThanOrEqualTo( Integer value ) {
            addCriterion( "order_type >=", value, "orderType" );
            return this;
        }
        
        public Criteria andOrderTypeLessThan( Integer value ) {
            addCriterion( "order_type <", value, "orderType" );
            return this;
        }
        
        public Criteria andOrderTypeLessThanOrEqualTo( Integer value ) {
            addCriterion( "order_type <=", value, "orderType" );
            return this;
        }
        
        public Criteria andOrderTypeIn( List values ) {
            addCriterion( "order_type in", values, "orderType" );
            return this;
        }
        
        public Criteria andOrderTypeNotIn( List values ) {
            addCriterion( "order_type not in", values, "orderType" );
            return this;
        }
        
        public Criteria andOrderTypeBetween( Integer value1, Integer value2 ) {
            addCriterion( "order_type between", value1, value2, "orderType" );
            return this;
        }
        
        public Criteria andOrderTypeNotBetween( Integer value1, Integer value2 ) {
            addCriterion( "order_type not between", value1, value2, "orderType" );
            return this;
        }
        
        public Criteria andOrderDescIsNull() {
            addCriterion( "order_desc is null" );
            return this;
        }
        
        public Criteria andOrderDescIsNotNull() {
            addCriterion( "order_desc is not null" );
            return this;
        }
        
        public Criteria andOrderDescEqualTo( String value ) {
            addCriterion( "order_desc =", value, "orderDesc" );
            return this;
        }
        
        public Criteria andOrderDescNotEqualTo( String value ) {
            addCriterion( "order_desc <>", value, "orderDesc" );
            return this;
        }
        
        public Criteria andOrderDescGreaterThan( String value ) {
            addCriterion( "order_desc >", value, "orderDesc" );
            return this;
        }
        
        public Criteria andOrderDescGreaterThanOrEqualTo( String value ) {
            addCriterion( "order_desc >=", value, "orderDesc" );
            return this;
        }
        
        public Criteria andOrderDescLessThan( String value ) {
            addCriterion( "order_desc <", value, "orderDesc" );
            return this;
        }
        
        public Criteria andOrderDescLessThanOrEqualTo( String value ) {
            addCriterion( "order_desc <=", value, "orderDesc" );
            return this;
        }
        
        public Criteria andOrderDescLike( String value ) {
            addCriterion( "order_desc like", value, "orderDesc" );
            return this;
        }
        
        public Criteria andOrderDescNotLike( String value ) {
            addCriterion( "order_desc not like", value, "orderDesc" );
            return this;
        }
        
        public Criteria andOrderDescIn( List values ) {
            addCriterion( "order_desc in", values, "orderDesc" );
            return this;
        }
        
        public Criteria andOrderDescNotIn( List values ) {
            addCriterion( "order_desc not in", values, "orderDesc" );
            return this;
        }
        
        public Criteria andOrderDescBetween( String value1, String value2 ) {
            addCriterion( "order_desc between", value1, value2, "orderDesc" );
            return this;
        }
        
        public Criteria andOrderDescNotBetween( String value1, String value2 ) {
            addCriterion( "order_desc not between", value1, value2, "orderDesc" );
            return this;
        }
    }
}