package com.tour.model;

import java.util.Date;

public class TmOrder {
    private String customName;
    private String scheduleName;
    
    
    public String getCustomName() {
        return customName;
    }

    
    public void setCustomName( String customName ) {
        this.customName = customName;
    }

    
    public String getScheduleName() {
        return scheduleName;
    }

    
    public void setScheduleName( String scheduleName ) {
        this.scheduleName = scheduleName;
    }

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column tm_order.id
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    private Integer id;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column tm_order.custom_id
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    private Integer customId;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column tm_order.total_people
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    private Integer totalPeople;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column tm_order.schedule_id
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    private Integer scheduleId;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column tm_order.total_price
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    private Double totalPrice;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column tm_order.is_confirm
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    private Integer isConfirm;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column tm_order.is_pay
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    private Integer isPay;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column tm_order.is_del
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    private String isDel;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column tm_order.create_time
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    private Date createTime;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column tm_order.create_user_id
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    private Integer createUserId;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column tm_order.update_time
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    private Date updateTime;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column tm_order.update_user_id
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    private Long updateUserId;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column tm_order.order_type
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    private Integer orderType;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column tm_order.order_desc
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    private String orderDesc;

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column tm_order.id
     * @return  the value of tm_order.id
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column tm_order.id
     * @param id  the value for tm_order.id
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public void setId( Integer id ) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column tm_order.custom_id
     * @return  the value of tm_order.custom_id
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public Integer getCustomId() {
        return customId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column tm_order.custom_id
     * @param customId  the value for tm_order.custom_id
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public void setCustomId( Integer customId ) {
        this.customId = customId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column tm_order.total_people
     * @return  the value of tm_order.total_people
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public Integer getTotalPeople() {
        return totalPeople;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column tm_order.total_people
     * @param totalPeople  the value for tm_order.total_people
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public void setTotalPeople( Integer totalPeople ) {
        this.totalPeople = totalPeople;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column tm_order.schedule_id
     * @return  the value of tm_order.schedule_id
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public Integer getScheduleId() {
        return scheduleId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column tm_order.schedule_id
     * @param scheduleId  the value for tm_order.schedule_id
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public void setScheduleId( Integer scheduleId ) {
        this.scheduleId = scheduleId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column tm_order.total_price
     * @return  the value of tm_order.total_price
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public Double getTotalPrice() {
        return totalPrice;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column tm_order.total_price
     * @param totalPrice  the value for tm_order.total_price
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public void setTotalPrice( Double totalPrice ) {
        this.totalPrice = totalPrice;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column tm_order.is_confirm
     * @return  the value of tm_order.is_confirm
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public Integer getIsConfirm() {
        return isConfirm;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column tm_order.is_confirm
     * @param isConfirm  the value for tm_order.is_confirm
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public void setIsConfirm( Integer isConfirm ) {
        this.isConfirm = isConfirm;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column tm_order.is_pay
     * @return  the value of tm_order.is_pay
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public Integer getIsPay() {
        return isPay;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column tm_order.is_pay
     * @param isPay  the value for tm_order.is_pay
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public void setIsPay( Integer isPay ) {
        this.isPay = isPay;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column tm_order.is_del
     * @return  the value of tm_order.is_del
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public String getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column tm_order.is_del
     * @param isDel  the value for tm_order.is_del
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public void setIsDel( String isDel ) {
        this.isDel = isDel;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column tm_order.create_time
     * @return  the value of tm_order.create_time
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column tm_order.create_time
     * @param createTime  the value for tm_order.create_time
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public void setCreateTime( Date createTime ) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column tm_order.create_user_id
     * @return  the value of tm_order.create_user_id
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public Integer getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column tm_order.create_user_id
     * @param createUserId  the value for tm_order.create_user_id
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public void setCreateUserId( Integer createUserId ) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column tm_order.update_time
     * @return  the value of tm_order.update_time
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column tm_order.update_time
     * @param updateTime  the value for tm_order.update_time
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public void setUpdateTime( Date updateTime ) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column tm_order.update_user_id
     * @return  the value of tm_order.update_user_id
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public Long getUpdateUserId() {
        return updateUserId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column tm_order.update_user_id
     * @param updateUserId  the value for tm_order.update_user_id
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public void setUpdateUserId( Long updateUserId ) {
        this.updateUserId = updateUserId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column tm_order.order_type
     * @return  the value of tm_order.order_type
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public Integer getOrderType() {
        return orderType;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column tm_order.order_type
     * @param orderType  the value for tm_order.order_type
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public void setOrderType( Integer orderType ) {
        this.orderType = orderType;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column tm_order.order_desc
     * @return  the value of tm_order.order_desc
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public String getOrderDesc() {
        return orderDesc;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column tm_order.order_desc
     * @param orderDesc  the value for tm_order.order_desc
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public void setOrderDesc( String orderDesc ) {
        this.orderDesc = orderDesc;
    }
}