package com.tour.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Map;

public class TmScheduleExample {

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database table tm_schedule
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    protected String orderByClause;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database table tm_schedule
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    protected List oredCriteria;

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tm_schedule
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public TmScheduleExample() {
        oredCriteria = new ArrayList();
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tm_schedule
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    protected TmScheduleExample( TmScheduleExample example ) {
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tm_schedule
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public void setOrderByClause( String orderByClause ) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tm_schedule
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tm_schedule
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public List getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tm_schedule
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public void or( Criteria criteria ) {
        oredCriteria.add( criteria );
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tm_schedule
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add( criteria );
        }
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tm_schedule
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tm_schedule
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public void clear() {
        oredCriteria.clear();
    }

    /**
     * This class was generated by Apache iBATIS ibator. This class corresponds to the database table tm_schedule
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public static class Criteria {
        
        protected List criteriaWithoutValue;
        protected List criteriaWithSingleValue;
        protected List criteriaWithListValue;
        protected List criteriaWithBetweenValue;
        
        protected Criteria() {
            super();
            criteriaWithoutValue = new ArrayList();
            criteriaWithSingleValue = new ArrayList();
            criteriaWithListValue = new ArrayList();
            criteriaWithBetweenValue = new ArrayList();
        }
        
        public boolean isValid() {
            return criteriaWithoutValue.size() > 0 || criteriaWithSingleValue.size() > 0
                    || criteriaWithListValue.size() > 0 || criteriaWithBetweenValue.size() > 0;
        }
        
        public List getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }
        
        public List getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }
        
        public List getCriteriaWithListValue() {
            return criteriaWithListValue;
        }
        
        public List getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }
        
        protected void addCriterion( String condition ) {
            if (condition == null) {
                throw new RuntimeException( "Value for condition cannot be null" );
            }
            criteriaWithoutValue.add( condition );
        }
        
        protected void addCriterion( String condition, Object value, String property ) {
            if (value == null) {
                throw new RuntimeException( "Value for " + property + " cannot be null" );
            }
            Map map = new HashMap();
            map.put( "condition", condition );
            map.put( "value", value );
            criteriaWithSingleValue.add( map );
        }
        
        protected void addCriterion( String condition, List values, String property ) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException( "Value list for " + property
                        + " cannot be null or empty" );
            }
            Map map = new HashMap();
            map.put( "condition", condition );
            map.put( "values", values );
            criteriaWithListValue.add( map );
        }
        
        protected void addCriterion( String condition, Object value1, Object value2, String property ) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException( "Between values for " + property + " cannot be null" );
            }
            List list = new ArrayList();
            list.add( value1 );
            list.add( value2 );
            Map map = new HashMap();
            map.put( "condition", condition );
            map.put( "values", list );
            criteriaWithBetweenValue.add( map );
        }
        
        protected void addCriterionForJDBCDate( String condition, Date value, String property ) {
            addCriterion( condition, new java.sql.Date( value.getTime() ), property );
        }
        
        protected void addCriterionForJDBCDate( String condition, List values, String property ) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException( "Value list for " + property
                        + " cannot be null or empty" );
            }
            List dateList = new ArrayList();
            Iterator iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add( new java.sql.Date( ((Date) iter.next()).getTime() ) );
            }
            addCriterion( condition, dateList, property );
        }
        
        protected void addCriterionForJDBCDate( String condition, Date value1, Date value2,
                String property ) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException( "Between values for " + property + " cannot be null" );
            }
            addCriterion( condition, new java.sql.Date( value1.getTime() ), new java.sql.Date(
                    value2.getTime() ), property );
        }
        
        public Criteria andIdIsNull() {
            addCriterion( "id is null" );
            return this;
        }
        
        public Criteria andIdIsNotNull() {
            addCriterion( "id is not null" );
            return this;
        }
        
        public Criteria andIdEqualTo( Integer value ) {
            addCriterion( "id =", value, "id" );
            return this;
        }
        
        public Criteria andIdNotEqualTo( Integer value ) {
            addCriterion( "id <>", value, "id" );
            return this;
        }
        
        public Criteria andIdGreaterThan( Integer value ) {
            addCriterion( "id >", value, "id" );
            return this;
        }
        
        public Criteria andIdGreaterThanOrEqualTo( Integer value ) {
            addCriterion( "id >=", value, "id" );
            return this;
        }
        
        public Criteria andIdLessThan( Integer value ) {
            addCriterion( "id <", value, "id" );
            return this;
        }
        
        public Criteria andIdLessThanOrEqualTo( Integer value ) {
            addCriterion( "id <=", value, "id" );
            return this;
        }
        
        public Criteria andIdIn( List values ) {
            addCriterion( "id in", values, "id" );
            return this;
        }
        
        public Criteria andIdNotIn( List values ) {
            addCriterion( "id not in", values, "id" );
            return this;
        }
        
        public Criteria andIdBetween( Integer value1, Integer value2 ) {
            addCriterion( "id between", value1, value2, "id" );
            return this;
        }
        
        public Criteria andIdNotBetween( Integer value1, Integer value2 ) {
            addCriterion( "id not between", value1, value2, "id" );
            return this;
        }
        
        public Criteria andNameIsNull() {
            addCriterion( "name is null" );
            return this;
        }
        
        public Criteria andNameIsNotNull() {
            addCriterion( "name is not null" );
            return this;
        }
        
        public Criteria andNameEqualTo( String value ) {
            addCriterion( "name =", value, "name" );
            return this;
        }
        
        public Criteria andNameNotEqualTo( String value ) {
            addCriterion( "name <>", value, "name" );
            return this;
        }
        
        public Criteria andNameGreaterThan( String value ) {
            addCriterion( "name >", value, "name" );
            return this;
        }
        
        public Criteria andNameGreaterThanOrEqualTo( String value ) {
            addCriterion( "name >=", value, "name" );
            return this;
        }
        
        public Criteria andNameLessThan( String value ) {
            addCriterion( "name <", value, "name" );
            return this;
        }
        
        public Criteria andNameLessThanOrEqualTo( String value ) {
            addCriterion( "name <=", value, "name" );
            return this;
        }
        
        public Criteria andNameLike( String value ) {
            addCriterion( "name like", value, "name" );
            return this;
        }
        
        public Criteria andNameNotLike( String value ) {
            addCriterion( "name not like", value, "name" );
            return this;
        }
        
        public Criteria andNameIn( List values ) {
            addCriterion( "name in", values, "name" );
            return this;
        }
        
        public Criteria andNameNotIn( List values ) {
            addCriterion( "name not in", values, "name" );
            return this;
        }
        
        public Criteria andNameBetween( String value1, String value2 ) {
            addCriterion( "name between", value1, value2, "name" );
            return this;
        }
        
        public Criteria andNameNotBetween( String value1, String value2 ) {
            addCriterion( "name not between", value1, value2, "name" );
            return this;
        }
        
        public Criteria andTotalDayIsNull() {
            addCriterion( "total_day is null" );
            return this;
        }
        
        public Criteria andTotalDayIsNotNull() {
            addCriterion( "total_day is not null" );
            return this;
        }
        
        public Criteria andTotalDayEqualTo( Integer value ) {
            addCriterion( "total_day =", value, "totalDay" );
            return this;
        }
        
        public Criteria andTotalDayNotEqualTo( Integer value ) {
            addCriterion( "total_day <>", value, "totalDay" );
            return this;
        }
        
        public Criteria andTotalDayGreaterThan( Integer value ) {
            addCriterion( "total_day >", value, "totalDay" );
            return this;
        }
        
        public Criteria andTotalDayGreaterThanOrEqualTo( Integer value ) {
            addCriterion( "total_day >=", value, "totalDay" );
            return this;
        }
        
        public Criteria andTotalDayLessThan( Integer value ) {
            addCriterion( "total_day <", value, "totalDay" );
            return this;
        }
        
        public Criteria andTotalDayLessThanOrEqualTo( Integer value ) {
            addCriterion( "total_day <=", value, "totalDay" );
            return this;
        }
        
        public Criteria andTotalDayIn( List values ) {
            addCriterion( "total_day in", values, "totalDay" );
            return this;
        }
        
        public Criteria andTotalDayNotIn( List values ) {
            addCriterion( "total_day not in", values, "totalDay" );
            return this;
        }
        
        public Criteria andTotalDayBetween( Integer value1, Integer value2 ) {
            addCriterion( "total_day between", value1, value2, "totalDay" );
            return this;
        }
        
        public Criteria andTotalDayNotBetween( Integer value1, Integer value2 ) {
            addCriterion( "total_day not between", value1, value2, "totalDay" );
            return this;
        }
        
        public Criteria andTotalPeopleIsNull() {
            addCriterion( "total_people is null" );
            return this;
        }
        
        public Criteria andTotalPeopleIsNotNull() {
            addCriterion( "total_people is not null" );
            return this;
        }
        
        public Criteria andTotalPeopleEqualTo( Integer value ) {
            addCriterion( "total_people =", value, "totalPeople" );
            return this;
        }
        
        public Criteria andTotalPeopleNotEqualTo( Integer value ) {
            addCriterion( "total_people <>", value, "totalPeople" );
            return this;
        }
        
        public Criteria andTotalPeopleGreaterThan( Integer value ) {
            addCriterion( "total_people >", value, "totalPeople" );
            return this;
        }
        
        public Criteria andTotalPeopleGreaterThanOrEqualTo( Integer value ) {
            addCriterion( "total_people >=", value, "totalPeople" );
            return this;
        }
        
        public Criteria andTotalPeopleLessThan( Integer value ) {
            addCriterion( "total_people <", value, "totalPeople" );
            return this;
        }
        
        public Criteria andTotalPeopleLessThanOrEqualTo( Integer value ) {
            addCriterion( "total_people <=", value, "totalPeople" );
            return this;
        }
        
        public Criteria andTotalPeopleIn( List values ) {
            addCriterion( "total_people in", values, "totalPeople" );
            return this;
        }
        
        public Criteria andTotalPeopleNotIn( List values ) {
            addCriterion( "total_people not in", values, "totalPeople" );
            return this;
        }
        
        public Criteria andTotalPeopleBetween( Integer value1, Integer value2 ) {
            addCriterion( "total_people between", value1, value2, "totalPeople" );
            return this;
        }
        
        public Criteria andTotalPeopleNotBetween( Integer value1, Integer value2 ) {
            addCriterion( "total_people not between", value1, value2, "totalPeople" );
            return this;
        }
        
        public Criteria andPriceIsNull() {
            addCriterion( "price is null" );
            return this;
        }
        
        public Criteria andPriceIsNotNull() {
            addCriterion( "price is not null" );
            return this;
        }
        
        public Criteria andPriceEqualTo( Double value ) {
            addCriterion( "price =", value, "price" );
            return this;
        }
        
        public Criteria andPriceNotEqualTo( Double value ) {
            addCriterion( "price <>", value, "price" );
            return this;
        }
        
        public Criteria andPriceGreaterThan( Double value ) {
            addCriterion( "price >", value, "price" );
            return this;
        }
        
        public Criteria andPriceGreaterThanOrEqualTo( Double value ) {
            addCriterion( "price >=", value, "price" );
            return this;
        }
        
        public Criteria andPriceLessThan( Double value ) {
            addCriterion( "price <", value, "price" );
            return this;
        }
        
        public Criteria andPriceLessThanOrEqualTo( Double value ) {
            addCriterion( "price <=", value, "price" );
            return this;
        }
        
        public Criteria andPriceIn( List values ) {
            addCriterion( "price in", values, "price" );
            return this;
        }
        
        public Criteria andPriceNotIn( List values ) {
            addCriterion( "price not in", values, "price" );
            return this;
        }
        
        public Criteria andPriceBetween( Double value1, Double value2 ) {
            addCriterion( "price between", value1, value2, "price" );
            return this;
        }
        
        public Criteria andPriceNotBetween( Double value1, Double value2 ) {
            addCriterion( "price not between", value1, value2, "price" );
            return this;
        }
        
        public Criteria andDepartureIsNull() {
            addCriterion( "departure is null" );
            return this;
        }
        
        public Criteria andDepartureIsNotNull() {
            addCriterion( "departure is not null" );
            return this;
        }
        
        public Criteria andDepartureEqualTo( String value ) {
            addCriterion( "departure =", value, "departure" );
            return this;
        }
        
        public Criteria andDepartureNotEqualTo( String value ) {
            addCriterion( "departure <>", value, "departure" );
            return this;
        }
        
        public Criteria andDepartureGreaterThan( String value ) {
            addCriterion( "departure >", value, "departure" );
            return this;
        }
        
        public Criteria andDepartureGreaterThanOrEqualTo( String value ) {
            addCriterion( "departure >=", value, "departure" );
            return this;
        }
        
        public Criteria andDepartureLessThan( String value ) {
            addCriterion( "departure <", value, "departure" );
            return this;
        }
        
        public Criteria andDepartureLessThanOrEqualTo( String value ) {
            addCriterion( "departure <=", value, "departure" );
            return this;
        }
        
        public Criteria andDepartureLike( String value ) {
            addCriterion( "departure like", value, "departure" );
            return this;
        }
        
        public Criteria andDepartureNotLike( String value ) {
            addCriterion( "departure not like", value, "departure" );
            return this;
        }
        
        public Criteria andDepartureIn( List values ) {
            addCriterion( "departure in", values, "departure" );
            return this;
        }
        
        public Criteria andDepartureNotIn( List values ) {
            addCriterion( "departure not in", values, "departure" );
            return this;
        }
        
        public Criteria andDepartureBetween( String value1, String value2 ) {
            addCriterion( "departure between", value1, value2, "departure" );
            return this;
        }
        
        public Criteria andDepartureNotBetween( String value1, String value2 ) {
            addCriterion( "departure not between", value1, value2, "departure" );
            return this;
        }
        
        public Criteria andDestinationIsNull() {
            addCriterion( "destination is null" );
            return this;
        }
        
        public Criteria andDestinationIsNotNull() {
            addCriterion( "destination is not null" );
            return this;
        }
        
        public Criteria andDestinationEqualTo( String value ) {
            addCriterion( "destination =", value, "destination" );
            return this;
        }
        
        public Criteria andDestinationNotEqualTo( String value ) {
            addCriterion( "destination <>", value, "destination" );
            return this;
        }
        
        public Criteria andDestinationGreaterThan( String value ) {
            addCriterion( "destination >", value, "destination" );
            return this;
        }
        
        public Criteria andDestinationGreaterThanOrEqualTo( String value ) {
            addCriterion( "destination >=", value, "destination" );
            return this;
        }
        
        public Criteria andDestinationLessThan( String value ) {
            addCriterion( "destination <", value, "destination" );
            return this;
        }
        
        public Criteria andDestinationLessThanOrEqualTo( String value ) {
            addCriterion( "destination <=", value, "destination" );
            return this;
        }
        
        public Criteria andDestinationLike( String value ) {
            addCriterion( "destination like", value, "destination" );
            return this;
        }
        
        public Criteria andDestinationNotLike( String value ) {
            addCriterion( "destination not like", value, "destination" );
            return this;
        }
        
        public Criteria andDestinationIn( List values ) {
            addCriterion( "destination in", values, "destination" );
            return this;
        }
        
        public Criteria andDestinationNotIn( List values ) {
            addCriterion( "destination not in", values, "destination" );
            return this;
        }
        
        public Criteria andDestinationBetween( String value1, String value2 ) {
            addCriterion( "destination between", value1, value2, "destination" );
            return this;
        }
        
        public Criteria andDestinationNotBetween( String value1, String value2 ) {
            addCriterion( "destination not between", value1, value2, "destination" );
            return this;
        }
        
        public Criteria andStartTimeIsNull() {
            addCriterion( "start_time is null" );
            return this;
        }
        
        public Criteria andStartTimeIsNotNull() {
            addCriterion( "start_time is not null" );
            return this;
        }
        
        public Criteria andStartTimeEqualTo( Date value ) {
            addCriterionForJDBCDate( "start_time =", value, "startTime" );
            return this;
        }
        
        public Criteria andStartTimeNotEqualTo( Date value ) {
            addCriterionForJDBCDate( "start_time <>", value, "startTime" );
            return this;
        }
        
        public Criteria andStartTimeGreaterThan( Date value ) {
            addCriterionForJDBCDate( "start_time >", value, "startTime" );
            return this;
        }
        
        public Criteria andStartTimeGreaterThanOrEqualTo( Date value ) {
            addCriterionForJDBCDate( "start_time >=", value, "startTime" );
            return this;
        }
        
        public Criteria andStartTimeLessThan( Date value ) {
            addCriterionForJDBCDate( "start_time <", value, "startTime" );
            return this;
        }
        
        public Criteria andStartTimeLessThanOrEqualTo( Date value ) {
            addCriterionForJDBCDate( "start_time <=", value, "startTime" );
            return this;
        }
        
        public Criteria andStartTimeIn( List values ) {
            addCriterionForJDBCDate( "start_time in", values, "startTime" );
            return this;
        }
        
        public Criteria andStartTimeNotIn( List values ) {
            addCriterionForJDBCDate( "start_time not in", values, "startTime" );
            return this;
        }
        
        public Criteria andStartTimeBetween( Date value1, Date value2 ) {
            addCriterionForJDBCDate( "start_time between", value1, value2, "startTime" );
            return this;
        }
        
        public Criteria andStartTimeNotBetween( Date value1, Date value2 ) {
            addCriterionForJDBCDate( "start_time not between", value1, value2, "startTime" );
            return this;
        }
        
        public Criteria andEndTimeIsNull() {
            addCriterion( "end_time is null" );
            return this;
        }
        
        public Criteria andEndTimeIsNotNull() {
            addCriterion( "end_time is not null" );
            return this;
        }
        
        public Criteria andEndTimeEqualTo( Date value ) {
            addCriterionForJDBCDate( "end_time =", value, "endTime" );
            return this;
        }
        
        public Criteria andEndTimeNotEqualTo( Date value ) {
            addCriterionForJDBCDate( "end_time <>", value, "endTime" );
            return this;
        }
        
        public Criteria andEndTimeGreaterThan( Date value ) {
            addCriterionForJDBCDate( "end_time >", value, "endTime" );
            return this;
        }
        
        public Criteria andEndTimeGreaterThanOrEqualTo( Date value ) {
            addCriterionForJDBCDate( "end_time >=", value, "endTime" );
            return this;
        }
        
        public Criteria andEndTimeLessThan( Date value ) {
            addCriterionForJDBCDate( "end_time <", value, "endTime" );
            return this;
        }
        
        public Criteria andEndTimeLessThanOrEqualTo( Date value ) {
            addCriterionForJDBCDate( "end_time <=", value, "endTime" );
            return this;
        }
        
        public Criteria andEndTimeIn( List values ) {
            addCriterionForJDBCDate( "end_time in", values, "endTime" );
            return this;
        }
        
        public Criteria andEndTimeNotIn( List values ) {
            addCriterionForJDBCDate( "end_time not in", values, "endTime" );
            return this;
        }
        
        public Criteria andEndTimeBetween( Date value1, Date value2 ) {
            addCriterionForJDBCDate( "end_time between", value1, value2, "endTime" );
            return this;
        }
        
        public Criteria andEndTimeNotBetween( Date value1, Date value2 ) {
            addCriterionForJDBCDate( "end_time not between", value1, value2, "endTime" );
            return this;
        }
        
        public Criteria andTypeIsNull() {
            addCriterion( "type is null" );
            return this;
        }
        
        public Criteria andTypeIsNotNull() {
            addCriterion( "type is not null" );
            return this;
        }
        
        public Criteria andTypeEqualTo( Integer value ) {
            addCriterion( "type =", value, "type" );
            return this;
        }
        
        public Criteria andTypeNotEqualTo( Integer value ) {
            addCriterion( "type <>", value, "type" );
            return this;
        }
        
        public Criteria andTypeGreaterThan( Integer value ) {
            addCriterion( "type >", value, "type" );
            return this;
        }
        
        public Criteria andTypeGreaterThanOrEqualTo( Integer value ) {
            addCriterion( "type >=", value, "type" );
            return this;
        }
        
        public Criteria andTypeLessThan( Integer value ) {
            addCriterion( "type <", value, "type" );
            return this;
        }
        
        public Criteria andTypeLessThanOrEqualTo( Integer value ) {
            addCriterion( "type <=", value, "type" );
            return this;
        }
        
        public Criteria andTypeIn( List values ) {
            addCriterion( "type in", values, "type" );
            return this;
        }
        
        public Criteria andTypeNotIn( List values ) {
            addCriterion( "type not in", values, "type" );
            return this;
        }
        
        public Criteria andTypeBetween( Integer value1, Integer value2 ) {
            addCriterion( "type between", value1, value2, "type" );
            return this;
        }
        
        public Criteria andTypeNotBetween( Integer value1, Integer value2 ) {
            addCriterion( "type not between", value1, value2, "type" );
            return this;
        }
        
        public Criteria andGradeIsNull() {
            addCriterion( "grade is null" );
            return this;
        }
        
        public Criteria andGradeIsNotNull() {
            addCriterion( "grade is not null" );
            return this;
        }
        
        public Criteria andGradeEqualTo( Integer value ) {
            addCriterion( "grade =", value, "grade" );
            return this;
        }
        
        public Criteria andGradeNotEqualTo( Integer value ) {
            addCriterion( "grade <>", value, "grade" );
            return this;
        }
        
        public Criteria andGradeGreaterThan( Integer value ) {
            addCriterion( "grade >", value, "grade" );
            return this;
        }
        
        public Criteria andGradeGreaterThanOrEqualTo( Integer value ) {
            addCriterion( "grade >=", value, "grade" );
            return this;
        }
        
        public Criteria andGradeLessThan( Integer value ) {
            addCriterion( "grade <", value, "grade" );
            return this;
        }
        
        public Criteria andGradeLessThanOrEqualTo( Integer value ) {
            addCriterion( "grade <=", value, "grade" );
            return this;
        }
        
        public Criteria andGradeIn( List values ) {
            addCriterion( "grade in", values, "grade" );
            return this;
        }
        
        public Criteria andGradeNotIn( List values ) {
            addCriterion( "grade not in", values, "grade" );
            return this;
        }
        
        public Criteria andGradeBetween( Integer value1, Integer value2 ) {
            addCriterion( "grade between", value1, value2, "grade" );
            return this;
        }
        
        public Criteria andGradeNotBetween( Integer value1, Integer value2 ) {
            addCriterion( "grade not between", value1, value2, "grade" );
            return this;
        }
        
        public Criteria andLineCodeIsNull() {
            addCriterion( "line_code is null" );
            return this;
        }
        
        public Criteria andLineCodeIsNotNull() {
            addCriterion( "line_code is not null" );
            return this;
        }
        
        public Criteria andLineCodeEqualTo( String value ) {
            addCriterion( "line_code =", value, "lineCode" );
            return this;
        }
        
        public Criteria andLineCodeNotEqualTo( String value ) {
            addCriterion( "line_code <>", value, "lineCode" );
            return this;
        }
        
        public Criteria andLineCodeGreaterThan( String value ) {
            addCriterion( "line_code >", value, "lineCode" );
            return this;
        }
        
        public Criteria andLineCodeGreaterThanOrEqualTo( String value ) {
            addCriterion( "line_code >=", value, "lineCode" );
            return this;
        }
        
        public Criteria andLineCodeLessThan( String value ) {
            addCriterion( "line_code <", value, "lineCode" );
            return this;
        }
        
        public Criteria andLineCodeLessThanOrEqualTo( String value ) {
            addCriterion( "line_code <=", value, "lineCode" );
            return this;
        }
        
        public Criteria andLineCodeLike( String value ) {
            addCriterion( "line_code like", value, "lineCode" );
            return this;
        }
        
        public Criteria andLineCodeNotLike( String value ) {
            addCriterion( "line_code not like", value, "lineCode" );
            return this;
        }
        
        public Criteria andLineCodeIn( List values ) {
            addCriterion( "line_code in", values, "lineCode" );
            return this;
        }
        
        public Criteria andLineCodeNotIn( List values ) {
            addCriterion( "line_code not in", values, "lineCode" );
            return this;
        }
        
        public Criteria andLineCodeBetween( String value1, String value2 ) {
            addCriterion( "line_code between", value1, value2, "lineCode" );
            return this;
        }
        
        public Criteria andLineCodeNotBetween( String value1, String value2 ) {
            addCriterion( "line_code not between", value1, value2, "lineCode" );
            return this;
        }
        
        public Criteria andGuiderIdsIsNull() {
            addCriterion( "guider_ids is null" );
            return this;
        }
        
        public Criteria andGuiderIdsIsNotNull() {
            addCriterion( "guider_ids is not null" );
            return this;
        }
        
        public Criteria andGuiderIdsEqualTo( String value ) {
            addCriterion( "guider_ids =", value, "guiderIds" );
            return this;
        }
        
        public Criteria andGuiderIdsNotEqualTo( String value ) {
            addCriterion( "guider_ids <>", value, "guiderIds" );
            return this;
        }
        
        public Criteria andGuiderIdsGreaterThan( String value ) {
            addCriterion( "guider_ids >", value, "guiderIds" );
            return this;
        }
        
        public Criteria andGuiderIdsGreaterThanOrEqualTo( String value ) {
            addCriterion( "guider_ids >=", value, "guiderIds" );
            return this;
        }
        
        public Criteria andGuiderIdsLessThan( String value ) {
            addCriterion( "guider_ids <", value, "guiderIds" );
            return this;
        }
        
        public Criteria andGuiderIdsLessThanOrEqualTo( String value ) {
            addCriterion( "guider_ids <=", value, "guiderIds" );
            return this;
        }
        
        public Criteria andGuiderIdsLike( String value ) {
            addCriterion( "guider_ids like", value, "guiderIds" );
            return this;
        }
        
        public Criteria andGuiderIdsNotLike( String value ) {
            addCriterion( "guider_ids not like", value, "guiderIds" );
            return this;
        }
        
        public Criteria andGuiderIdsIn( List values ) {
            addCriterion( "guider_ids in", values, "guiderIds" );
            return this;
        }
        
        public Criteria andGuiderIdsNotIn( List values ) {
            addCriterion( "guider_ids not in", values, "guiderIds" );
            return this;
        }
        
        public Criteria andGuiderIdsBetween( String value1, String value2 ) {
            addCriterion( "guider_ids between", value1, value2, "guiderIds" );
            return this;
        }
        
        public Criteria andGuiderIdsNotBetween( String value1, String value2 ) {
            addCriterion( "guider_ids not between", value1, value2, "guiderIds" );
            return this;
        }
        
        public Criteria andDetailIdIsNull() {
            addCriterion( "detail_id is null" );
            return this;
        }
        
        public Criteria andDetailIdIsNotNull() {
            addCriterion( "detail_id is not null" );
            return this;
        }
        
        public Criteria andDetailIdEqualTo( String value ) {
            addCriterion( "detail_id =", value, "detailId" );
            return this;
        }
        
        public Criteria andDetailIdNotEqualTo( String value ) {
            addCriterion( "detail_id <>", value, "detailId" );
            return this;
        }
        
        public Criteria andDetailIdGreaterThan( String value ) {
            addCriterion( "detail_id >", value, "detailId" );
            return this;
        }
        
        public Criteria andDetailIdGreaterThanOrEqualTo( String value ) {
            addCriterion( "detail_id >=", value, "detailId" );
            return this;
        }
        
        public Criteria andDetailIdLessThan( String value ) {
            addCriterion( "detail_id <", value, "detailId" );
            return this;
        }
        
        public Criteria andDetailIdLessThanOrEqualTo( String value ) {
            addCriterion( "detail_id <=", value, "detailId" );
            return this;
        }
        
        public Criteria andDetailIdLike( String value ) {
            addCriterion( "detail_id like", value, "detailId" );
            return this;
        }
        
        public Criteria andDetailIdNotLike( String value ) {
            addCriterion( "detail_id not like", value, "detailId" );
            return this;
        }
        
        public Criteria andDetailIdIn( List values ) {
            addCriterion( "detail_id in", values, "detailId" );
            return this;
        }
        
        public Criteria andDetailIdNotIn( List values ) {
            addCriterion( "detail_id not in", values, "detailId" );
            return this;
        }
        
        public Criteria andDetailIdBetween( String value1, String value2 ) {
            addCriterion( "detail_id between", value1, value2, "detailId" );
            return this;
        }
        
        public Criteria andDetailIdNotBetween( String value1, String value2 ) {
            addCriterion( "detail_id not between", value1, value2, "detailId" );
            return this;
        }
        
        public Criteria andCreateTimeIsNull() {
            addCriterion( "create_time is null" );
            return this;
        }
        
        public Criteria andCreateTimeIsNotNull() {
            addCriterion( "create_time is not null" );
            return this;
        }
        
        public Criteria andCreateTimeEqualTo( Date value ) {
            addCriterionForJDBCDate( "create_time =", value, "createTime" );
            return this;
        }
        
        public Criteria andCreateTimeNotEqualTo( Date value ) {
            addCriterionForJDBCDate( "create_time <>", value, "createTime" );
            return this;
        }
        
        public Criteria andCreateTimeGreaterThan( Date value ) {
            addCriterionForJDBCDate( "create_time >", value, "createTime" );
            return this;
        }
        
        public Criteria andCreateTimeGreaterThanOrEqualTo( Date value ) {
            addCriterionForJDBCDate( "create_time >=", value, "createTime" );
            return this;
        }
        
        public Criteria andCreateTimeLessThan( Date value ) {
            addCriterionForJDBCDate( "create_time <", value, "createTime" );
            return this;
        }
        
        public Criteria andCreateTimeLessThanOrEqualTo( Date value ) {
            addCriterionForJDBCDate( "create_time <=", value, "createTime" );
            return this;
        }
        
        public Criteria andCreateTimeIn( List values ) {
            addCriterionForJDBCDate( "create_time in", values, "createTime" );
            return this;
        }
        
        public Criteria andCreateTimeNotIn( List values ) {
            addCriterionForJDBCDate( "create_time not in", values, "createTime" );
            return this;
        }
        
        public Criteria andCreateTimeBetween( Date value1, Date value2 ) {
            addCriterionForJDBCDate( "create_time between", value1, value2, "createTime" );
            return this;
        }
        
        public Criteria andCreateTimeNotBetween( Date value1, Date value2 ) {
            addCriterionForJDBCDate( "create_time not between", value1, value2, "createTime" );
            return this;
        }
        
        public Criteria andCreateUserIdIsNull() {
            addCriterion( "create_user_id is null" );
            return this;
        }
        
        public Criteria andCreateUserIdIsNotNull() {
            addCriterion( "create_user_id is not null" );
            return this;
        }
        
        public Criteria andCreateUserIdEqualTo( Integer value ) {
            addCriterion( "create_user_id =", value, "createUserId" );
            return this;
        }
        
        public Criteria andCreateUserIdNotEqualTo( Integer value ) {
            addCriterion( "create_user_id <>", value, "createUserId" );
            return this;
        }
        
        public Criteria andCreateUserIdGreaterThan( Integer value ) {
            addCriterion( "create_user_id >", value, "createUserId" );
            return this;
        }
        
        public Criteria andCreateUserIdGreaterThanOrEqualTo( Integer value ) {
            addCriterion( "create_user_id >=", value, "createUserId" );
            return this;
        }
        
        public Criteria andCreateUserIdLessThan( Integer value ) {
            addCriterion( "create_user_id <", value, "createUserId" );
            return this;
        }
        
        public Criteria andCreateUserIdLessThanOrEqualTo( Integer value ) {
            addCriterion( "create_user_id <=", value, "createUserId" );
            return this;
        }
        
        public Criteria andCreateUserIdIn( List values ) {
            addCriterion( "create_user_id in", values, "createUserId" );
            return this;
        }
        
        public Criteria andCreateUserIdNotIn( List values ) {
            addCriterion( "create_user_id not in", values, "createUserId" );
            return this;
        }
        
        public Criteria andCreateUserIdBetween( Integer value1, Integer value2 ) {
            addCriterion( "create_user_id between", value1, value2, "createUserId" );
            return this;
        }
        
        public Criteria andCreateUserIdNotBetween( Integer value1, Integer value2 ) {
            addCriterion( "create_user_id not between", value1, value2, "createUserId" );
            return this;
        }
        
        public Criteria andUpdateTimeIsNull() {
            addCriterion( "update_time is null" );
            return this;
        }
        
        public Criteria andUpdateTimeIsNotNull() {
            addCriterion( "update_time is not null" );
            return this;
        }
        
        public Criteria andUpdateTimeEqualTo( Date value ) {
            addCriterionForJDBCDate( "update_time =", value, "updateTime" );
            return this;
        }
        
        public Criteria andUpdateTimeNotEqualTo( Date value ) {
            addCriterionForJDBCDate( "update_time <>", value, "updateTime" );
            return this;
        }
        
        public Criteria andUpdateTimeGreaterThan( Date value ) {
            addCriterionForJDBCDate( "update_time >", value, "updateTime" );
            return this;
        }
        
        public Criteria andUpdateTimeGreaterThanOrEqualTo( Date value ) {
            addCriterionForJDBCDate( "update_time >=", value, "updateTime" );
            return this;
        }
        
        public Criteria andUpdateTimeLessThan( Date value ) {
            addCriterionForJDBCDate( "update_time <", value, "updateTime" );
            return this;
        }
        
        public Criteria andUpdateTimeLessThanOrEqualTo( Date value ) {
            addCriterionForJDBCDate( "update_time <=", value, "updateTime" );
            return this;
        }
        
        public Criteria andUpdateTimeIn( List values ) {
            addCriterionForJDBCDate( "update_time in", values, "updateTime" );
            return this;
        }
        
        public Criteria andUpdateTimeNotIn( List values ) {
            addCriterionForJDBCDate( "update_time not in", values, "updateTime" );
            return this;
        }
        
        public Criteria andUpdateTimeBetween( Date value1, Date value2 ) {
            addCriterionForJDBCDate( "update_time between", value1, value2, "updateTime" );
            return this;
        }
        
        public Criteria andUpdateTimeNotBetween( Date value1, Date value2 ) {
            addCriterionForJDBCDate( "update_time not between", value1, value2, "updateTime" );
            return this;
        }
        
        public Criteria andUpdateUserIdIsNull() {
            addCriterion( "update_user_id is null" );
            return this;
        }
        
        public Criteria andUpdateUserIdIsNotNull() {
            addCriterion( "update_user_id is not null" );
            return this;
        }
        
        public Criteria andUpdateUserIdEqualTo( Long value ) {
            addCriterion( "update_user_id =", value, "updateUserId" );
            return this;
        }
        
        public Criteria andUpdateUserIdNotEqualTo( Long value ) {
            addCriterion( "update_user_id <>", value, "updateUserId" );
            return this;
        }
        
        public Criteria andUpdateUserIdGreaterThan( Long value ) {
            addCriterion( "update_user_id >", value, "updateUserId" );
            return this;
        }
        
        public Criteria andUpdateUserIdGreaterThanOrEqualTo( Long value ) {
            addCriterion( "update_user_id >=", value, "updateUserId" );
            return this;
        }
        
        public Criteria andUpdateUserIdLessThan( Long value ) {
            addCriterion( "update_user_id <", value, "updateUserId" );
            return this;
        }
        
        public Criteria andUpdateUserIdLessThanOrEqualTo( Long value ) {
            addCriterion( "update_user_id <=", value, "updateUserId" );
            return this;
        }
        
        public Criteria andUpdateUserIdIn( List values ) {
            addCriterion( "update_user_id in", values, "updateUserId" );
            return this;
        }
        
        public Criteria andUpdateUserIdNotIn( List values ) {
            addCriterion( "update_user_id not in", values, "updateUserId" );
            return this;
        }
        
        public Criteria andUpdateUserIdBetween( Long value1, Long value2 ) {
            addCriterion( "update_user_id between", value1, value2, "updateUserId" );
            return this;
        }
        
        public Criteria andUpdateUserIdNotBetween( Long value1, Long value2 ) {
            addCriterion( "update_user_id not between", value1, value2, "updateUserId" );
            return this;
        }
        
        public Criteria andIsDelIsNull() {
            addCriterion( "is_del is null" );
            return this;
        }
        
        public Criteria andIsDelIsNotNull() {
            addCriterion( "is_del is not null" );
            return this;
        }
        
        public Criteria andIsDelEqualTo( String value ) {
            addCriterion( "is_del =", value, "isDel" );
            return this;
        }
        
        public Criteria andIsDelNotEqualTo( String value ) {
            addCriterion( "is_del <>", value, "isDel" );
            return this;
        }
        
        public Criteria andIsDelGreaterThan( String value ) {
            addCriterion( "is_del >", value, "isDel" );
            return this;
        }
        
        public Criteria andIsDelGreaterThanOrEqualTo( String value ) {
            addCriterion( "is_del >=", value, "isDel" );
            return this;
        }
        
        public Criteria andIsDelLessThan( String value ) {
            addCriterion( "is_del <", value, "isDel" );
            return this;
        }
        
        public Criteria andIsDelLessThanOrEqualTo( String value ) {
            addCriterion( "is_del <=", value, "isDel" );
            return this;
        }
        
        public Criteria andIsDelLike( String value ) {
            addCriterion( "is_del like", value, "isDel" );
            return this;
        }
        
        public Criteria andIsDelNotLike( String value ) {
            addCriterion( "is_del not like", value, "isDel" );
            return this;
        }
        
        public Criteria andIsDelIn( List values ) {
            addCriterion( "is_del in", values, "isDel" );
            return this;
        }
        
        public Criteria andIsDelNotIn( List values ) {
            addCriterion( "is_del not in", values, "isDel" );
            return this;
        }
        
        public Criteria andIsDelBetween( String value1, String value2 ) {
            addCriterion( "is_del between", value1, value2, "isDel" );
            return this;
        }
        
        public Criteria andIsDelNotBetween( String value1, String value2 ) {
            addCriterion( "is_del not between", value1, value2, "isDel" );
            return this;
        }
        
        public Criteria andScheduleDescIsNull() {
            addCriterion( "schedule_desc is null" );
            return this;
        }
        
        public Criteria andScheduleDescIsNotNull() {
            addCriterion( "schedule_desc is not null" );
            return this;
        }
        
        public Criteria andScheduleDescEqualTo( String value ) {
            addCriterion( "schedule_desc =", value, "scheduleDesc" );
            return this;
        }
        
        public Criteria andScheduleDescNotEqualTo( String value ) {
            addCriterion( "schedule_desc <>", value, "scheduleDesc" );
            return this;
        }
        
        public Criteria andScheduleDescGreaterThan( String value ) {
            addCriterion( "schedule_desc >", value, "scheduleDesc" );
            return this;
        }
        
        public Criteria andScheduleDescGreaterThanOrEqualTo( String value ) {
            addCriterion( "schedule_desc >=", value, "scheduleDesc" );
            return this;
        }
        
        public Criteria andScheduleDescLessThan( String value ) {
            addCriterion( "schedule_desc <", value, "scheduleDesc" );
            return this;
        }
        
        public Criteria andScheduleDescLessThanOrEqualTo( String value ) {
            addCriterion( "schedule_desc <=", value, "scheduleDesc" );
            return this;
        }
        
        public Criteria andScheduleDescLike( String value ) {
            addCriterion( "schedule_desc like", value, "scheduleDesc" );
            return this;
        }
        
        public Criteria andScheduleDescNotLike( String value ) {
            addCriterion( "schedule_desc not like", value, "scheduleDesc" );
            return this;
        }
        
        public Criteria andScheduleDescIn( List values ) {
            addCriterion( "schedule_desc in", values, "scheduleDesc" );
            return this;
        }
        
        public Criteria andScheduleDescNotIn( List values ) {
            addCriterion( "schedule_desc not in", values, "scheduleDesc" );
            return this;
        }
        
        public Criteria andScheduleDescBetween( String value1, String value2 ) {
            addCriterion( "schedule_desc between", value1, value2, "scheduleDesc" );
            return this;
        }
        
        public Criteria andScheduleDescNotBetween( String value1, String value2 ) {
            addCriterion( "schedule_desc not between", value1, value2, "scheduleDesc" );
            return this;
        }
    }
}