package com.tour.model;

import java.util.Date;

public class TmSchedule {
    
    private String guiderNames;

    public String getGuiderNames() {
        return guiderNames;
    }

    
    public void setGuiderNames( String guiderNames ) {
        this.guiderNames = guiderNames;
    }

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column tm_schedule.id
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    private Integer id;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column tm_schedule.name
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    private String name;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column tm_schedule.total_day
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    private Integer totalDay;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column tm_schedule.total_people
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    private Integer totalPeople;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column tm_schedule.price
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    private Double price;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column tm_schedule.departure
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    private String departure;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column tm_schedule.destination
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    private String destination;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column tm_schedule.start_time
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    private Date startTime;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column tm_schedule.end_time
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    private Date endTime;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column tm_schedule.type
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    private Integer type;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column tm_schedule.grade
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    private Integer grade;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column tm_schedule.line_code
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    private String lineCode;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column tm_schedule.guider_ids
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    private String guiderIds;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column tm_schedule.detail_id
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    private String detailId;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column tm_schedule.create_time
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    private Date createTime;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column tm_schedule.create_user_id
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    private Integer createUserId;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column tm_schedule.update_time
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    private Date updateTime;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column tm_schedule.update_user_id
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    private Long updateUserId;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column tm_schedule.is_del
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    private String isDel;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column tm_schedule.schedule_desc
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    private String scheduleDesc;

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column tm_schedule.id
     * @return  the value of tm_schedule.id
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column tm_schedule.id
     * @param id  the value for tm_schedule.id
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public void setId( Integer id ) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column tm_schedule.name
     * @return  the value of tm_schedule.name
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column tm_schedule.name
     * @param name  the value for tm_schedule.name
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public void setName( String name ) {
        this.name = name;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column tm_schedule.total_day
     * @return  the value of tm_schedule.total_day
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public Integer getTotalDay() {
        return totalDay;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column tm_schedule.total_day
     * @param totalDay  the value for tm_schedule.total_day
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public void setTotalDay( Integer totalDay ) {
        this.totalDay = totalDay;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column tm_schedule.total_people
     * @return  the value of tm_schedule.total_people
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public Integer getTotalPeople() {
        return totalPeople;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column tm_schedule.total_people
     * @param totalPeople  the value for tm_schedule.total_people
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public void setTotalPeople( Integer totalPeople ) {
        this.totalPeople = totalPeople;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column tm_schedule.price
     * @return  the value of tm_schedule.price
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column tm_schedule.price
     * @param price  the value for tm_schedule.price
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public void setPrice( Double price ) {
        this.price = price;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column tm_schedule.departure
     * @return  the value of tm_schedule.departure
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public String getDeparture() {
        return departure;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column tm_schedule.departure
     * @param departure  the value for tm_schedule.departure
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public void setDeparture( String departure ) {
        this.departure = departure;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column tm_schedule.destination
     * @return  the value of tm_schedule.destination
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public String getDestination() {
        return destination;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column tm_schedule.destination
     * @param destination  the value for tm_schedule.destination
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public void setDestination( String destination ) {
        this.destination = destination;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column tm_schedule.start_time
     * @return  the value of tm_schedule.start_time
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column tm_schedule.start_time
     * @param startTime  the value for tm_schedule.start_time
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public void setStartTime( Date startTime ) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column tm_schedule.end_time
     * @return  the value of tm_schedule.end_time
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column tm_schedule.end_time
     * @param endTime  the value for tm_schedule.end_time
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public void setEndTime( Date endTime ) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column tm_schedule.type
     * @return  the value of tm_schedule.type
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column tm_schedule.type
     * @param type  the value for tm_schedule.type
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public void setType( Integer type ) {
        this.type = type;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column tm_schedule.grade
     * @return  the value of tm_schedule.grade
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public Integer getGrade() {
        return grade;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column tm_schedule.grade
     * @param grade  the value for tm_schedule.grade
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public void setGrade( Integer grade ) {
        this.grade = grade;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column tm_schedule.line_code
     * @return  the value of tm_schedule.line_code
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public String getLineCode() {
        return lineCode;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column tm_schedule.line_code
     * @param lineCode  the value for tm_schedule.line_code
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public void setLineCode( String lineCode ) {
        this.lineCode = lineCode;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column tm_schedule.guider_ids
     * @return  the value of tm_schedule.guider_ids
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public String getGuiderIds() {
        return guiderIds;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column tm_schedule.guider_ids
     * @param guiderIds  the value for tm_schedule.guider_ids
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public void setGuiderIds( String guiderIds ) {
        this.guiderIds = guiderIds;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column tm_schedule.detail_id
     * @return  the value of tm_schedule.detail_id
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public String getDetailId() {
        return detailId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column tm_schedule.detail_id
     * @param detailId  the value for tm_schedule.detail_id
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public void setDetailId( String detailId ) {
        this.detailId = detailId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column tm_schedule.create_time
     * @return  the value of tm_schedule.create_time
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column tm_schedule.create_time
     * @param createTime  the value for tm_schedule.create_time
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public void setCreateTime( Date createTime ) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column tm_schedule.create_user_id
     * @return  the value of tm_schedule.create_user_id
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public Integer getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column tm_schedule.create_user_id
     * @param createUserId  the value for tm_schedule.create_user_id
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public void setCreateUserId( Integer createUserId ) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column tm_schedule.update_time
     * @return  the value of tm_schedule.update_time
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column tm_schedule.update_time
     * @param updateTime  the value for tm_schedule.update_time
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public void setUpdateTime( Date updateTime ) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column tm_schedule.update_user_id
     * @return  the value of tm_schedule.update_user_id
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public Long getUpdateUserId() {
        return updateUserId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column tm_schedule.update_user_id
     * @param updateUserId  the value for tm_schedule.update_user_id
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public void setUpdateUserId( Long updateUserId ) {
        this.updateUserId = updateUserId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column tm_schedule.is_del
     * @return  the value of tm_schedule.is_del
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public String getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column tm_schedule.is_del
     * @param isDel  the value for tm_schedule.is_del
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public void setIsDel( String isDel ) {
        this.isDel = isDel;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column tm_schedule.schedule_desc
     * @return  the value of tm_schedule.schedule_desc
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public String getScheduleDesc() {
        return scheduleDesc;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column tm_schedule.schedule_desc
     * @param scheduleDesc  the value for tm_schedule.schedule_desc
     * @ibatorgenerated  Wed May 13 15:02:13 CST 2015
     */
    public void setScheduleDesc( String scheduleDesc ) {
        this.scheduleDesc = scheduleDesc;
    }
}