package com.tour.dao.ifc;

import com.tour.model.SmRole;
import com.tour.model.SmRoleExample;
import java.util.List;

public interface SmRoleDAO {

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table sm_role
     * @ibatorgenerated  Wed May 13 14:51:35 CST 2015
     */
    int countByExample( SmRoleExample example );

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table sm_role
     * @ibatorgenerated  Wed May 13 14:51:35 CST 2015
     */
    int deleteByExample( SmRoleExample example );

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table sm_role
     * @ibatorgenerated  Wed May 13 14:51:35 CST 2015
     */
    int deleteByPrimaryKey( Integer id );

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table sm_role
     * @ibatorgenerated  Wed May 13 14:51:35 CST 2015
     */
    void insert( SmRole record );

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table sm_role
     * @ibatorgenerated  Wed May 13 14:51:35 CST 2015
     */
    void insertSelective( SmRole record );

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table sm_role
     * @ibatorgenerated  Wed May 13 14:51:35 CST 2015
     */
    List selectByExample( SmRoleExample example );

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table sm_role
     * @ibatorgenerated  Wed May 13 14:51:35 CST 2015
     */
    SmRole selectByPrimaryKey( Integer id );

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table sm_role
     * @ibatorgenerated  Wed May 13 14:51:35 CST 2015
     */
    int updateByExampleSelective( SmRole record, SmRoleExample example );

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table sm_role
     * @ibatorgenerated  Wed May 13 14:51:35 CST 2015
     */
    int updateByExample( SmRole record, SmRoleExample example );

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table sm_role
     * @ibatorgenerated  Wed May 13 14:51:35 CST 2015
     */
    int updateByPrimaryKeySelective( SmRole record );

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table sm_role
     * @ibatorgenerated  Wed May 13 14:51:35 CST 2015
     */
    int updateByPrimaryKey( SmRole record );
}