package com.tour.dao.ifc;

import com.tour.model.TmCustomerGroup;
import com.tour.model.TmCustomerGroupExample;
import java.util.List;

public interface TmCustomerGroupDAO {

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tm_customer_group
     * @ibatorgenerated  Wed May 13 14:51:35 CST 2015
     */
    int countByExample( TmCustomerGroupExample example );

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tm_customer_group
     * @ibatorgenerated  Wed May 13 14:51:35 CST 2015
     */
    int deleteByExample( TmCustomerGroupExample example );

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tm_customer_group
     * @ibatorgenerated  Wed May 13 14:51:35 CST 2015
     */
    int deleteByPrimaryKey( Integer id );

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tm_customer_group
     * @ibatorgenerated  Wed May 13 14:51:35 CST 2015
     */
    void insert( TmCustomerGroup record );

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tm_customer_group
     * @ibatorgenerated  Wed May 13 14:51:35 CST 2015
     */
    void insertSelective( TmCustomerGroup record );

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tm_customer_group
     * @ibatorgenerated  Wed May 13 14:51:35 CST 2015
     */
    List selectByExample( TmCustomerGroupExample example );

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tm_customer_group
     * @ibatorgenerated  Wed May 13 14:51:35 CST 2015
     */
    TmCustomerGroup selectByPrimaryKey( Integer id );

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tm_customer_group
     * @ibatorgenerated  Wed May 13 14:51:35 CST 2015
     */
    int updateByExampleSelective( TmCustomerGroup record, TmCustomerGroupExample example );

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tm_customer_group
     * @ibatorgenerated  Wed May 13 14:51:35 CST 2015
     */
    int updateByExample( TmCustomerGroup record, TmCustomerGroupExample example );

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tm_customer_group
     * @ibatorgenerated  Wed May 13 14:51:35 CST 2015
     */
    int updateByPrimaryKeySelective( TmCustomerGroup record );

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tm_customer_group
     * @ibatorgenerated  Wed May 13 14:51:35 CST 2015
     */
    int updateByPrimaryKey( TmCustomerGroup record );
}