package com.tour.dao.ifc;

import com.tour.model.TmDepartment;
import com.tour.model.TmDepartmentExample;
import java.util.List;

public interface TmDepartmentDAO {

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tm_department
     * @ibatorgenerated  Wed May 13 14:51:35 CST 2015
     */
    int countByExample( TmDepartmentExample example );

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tm_department
     * @ibatorgenerated  Wed May 13 14:51:35 CST 2015
     */
    int deleteByExample( TmDepartmentExample example );

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tm_department
     * @ibatorgenerated  Wed May 13 14:51:35 CST 2015
     */
    int deleteByPrimaryKey( Integer id );

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tm_department
     * @ibatorgenerated  Wed May 13 14:51:35 CST 2015
     */
    void insert( TmDepartment record );

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tm_department
     * @ibatorgenerated  Wed May 13 14:51:35 CST 2015
     */
    void insertSelective( TmDepartment record );

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tm_department
     * @ibatorgenerated  Wed May 13 14:51:35 CST 2015
     */
    List selectByExample( TmDepartmentExample example );

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tm_department
     * @ibatorgenerated  Wed May 13 14:51:35 CST 2015
     */
    TmDepartment selectByPrimaryKey( Integer id );

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tm_department
     * @ibatorgenerated  Wed May 13 14:51:35 CST 2015
     */
    int updateByExampleSelective( TmDepartment record, TmDepartmentExample example );

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tm_department
     * @ibatorgenerated  Wed May 13 14:51:35 CST 2015
     */
    int updateByExample( TmDepartment record, TmDepartmentExample example );

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tm_department
     * @ibatorgenerated  Wed May 13 14:51:35 CST 2015
     */
    int updateByPrimaryKeySelective( TmDepartment record );

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tm_department
     * @ibatorgenerated  Wed May 13 14:51:35 CST 2015
     */
    int updateByPrimaryKey( TmDepartment record );
}