package com.tour.dao.ifc;

import com.tour.model.TmEmployee;
import com.tour.model.TmEmployeeExample;
import java.util.List;

public interface TmEmployeeDAO {

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tm_employee
     * @ibatorgenerated  Wed May 13 14:51:35 CST 2015
     */
    int countByExample( TmEmployeeExample example );

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tm_employee
     * @ibatorgenerated  Wed May 13 14:51:35 CST 2015
     */
    int deleteByExample( TmEmployeeExample example );

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tm_employee
     * @ibatorgenerated  Wed May 13 14:51:35 CST 2015
     */
    int deleteByPrimaryKey( Integer id );

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tm_employee
     * @ibatorgenerated  Wed May 13 14:51:35 CST 2015
     */
    void insert( TmEmployee record );

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tm_employee
     * @ibatorgenerated  Wed May 13 14:51:35 CST 2015
     */
    void insertSelective( TmEmployee record );

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tm_employee
     * @ibatorgenerated  Wed May 13 14:51:35 CST 2015
     */
    List selectByExample( TmEmployeeExample example );

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tm_employee
     * @ibatorgenerated  Wed May 13 14:51:35 CST 2015
     */
    TmEmployee selectByPrimaryKey( Integer id );

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tm_employee
     * @ibatorgenerated  Wed May 13 14:51:35 CST 2015
     */
    int updateByExampleSelective( TmEmployee record, TmEmployeeExample example );

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tm_employee
     * @ibatorgenerated  Wed May 13 14:51:35 CST 2015
     */
    int updateByExample( TmEmployee record, TmEmployeeExample example );

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tm_employee
     * @ibatorgenerated  Wed May 13 14:51:35 CST 2015
     */
    int updateByPrimaryKeySelective( TmEmployee record );

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tm_employee
     * @ibatorgenerated  Wed May 13 14:51:35 CST 2015
     */
    int updateByPrimaryKey( TmEmployee record );
}