package com.tour.dao.ifc;

import com.tour.model.TmInfo;
import com.tour.model.TmInfoExample;
import java.util.List;

public interface TmInfoDAO {

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tm_info
     * @ibatorgenerated  Wed May 13 14:51:35 CST 2015
     */
    int countByExample( TmInfoExample example );

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tm_info
     * @ibatorgenerated  Wed May 13 14:51:35 CST 2015
     */
    int deleteByExample( TmInfoExample example );

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tm_info
     * @ibatorgenerated  Wed May 13 14:51:35 CST 2015
     */
    int deleteByPrimaryKey( Integer id );

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tm_info
     * @ibatorgenerated  Wed May 13 14:51:35 CST 2015
     */
    void insert( TmInfo record );

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tm_info
     * @ibatorgenerated  Wed May 13 14:51:35 CST 2015
     */
    void insertSelective( TmInfo record );

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tm_info
     * @ibatorgenerated  Wed May 13 14:51:35 CST 2015
     */
    List selectByExample( TmInfoExample example );

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tm_info
     * @ibatorgenerated  Wed May 13 14:51:35 CST 2015
     */
    TmInfo selectByPrimaryKey( Integer id );

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tm_info
     * @ibatorgenerated  Wed May 13 14:51:35 CST 2015
     */
    int updateByExampleSelective( TmInfo record, TmInfoExample example );

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tm_info
     * @ibatorgenerated  Wed May 13 14:51:35 CST 2015
     */
    int updateByExample( TmInfo record, TmInfoExample example );

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tm_info
     * @ibatorgenerated  Wed May 13 14:51:35 CST 2015
     */
    int updateByPrimaryKeySelective( TmInfo record );

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tm_info
     * @ibatorgenerated  Wed May 13 14:51:35 CST 2015
     */
    int updateByPrimaryKey( TmInfo record );
}