package com.tour.dao.ifc;

import com.tour.model.TmOrder;
import com.tour.model.TmOrderExample;
import java.util.List;

public interface TmOrderDAO {

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tm_order
     * @ibatorgenerated  Wed May 13 14:51:35 CST 2015
     */
    int countByExample( TmOrderExample example );

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tm_order
     * @ibatorgenerated  Wed May 13 14:51:35 CST 2015
     */
    int deleteByExample( TmOrderExample example );

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tm_order
     * @ibatorgenerated  Wed May 13 14:51:35 CST 2015
     */
    int deleteByPrimaryKey( Integer id );

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tm_order
     * @ibatorgenerated  Wed May 13 14:51:35 CST 2015
     */
    void insert( TmOrder record );

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tm_order
     * @ibatorgenerated  Wed May 13 14:51:35 CST 2015
     */
    void insertSelective( TmOrder record );

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tm_order
     * @ibatorgenerated  Wed May 13 14:51:35 CST 2015
     */
    List selectByExample( TmOrderExample example );

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tm_order
     * @ibatorgenerated  Wed May 13 14:51:35 CST 2015
     */
    TmOrder selectByPrimaryKey( Integer id );

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tm_order
     * @ibatorgenerated  Wed May 13 14:51:35 CST 2015
     */
    int updateByExampleSelective( TmOrder record, TmOrderExample example );

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tm_order
     * @ibatorgenerated  Wed May 13 14:51:35 CST 2015
     */
    int updateByExample( TmOrder record, TmOrderExample example );

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tm_order
     * @ibatorgenerated  Wed May 13 14:51:35 CST 2015
     */
    int updateByPrimaryKeySelective( TmOrder record );

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tm_order
     * @ibatorgenerated  Wed May 13 14:51:35 CST 2015
     */
    int updateByPrimaryKey( TmOrder record );
}