package com.tour.dao.ifc;

import com.tour.model.TmSchedule;
import com.tour.model.TmScheduleExample;
import java.util.List;

public interface TmScheduleDAO {

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tm_schedule
     * @ibatorgenerated  Wed May 13 14:51:35 CST 2015
     */
    int countByExample( TmScheduleExample example );

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tm_schedule
     * @ibatorgenerated  Wed May 13 14:51:35 CST 2015
     */
    int deleteByExample( TmScheduleExample example );

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tm_schedule
     * @ibatorgenerated  Wed May 13 14:51:35 CST 2015
     */
    int deleteByPrimaryKey( Integer id );

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tm_schedule
     * @ibatorgenerated  Wed May 13 14:51:35 CST 2015
     */
    void insert( TmSchedule record );

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tm_schedule
     * @ibatorgenerated  Wed May 13 14:51:35 CST 2015
     */
    void insertSelective( TmSchedule record );

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tm_schedule
     * @ibatorgenerated  Wed May 13 14:51:35 CST 2015
     */
    List selectByExample( TmScheduleExample example );

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tm_schedule
     * @ibatorgenerated  Wed May 13 14:51:35 CST 2015
     */
    TmSchedule selectByPrimaryKey( Integer id );

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tm_schedule
     * @ibatorgenerated  Wed May 13 14:51:35 CST 2015
     */
    int updateByExampleSelective( TmSchedule record, TmScheduleExample example );

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tm_schedule
     * @ibatorgenerated  Wed May 13 14:51:35 CST 2015
     */
    int updateByExample( TmSchedule record, TmScheduleExample example );

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tm_schedule
     * @ibatorgenerated  Wed May 13 14:51:35 CST 2015
     */
    int updateByPrimaryKeySelective( TmSchedule record );

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tm_schedule
     * @ibatorgenerated  Wed May 13 14:51:35 CST 2015
     */
    int updateByPrimaryKey( TmSchedule record );
}